'use strict';

const assert=require('assert');
const events=require('events');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const carrier=require('./bridge/niannian_redraw_step02_windows_mac_phase_carrier');
const launcher=require('./bridge/niannian_redraw_step02_mac_app_phase_worker_launcher');
const transport=require('./bridge/niannian_redraw_step02_mac_app_phase_transport');
const step02=require('./bridge/niannian_redraw_step02_vertical');
const fixture=require('./test_niannian_redraw_step02_mac_app_phase_transport');

async function processExists(pid){try{process.kill(pid,0);return true;}catch{return false;}}
async function waitGone(pid){for(let i=0;i<30;i++){if(!await processExists(pid))return true;await new Promise(resolve=>setTimeout(resolve,50));}return false;}
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'step02-carrier-'));const oldSentinel=process.env.NIANNIAN_FORBIDDEN_SENTINEL;try{
  process.env.NIANNIAN_FORBIDDEN_SENTINEL='must-not-propagate';await carrier.runProcess(process.execPath,['-e','process.exit(process.env.NIANNIAN_FORBIDDEN_SENTINEL?9:0)'],2000);
  const timeoutPidPath=path.join(root,'timeout-child.pid'),treeScript=`const fs=require('fs'),cp=require('child_process'),c=cp.spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'ignore'});fs.writeFileSync(${JSON.stringify(timeoutPidPath)},String(c.pid));setInterval(()=>{},1000);`;await assert.rejects(()=>carrier.runProcess(process.execPath,['-e',treeScript],120),error=>error.code==='STEP02_CARRIER_TIMEOUT');const timeoutPid=Number(await fsp.readFile(timeoutPidPath,'utf8'));assert.equal(await waitGone(timeoutPid),true);
  const abortPidPath=path.join(root,'abort-child.pid'),abortScript=`const fs=require('fs'),cp=require('child_process'),c=cp.spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'ignore'});fs.writeFileSync(${JSON.stringify(abortPidPath)},String(c.pid));setInterval(()=>{},1000);`,controller=new AbortController();const aborted=carrier.runProcess(process.execPath,['-e',abortScript],5000,controller.signal);while(!await fsp.stat(abortPidPath).then(()=>true,()=>false))await new Promise(resolve=>setTimeout(resolve,10));controller.abort();await assert.rejects(()=>aborted,error=>error.code==='STEP02_CARRIER_CLIENT_DISCONNECTED');const abortPid=Number(await fsp.readFile(abortPidPath,'utf8'));assert.equal(await waitGone(abortPid),true);
  let spawnOptions=null;const fakeChild=new events.EventEmitter();fakeChild.pid=12345;fakeChild.kill=()=>{};process.nextTick(()=>fakeChild.emit('exit',0,null));await launcher.launch({args:['--package','/tmp/package','--manifest-sha','a'.repeat(64)],spawnSync:()=>({status:0,stdout:'synthetic-key-never-printed\n'}),spawn:(command,args,options)=>{spawnOptions=options;return fakeChild;},detached:false,stdio:'ignore'});assert.equal(spawnOptions.env.NIANNIAN_FORBIDDEN_SENTINEL,undefined);assert.equal(spawnOptions.env.KRILL_CODEX_API_KEY!==undefined,true);assert.equal(Object.keys(spawnOptions.env).some(name=>/MIMO|PADDLE|TOKEN/i.test(name)),false);
  const current=await fixture.build(root,'receipt'),packageRoot=path.join(current.job,'package'),exported=await transport.exportWindowsPhase({step02Root:current.stepRoot,packageRoot}),workspace=path.join(current.job,'mac');await transport.importDispatchToMac({packageRoot,expectedManifestSha256:exported.evidence.sha256,workspacePath:workspace});await fixture.writeReturn(workspace,current.dispatch);const finalized=await transport.finalizeMacReturn({workspacePath:workspace}),importRoot=path.join(current.stepRoot,'imported',current.dispatch.phase_key);await transport.importMacReturnToWindows({returnRoot:workspace,expectedManifestSha256:finalized.evidence.sha256,windowsReturnRoot:importRoot});const first=await carrier.createTrustedReceipt({importRoot,dispatch:current.dispatch,testMode:true}),second=await carrier.createTrustedReceipt({importRoot,dispatch:current.dispatch,testMode:true});assert.equal(first.evidence.sha256,second.evidence.sha256);assert.equal(first.value.step04_ready,undefined);assert.equal(first.value.test_only,true);
  for(const name of ['step02_app_server_audit.json','step02_app_server_response.json','step02_return_manifest.json']){const exact=path.join(importRoot,name),original=await fsp.readFile(exact);await fsp.appendFile(exact,' ');await assert.rejects(()=>carrier.createTrustedReceipt({importRoot,dispatch:current.dispatch,testMode:true}),error=>String(error.code||error.message).includes('TAMPER')||String(error.code||error.message).includes('CONFLICT'));await fsp.writeFile(exact,original);}
  const oldEnabled=process.env.NIANNIAN_STEP02_CARRIER_ENABLED;delete process.env.NIANNIAN_STEP02_CARRIER_ENABLED;await assert.rejects(()=>carrier.runCarrier({project:{id:'NN-X',ownerId:'owner'},jobRoot:root,ownerId:'owner',ownerActionEventId:'action'}),error=>error.code==='STEP02_CARRIER_PRODUCTION_DISABLED');if(oldEnabled!==undefined)process.env.NIANNIAN_STEP02_CARRIER_ENABLED=oldEnabled;
  process.stdout.write(JSON.stringify({ok:true,status:'PASS_SYNTHETIC_WINDOWS_MAC_STEP02_CARRIER',verified:['minimal child environment excludes forbidden sentinel','timeout terminates full child tree','client abort terminates full child tree','launcher forwards only allowlisted environment plus Krill key','stable carrier receipt replay SHA','tampered App audit/response/return rejected','candidate receipt remains test-only and does not unlock Step04','production carrier defaults disabled'],real_mac_turn_started:false,source_001_read:false,provider_called:false,spend_requested:false,local_image_editing_requested:false})+'\n');
}finally{if(oldSentinel===undefined)delete process.env.NIANNIAN_FORBIDDEN_SENTINEL;else process.env.NIANNIAN_FORBIDDEN_SENTINEL=oldSentinel;await fsp.rm(root,{recursive:true,force:true});}}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
