const assert = require('assert/strict');
const {createPlanningClient,planningSchema,validatePlanningResult} = require('./bridge/niannian_step03_planner');

function response(value,status=200){return{ok:status>=200&&status<300,status,async json(){return{output_text:JSON.stringify(value)};}};}
function fixture(){return{characters:[{character_id:'C001',source_identity:'女主',localized_identity:'Lucia',function:'核心冲突当事人',importance:'lead',target_casting:'可信墨西哥女性',age_band:'25-32',relationship:'核心人物',profession:'律师',appearance_shot_ids:['S001']}],continuity_ledger:[{appearance_id:'AP-C001-01',character_id:'C001',continuity_block_id:'CB-C001-01',source_shot_ids:['S001'],source_wardrobe_evidence:'职业套装',decision:'first_appearance',change_reason:'首次出现'}],assets:[{asset_id:'A-PHONE-001',canonical_type:'phone-ui',name:'手机证据页',description:'墨西哥西语手机证据页',owner_character_id:null,dependencies:[],used_by_shots:['S001'],prompt:'生成写实手机证据页，文字清晰且只使用墨西哥西班牙语。',reference_strategy:'text_to_image',visible_text_original:'证据',visible_text_localized:'Prueba'}],group_annotations:[{group_id:'G001',difficulty_types:['手机文字'],asset_ids:['A-PHONE-001'],visual_goal:'手机朝向镜头且文字清晰'}]};}

async function run(){
  const context={shots:[{shot_id:'S001'}],groups:[{group_id:'G001'}],locale:'es-MX'};assert.equal(planningSchema().additionalProperties,false);assert.equal(validatePlanningResult(fixture(),context).assets[0].canonical_type,'phone-ui');
  const repeated={...fixture(),continuity_ledger:[fixture().continuity_ledger[0],fixture().continuity_ledger[0]]};assert.equal(validatePlanningResult(repeated,context).continuity_ledger.length,1,'identical continuity rows should be deduplicated');
  const collision={...fixture(),continuity_ledger:[fixture().continuity_ledger[0],{...fixture().continuity_ledger[0],source_wardrobe_evidence:'晚宴礼服',decision:'wardrobe_change',change_reason:'场景换装'}]};const repaired=validatePlanningResult(collision,context);assert.equal(repaired.continuity_ledger.length,2);assert.equal(new Set(repaired.continuity_ledger.map(row=>row.appearance_id)).size,2,'different continuity rows must retain data with deterministic unique ids');assert.match(repaired.continuity_ledger[1].appearance_id,/^AP-C001-[a-f0-9]{16}$/);
  const mixedShots={...fixture(),characters:[{...fixture().characters[0],appearance_shot_ids:['S001','S999','S001']}]};assert.deepEqual(validatePlanningResult(mixedShots,context).characters[0].appearance_shot_ids,['S001'],'unknown and duplicate shot ids should be removed when valid evidence remains');
  const continuityFallback={...fixture(),characters:[{...fixture().characters[0],appearance_shot_ids:['S999']}]};assert.deepEqual(validatePlanningResult(continuityFallback,context).characters[0].appearance_shot_ids,['S001'],'continuity evidence should repair an empty character appearance list');
  const noEvidence={...fixture(),characters:[{...fixture().characters[0],appearance_shot_ids:['S999']}],continuity_ledger:[]};assert.throws(()=>validatePlanningResult(noEvidence,context),error=>error.code==='STEP03_PLANNER_CHARACTER_SHOTS_INVALID');
  const ownerRepair={...fixture(),assets:[{...fixture().assets[0],asset_id:'A-WARDROBE-001',canonical_type:'wardrobe',owner_character_id:'C001',dependencies:[],reference_strategy:'character_image_to_image',visible_text_original:null,visible_text_localized:null}],group_annotations:[{...fixture().group_annotations[0],asset_ids:['A-WARDROBE-001']}]};assert.deepEqual(validatePlanningResult(ownerRepair,context).assets[0].dependencies,['C001'],'owner character should repair a missing image-to-image dependency');
  const shotRepair={...ownerRepair,assets:[{...ownerRepair.assets[0],owner_character_id:null}]};assert.deepEqual(validatePlanningResult(shotRepair,context).assets[0].dependencies,['C001'],'a unique character in the asset shots should repair the missing dependency');
  const ambiguousRepair={...shotRepair,characters:[...shotRepair.characters,{...shotRepair.characters[0],character_id:'C002',localized_identity:'Mateo',importance:'important'}]};assert.throws(()=>validatePlanningResult(ambiguousRepair,context),error=>error.code==='STEP03_PLANNER_ASSET_REFERENCE_INVALID','ambiguous character dependencies must remain a hard validation failure');
  const sourceEthnicityLeak={...fixture(),characters:[{...fixture().characters[0],target_casting:'Mujer joven china con el rostro de la actriz original'}]};assert.throws(()=>validatePlanningResult(sourceEthnicityLeak,context),error=>error.code==='STEP03_PLANNER_SOURCE_ETHNICITY_LEAK');
  const missingMarketCasting={...fixture(),characters:[{...fixture().characters[0],target_casting:'Mujer joven elegante y expresiva'}]};assert.throws(()=>validatePlanningResult(missingMarketCasting,context),error=>error.code==='STEP03_PLANNER_MARKET_CASTING_REQUIRED');
  assert.throws(()=>validatePlanningResult({...fixture(),assets:[{...fixture().assets[0],visible_text_localized:null}]},context),error=>error.code==='STEP03_PLANNER_LOCALIZED_TEXT_REQUIRED');
  let requestBody=null;const client=createPlanningClient({baseUrl:'https://krill.example/v1',apiKey:'test-only',instructions:'locked bundle',fetchImpl:async(url,init)=>{requestBody=JSON.parse(init.body);return response(fixture());}});const result=await client.plan({locale:'es-MX',market:'Mexico',language:'Spanish (Mexico)',global_context:{},...context});assert.equal(result.characters[0].character_id,'C001');assert.equal(requestBody.text.format.type,'json_schema');assert.equal(requestBody.text.format.strict,true);assert.match(requestBody.instructions,/不得调用工具/);assert.doesNotMatch(JSON.stringify(requestBody),/mcgrox/i);
  const invalidClient=createPlanningClient({baseUrl:'https://krill.example/v1',apiKey:'test-only',instructions:'locked bundle',fetchImpl:async()=>response({...fixture(),group_annotations:[{...fixture().group_annotations[0],group_id:'G999'}]})});await assert.rejects(()=>invalidClient.plan({locale:'es-MX',market:'Mexico',language:'Spanish (Mexico)',global_context:{},...context}),error=>error.code==='STEP03_PLANNER_GROUP_REFERENCE_INVALID');
  process.stdout.write(JSON.stringify({ok:true,strict_json_schema:true,krill_only:true,continuity_collision_auto_repair:true,shot_reference_auto_repair:true,asset_dependency_auto_repair:true,ambiguous_asset_dependency_rejected:true,source_ethnicity_leak_rejected:true,market_casting_required:true,asset_text_guard:true,reference_validation:true})+'\n');
}
run().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
