'use strict';

const assert=require('assert');
const crypto=require('crypto');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const {buildStep01EvidencePackage,validateStep01EvidencePackage}=require('./bridge/niannian_step01_evidence_package');
const {appendEvidenceEvent,readEvidenceEvents,reduceEvidenceEvents}=require('./bridge/niannian_step01_evidence_events');

async function writeJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});await fsp.writeFile(filePath,JSON.stringify(value,null,2)+'\n');}
async function pointer(root,relative){const exact=path.join(root,relative);const bytes=await fsp.readFile(exact);return {relative_path:relative.replace(/\\/g,'/'),sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length};}

async function main(){
  const root=await fsp.mkdtemp(path.join(os.tmpdir(),'niannian-step01-evidence-delivery-'));
  try{
    const sourceRoot=path.join(root,'return'),outputRoot=path.join(root,'canonical');await fsp.mkdir(path.join(sourceRoot,'evidence','frames'),{recursive:true});
    await writeJson(path.join(sourceRoot,'evidence','ffprobe.json'),{duration_seconds:12,width:1080,height:1920,fps:25});
    await writeJson(path.join(sourceRoot,'evidence','shots.json'),{status:'accepted',detector:'TransNetV2',shots:[{shot_id:'1',start_sec:0,end_sec:6},{shot_id:'2',start_sec:6,end_sec:12}]});
    const rows=[];const native=[];for(const shot of ['1','2'])for(const point of ['start','mid','end']){const relative='evidence/frames/'+shot+'-'+point+'.png';await fsp.writeFile(path.join(sourceRoot,relative),Buffer.from('png-evidence-'+shot+'-'+point));const evidence=await pointer(sourceRoot,relative);rows.push({shot_id:shot,point,...evidence});native.push(evidence);}
    await writeJson(path.join(sourceRoot,'evidence','supplement.json'),{rows});
    await writeJson(path.join(sourceRoot,'evidence','native.json'),{frames:native});
    await writeJson(path.join(sourceRoot,'evidence','chunks.json'),[{chunk_index:1,start_sec:0,end_sec:12}]);
    await fsp.writeFile(path.join(sourceRoot,'evidence','audio.wav'),Buffer.from('wav'));
    await fsp.writeFile(path.join(sourceRoot,'evidence','audio.csv'),'start_sec,end_sec,text\n0,2,hello\n');
    await writeJson(path.join(sourceRoot,'evidence','mimo.json'),{status:'passed'});await writeJson(path.join(sourceRoot,'evidence','aligner.json'),{status:'passed'});
    await fsp.writeFile(path.join(sourceRoot,'evidence','ocr.csv'),'start_sec,end_sec,text\n1,2,door\n');await writeJson(path.join(sourceRoot,'evidence','ocr.json'),{status:'passed'});
    await writeJson(path.join(sourceRoot,'evidence','validation.json'),{status:'passed',hard_gates:{artifact_hashes_pass:true}});
    const manifest={schema_version:'step01_evidence_manifest_v1',status:'verified',profile:'hq_full',downstream_consumable:true,test_only:false,source_sha256:'a'.repeat(64),source_bytes:123,source:{ffprobe:await pointer(sourceRoot,'evidence/ffprobe.json')},minute_chunks:{index:await pointer(sourceRoot,'evidence/chunks.json')},native_frames:{manifest:await pointer(sourceRoot,'evidence/native.json'),frames:native},transnet:{accepted_shots:await pointer(sourceRoot,'evidence/shots.json'),shot_supplement:await pointer(sourceRoot,'evidence/supplement.json')},audio:{wav:await pointer(sourceRoot,'evidence/audio.wav'),event_ledger:await pointer(sourceRoot,'evidence/audio.csv'),mimo_transcript_receipt:await pointer(sourceRoot,'evidence/mimo.json'),forced_aligner_receipt:await pointer(sourceRoot,'evidence/aligner.json')},ocr:{ledger:await pointer(sourceRoot,'evidence/ocr.csv'),receipt:await pointer(sourceRoot,'evidence/ocr.json')},validation:{receipt:await pointer(sourceRoot,'evidence/validation.json')},artifacts:[]};
    await writeJson(path.join(sourceRoot,'step01_evidence_manifest.json'),manifest);
    const project={id:'NN-EVIDENCE-DELIVERY-001',sourceRevision:1,source:{sha256:'a'.repeat(64),bytes:123}},analysisRun={id:'analysis-1-evidence'};
    const built=await buildStep01EvidencePackage({sourceRoot,outputRoot,project,analysisRun});const validated=await validateStep01EvidencePackage({outputRoot,expected:{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1}});assert.equal(validated.index.status,'evidence_ready');assert.equal(validated.index.timeline.length,2);assert.equal(validated.delivery.included_files.some(item=>item.source_relative_path==='evidence/frames/1-start.png'),true);assert.equal(validated.delivery.exclusions.includes('creative_settings'),true);assert(built.bundle.bytes>0);
    const originalSupplement=structuredClone(rows),originalShots={status:'accepted',detector:'TransNetV2',shots:[{shot_id:'1',start_sec:0,end_sec:6},{shot_id:'2',start_sec:6,end_sec:12}]};
    await writeJson(path.join(sourceRoot,'evidence','supplement.json'),{rows:[...rows,rows[0]]});manifest.transnet.shot_supplement=await pointer(sourceRoot,'evidence/supplement.json');await writeJson(path.join(sourceRoot,'step01_evidence_manifest.json'),manifest);await assert.rejects(()=>buildStep01EvidencePackage({sourceRoot,outputRoot:path.join(root,'duplicate-frame'),project,analysisRun}),/shot_supplement_count_invalid/);
    const unknownRows=structuredClone(originalSupplement);unknownRows[0].shot_id='unknown';await writeJson(path.join(sourceRoot,'evidence','supplement.json'),{rows:unknownRows});manifest.transnet.shot_supplement=await pointer(sourceRoot,'evidence/supplement.json');await writeJson(path.join(sourceRoot,'step01_evidence_manifest.json'),manifest);await assert.rejects(()=>buildStep01EvidencePackage({sourceRoot,outputRoot:path.join(root,'unknown-shot'),project,analysisRun}),/shot_id_set_mismatch/);
    await writeJson(path.join(sourceRoot,'evidence','supplement.json'),{rows:originalSupplement});await writeJson(path.join(sourceRoot,'evidence','shots.json'),{...originalShots,shots:[{shot_id:'1',start_sec:0,end_sec:8},{shot_id:'2',start_sec:7,end_sec:12}]});manifest.transnet.shot_supplement=await pointer(sourceRoot,'evidence/supplement.json');manifest.transnet.accepted_shots=await pointer(sourceRoot,'evidence/shots.json');await writeJson(path.join(sourceRoot,'step01_evidence_manifest.json'),manifest);await assert.rejects(()=>buildStep01EvidencePackage({sourceRoot,outputRoot:path.join(root,'overlap'),project,analysisRun}),/timeline_order_invalid/);
    await writeJson(path.join(sourceRoot,'evidence','shots.json'),originalShots);manifest.transnet.accepted_shots=await pointer(sourceRoot,'evidence/shots.json');await writeJson(path.join(sourceRoot,'step01_evidence_manifest.json'),manifest);
    const eventPath=path.join(root,'evidence_events.jsonl');const base={project_id:project.id,analysis_run_id:analysisRun.id,source_revision:1,source_sha256:project.source.sha256,dispatch_id:'STEP01EMP-EVIDENCE-001',phase_key:'phase-1'};for(const [type,status,evidence_sha256] of [['analysis_run_created','queued','1'.repeat(64)],['dispatch_claimed','codex_dispatched','2'.repeat(64)],['codex_turn_started','codex_running','3'.repeat(64)],['skill_route_selected','mx-shortdrama-01-frame-extract','4'.repeat(64)],['analysis_service_task_reconciled','used','9'.repeat(64)],['codex_turn_completed','completed','5'.repeat(64)],['return_manifest_received','return_received','6'.repeat(64)],['artifact_paths_verified','verified','7'.repeat(64)],['step01_validation_passed','passed','8'.repeat(64)],['step01_evidence_accepted','evidence_ready',built.bundle.sha256]])await appendEvidenceEvent(eventPath,{...base,type,status,evidence_sha256});
    let reduced=reduceEvidenceEvents(await readEvidenceEvents(eventPath),{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1});assert.equal(reduced.status,'evidence_ready');assert.equal(reduced.accepted,true);assert.equal(reduced.delivered,false);await appendEvidenceEvent(eventPath,{...base,type:'step01_evidence_delivered',status:'delivered',evidence_sha256:built.bundle.sha256});reduced=reduceEvidenceEvents(await readEvidenceEvents(eventPath),{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1});assert.equal(reduced.delivered,true);
    await appendEvidenceEvent(eventPath,{...base,type:'blocker_observed',status:'blocked_transport',evidence_sha256:'b'.repeat(64),schema_version:'forged',event_id:'forged',at:'1970-01-01T00:00:00.000Z'});const protectedRows=await readEvidenceEvents(eventPath),protectedBlocker=protectedRows[protectedRows.length-1];assert.equal(protectedBlocker.schema_version,'niannian_step01_evidence_event_v1');assert.notEqual(protectedBlocker.event_id,'forged');assert.notEqual(protectedBlocker.at,'1970-01-01T00:00:00.000Z');reduced=reduceEvidenceEvents(protectedRows,{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1});assert.equal(reduced.status,'blocked_transport');
    const mismatchPath=path.join(root,'delivery-mismatch.jsonl');for(const [type,status,evidence_sha256] of [['analysis_run_created','queued','1'.repeat(64)],['dispatch_claimed','codex_dispatched','2'.repeat(64)],['codex_turn_started','codex_running','3'.repeat(64)],['skill_route_selected','mx-shortdrama-01-frame-extract','4'.repeat(64)],['analysis_service_task_reconciled','used','9'.repeat(64)],['codex_turn_completed','completed','5'.repeat(64)],['return_manifest_received','return_received','6'.repeat(64)],['artifact_paths_verified','verified','7'.repeat(64)],['step01_validation_passed','passed','8'.repeat(64)],['step01_evidence_accepted','evidence_ready',built.bundle.sha256],['step01_evidence_delivered','delivered','f'.repeat(64)]])await appendEvidenceEvent(mismatchPath,{...base,type,status,evidence_sha256});const mismatchRows=await readEvidenceEvents(mismatchPath);assert.throws(()=>reduceEvidenceEvents(mismatchRows,{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1}),/delivery_sha_mismatch/);
    const mixedPath=path.join(root,'mixed-events.jsonl'),attemptA={...base,dispatch_id:'dispatch-A',phase_key:'phase-A'},attemptB={...base,dispatch_id:'dispatch-B',phase_key:'phase-B'};await appendEvidenceEvent(mixedPath,{...attemptA,type:'analysis_run_created',status:'queued',evidence_sha256:'1'.repeat(64)});for(const type of ['dispatch_claimed','codex_turn_started','skill_route_selected','analysis_service_task_reconciled'])await appendEvidenceEvent(mixedPath,{...attemptA,type,status:'partial',evidence_sha256:crypto.createHash('sha256').update(type).digest('hex')});for(const type of ['codex_turn_completed','return_manifest_received','artifact_paths_verified','step01_validation_passed','step01_evidence_accepted'])await appendEvidenceEvent(mixedPath,{...attemptB,type,status:type==='step01_evidence_accepted'?'evidence_ready':'partial',evidence_sha256:crypto.createHash('sha256').update('B-'+type).digest('hex')});const mixedEvents=await readEvidenceEvents(mixedPath);assert.throws(()=>reduceEvidenceEvents(mixedEvents,{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1}),/acceptance_event_chain_incomplete/);
    await fsp.appendFile(built.bundle.exact_path,'tamper');await assert.rejects(()=>validateStep01EvidencePackage({outputRoot,expected:{projectId:project.id,analysisRunId:analysisRun.id,sourceSha256:project.source.sha256,sourceRevision:1}}),/delivery_hash_mismatch/);
    process.stdout.write(JSON.stringify({ok:true,verified:['source-only customer evidence index','exact start/mid/end coverage with no duplicate or unknown shot IDs','monotonic non-overlapping source timeline','explicit delivery allowlist and exclusions','zip SHA receipt','event replay binds an ordered chain to one dispatch and phase','delivery is bound to the accepted attempt','tampered bundle rejected']})+'\n');
  }finally{await fsp.rm(root,{recursive:true,force:true});}
}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
