'use strict';

const assert=require('assert/strict');
const path=require('path');
const {chromium}=require('playwright');

const projectId='STEP05-BROWSER-FIXTURE';
const localizationRevision='loc-browser-r1';
const plan={plan_id:'PLAN-V01',etag:'"plan-1"',step02_variant_id:'VAR-1',step02_confirmed_sha256:'b'.repeat(64),step01_source_ledger_sha256:'c'.repeat(64),substep:'characters',progress:{important_characters_confirmed:0,important_characters_total:1,assets_accepted:0,assets_total:0,groups_confirmed:0,groups_total:0},characters:[{character_id:'CHAR-1',source_identity:'原片女主',localized_identity:'Lucia',importance:'lead',function:'核心人物',status:'awaiting_candidates',candidate_ids:[],appearance_shot_ids:[]}],assets:[],groups:[],firstframes:[],tasks:[]};
const pendingProjection={status:'等待确认视频参考图',counts:{system_checked:1,needs_action:1,video_reference_total:2,video_reference_pending:2},support_assets:{system_checked:[{ref_key:'SUPPORT-HERO',title:'女主人物支撑图',status:'系统已检查',problem_cn:'',actions:[]}],needs_action:[{ref_key:'SUPPORT-PROP',title:'关键道具支撑图',status:'需要您处理',problem_cn:'道具轮廓与来源事实不一致',actions:['reroll','remove','return_upstream']}]},video_reference_cards:[{ref_key:'FIRST-V01',canonical_type:'video_first_frame_anchor',source_fact:{label:'原片 V01 起始画面',start_sec:0},candidate_url:'/api/projects/'+projectId+'/step05/references/FIRST-V01/candidate',video_group:'V01',purpose:'V01 首帧',reference_duty:'锁定 V01 开场构图与动作',related_support_assets:[{ref_key:'SUPPORT-HERO',title:'女主人物支撑图'}],decision:'待确认',issue_category:'',note:''},{ref_key:'IDENTITY-HERO',canonical_type:'video_upload_non_first_ref',source_fact:{label:'人物职责来源事实'},candidate_url:'/api/projects/'+projectId+'/step05/references/IDENTITY-HERO/candidate',video_group:'V01',purpose:'女主身份基准图',reference_duty:'锁定女主身份一致性',related_support_assets:[{ref_key:'SUPPORT-HERO',title:'女主人物支撑图'}],decision:'待确认',issue_category:'',note:''}],video_references_confirmed:false};

(async()=>{
  const browser=await chromium.launch({headless:true});let confirmAttempts=0,confirmationPosts=0,currentEtag='"step05-browser-1"',projection=JSON.parse(JSON.stringify(pendingProjection)),actionPosts={reject:0,reroll:0,support:0};
  try{
    const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),pageErrors=[];
    page.on('pageerror',error=>pageErrors.push(error.message));
    await page.route('http://step05.test/**',async route=>{
      const request=route.request(),url=new URL(request.url()),pathname=url.pathname,headers={'Content-Type':'application/json'};
      if(pathname==='/'){await route.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body><main id="redrawStudioContent"></main></body></html>'});return;}
      if(pathname==='/api/projects'){await route.fulfill({status:200,headers,body:JSON.stringify({projects:[{id:projectId,source:{previewUrl:''}}]})});return;}
      if(pathname.endsWith('/localization-confirmation')){await route.fulfill({status:200,headers:{...headers,'X-Localization-Revision':localizationRevision,ETag:'"loc-1"'},body:JSON.stringify({localization:{downstream_ready:true,candidate:{status:'candidate'}}})});return;}
      if(pathname.endsWith('/step02/variants')){await route.fulfill({status:200,headers,body:JSON.stringify({variants:[{variant_id:'VAR-1',locale:'es-MX',status:'confirmed',confirmed_sha256:'b'.repeat(64)}]})});return;}
      if(pathname.includes('/shot-review')){await route.fulfill({status:200,headers,body:JSON.stringify({shots:[]})});return;}
      if(pathname.endsWith('/step01/shot-ledger')){await route.fulfill({status:200,headers,body:JSON.stringify({ledger:{snapshot_sha256:'c'.repeat(64)}})});return;}
      if(pathname.endsWith('/step03/plans')){await route.fulfill({status:200,headers,body:JSON.stringify({plans:[plan]})});return;}
      if(pathname.endsWith('/step03/plans/PLAN-V01')){await route.fulfill({status:200,headers:{...headers,ETag:'"plan-1"'},body:JSON.stringify({plan})});return;}
      if(pathname.endsWith('/step05/references')&&request.method()==='GET'){await route.fulfill({status:200,headers:{...headers,ETag:currentEtag},body:JSON.stringify({references:projection})});return;}
      if(pathname.endsWith('/step05/references/confirm-batch')&&request.method()==='POST'){
        confirmationPosts+=1;const body=JSON.parse(request.postData()||'{}');assert.equal(request.headers()['x-localization-revision'],localizationRevision);assert.ok(request.headers()['if-match']);assert.ok(request.headers()['idempotency-key']);assert.deepEqual(body.decisions.map(row=>row.decision),['pass','pass']);confirmAttempts+=1;
        if(confirmAttempts===1){currentEtag='"step05-browser-2"';await route.fulfill({status:412,headers,body:JSON.stringify({error:'视频参考图已更新，请重新读取'})});return;}
        projection=JSON.parse(JSON.stringify(pendingProjection));projection.status='视频参考图已确认';projection.counts.video_reference_pending=0;projection.video_references_confirmed=true;for(const card of projection.video_reference_cards)card.decision='通过';currentEtag='"step05-browser-3"';await route.fulfill({status:200,headers:{...headers,ETag:currentEtag},body:JSON.stringify({result:{confirmed_count:2,idempotent:false},references:projection})});return;
      }
      if(pathname.endsWith('/step05/references/IDENTITY-HERO/reject')&&request.method()==='POST'){const body=JSON.parse(request.postData()||'{}');assert.equal(body.issue_category,'构图不一致');assert.equal(body.note,'人物面部与来源事实不一致');actionPosts.reject+=1;projection.video_reference_cards.find(card=>card.ref_key==='IDENTITY-HERO').decision='不通过';currentEtag='"step05-browser-rejected"';await route.fulfill({status:200,headers:{...headers,ETag:currentEtag},body:JSON.stringify({references:projection})});return;}
      if(pathname.endsWith('/step05/references/IDENTITY-HERO/reroll')&&request.method()==='POST'){actionPosts.reroll+=1;projection.video_reference_cards.find(card=>card.ref_key==='IDENTITY-HERO').decision='待确认';currentEtag='"step05-browser-rerolled"';await route.fulfill({status:202,headers:{...headers,ETag:currentEtag},body:JSON.stringify({references:projection})});return;}
      if(pathname.endsWith('/step05/references/SUPPORT-PROP/action')&&request.method()==='POST'){const body=JSON.parse(request.postData()||'{}');assert.equal(body.action,'reroll');actionPosts.support+=1;currentEtag='"step05-browser-support-action"';await route.fulfill({status:202,headers:{...headers,ETag:currentEtag},body:JSON.stringify({references:projection})});return;}
      if(pathname.includes('/step05/references/')&&/(candidate|source-preview)$/.test(pathname)){await route.fulfill({status:404,headers,body:JSON.stringify({error:'fixture media unavailable'})});return;}
      await route.fulfill({status:404,headers,body:JSON.stringify({error:'fixture route unavailable'})});
    });
    await page.goto('http://step05.test/#redraw/'+projectId+'/stage/04/market/es-MX');
    await page.addStyleTag({path:path.join(__dirname,'product.css')});await page.addScriptTag({path:path.join(__dirname,'mvp-step03-r1.js')});
    await page.waitForFunction(()=>document.querySelector('.step03-stage')?.textContent.includes('Lucia'));
    await page.click('[data-step03-substep="confirmation"]');await page.waitForSelector('.step05-reference-card');
    assert.equal(await page.locator('.step05-reference-card').count(),2);assert.match(await page.locator('.step05-support-lanes').innerText(),/系统已检查[\s\S]*需要您处理/);assert.match(await page.locator('.step05-reference-workspace').innerText(),/原片 V01 起始画面[\s\S]*当前候选[\s\S]*中文参考职责/);
    const unsafe=await page.locator('.step05-reference-workspace').innerText();assert.doesNotMatch(unsafe,/content_sha|authority_revision|localization_revision|provider|receipt|locked_prompt|[A-Z]:[\\/]|signature=/i);
    const rejectRadio=page.locator('input[data-step05-decision="IDENTITY-HERO"][value="不通过"]');await rejectRadio.focus();await page.keyboard.press('Space');const category=page.locator('[data-step05-issue-category="IDENTITY-HERO"]');await category.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const note=page.locator('[data-step05-note="IDENTITY-HERO"]');await note.focus();await page.keyboard.type('人物面部与来源事实不一致');await page.locator('[data-step05-reject="IDENTITY-HERO"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-step05-reference-card="IDENTITY-HERO"]')?.textContent.includes('不通过'));await page.locator('[data-step05-reroll="IDENTITY-HERO"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-step05-reference-card="IDENTITY-HERO"]')?.textContent.includes('待确认'));
    await page.locator('[data-step05-support-action="reroll"][data-ref-key="SUPPORT-PROP"]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-step03-substep="assets"]')?.classList.contains('is-active'));await page.locator('[data-step03-substep="confirmation"]').focus();await page.keyboard.press('Enter');await page.waitForSelector('.step05-reference-card');
    await page.locator('input[data-step05-decision]').filter({has:page.locator('[value="通过"]')}).count().catch(()=>0);
    const passRadios=page.locator('input[data-step05-decision][value="通过"]');await passRadios.nth(0).focus();await page.keyboard.press('Space');await passRadios.nth(1).focus();await page.keyboard.press('Space');
    await page.locator('[data-step05-confirm-batch]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.step03-alert')?.textContent.includes('已更新'));await page.waitForFunction(()=>document.activeElement?.matches('[data-step05-confirm-batch]'));assert.equal(confirmAttempts,1);
    await passRadios.nth(0).focus();await page.keyboard.press('Space');await passRadios.nth(1).focus();await page.keyboard.press('Space');await page.locator('[data-step05-confirm-batch]').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.step05-reference-workspace')?.textContent.includes('视频参考图已确认'));assert.equal(confirmAttempts,2);
    await page.reload();await page.addStyleTag({path:path.join(__dirname,'product.css')});await page.addScriptTag({path:path.join(__dirname,'mvp-step03-r1.js')});await page.waitForFunction(()=>document.querySelector('.step03-stage')?.textContent.includes('Lucia'));await page.click('[data-step03-substep="confirmation"]');await page.waitForFunction(()=>document.querySelector('.step05-reference-workspace')?.textContent.includes('视频参考图已确认'));
    const viewports=[[1440,900],[1366,768],[390,844]],layouts=[];for(const [width,height] of viewports){await page.setViewportSize({width,height});await page.waitForTimeout(50);layouts.push(await page.evaluate(()=>({width:innerWidth,scrollWidth:document.scrollingElement.scrollWidth,cardWidth:document.querySelector('.step05-reference-card')?.getBoundingClientRect().width||0})));}
    for(const layout of layouts)assert.ok(layout.scrollWidth<=layout.width,JSON.stringify(layout));assert.ok(layouts[2].cardWidth<=390);
    await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement===document.body),true);assert.deepEqual(pageErrors,[]);assert.equal(confirmationPosts,2);assert.deepEqual(actionPosts,{reject:1,reroll:1,support:1});
    console.log(JSON.stringify({status:'PASS',real_browser_ui:true,viewports:['1440x900','1366x768','390x844'],no_horizontal_overflow:true,keyboard_only_reject_category_note_reroll_support_and_batch:true,conflict_recovery:true,refresh_recovery:true,batch_posts:confirmationPosts,action_posts:actionPosts,provider_calls:0}));
  }finally{await browser.close();}
})().catch(error=>{console.error(error.stack||error);process.exit(1);});
