'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = __dirname;
const html = fs.readFileSync(path.join(root, 'studio', 'index.html'), 'utf8');
const source = fs.readFileSync(path.join(root, 'studio', 'assets', 's1-chain-ui.js'), 'utf8');

assert.match(html, /assets\/s1-chain-ui\.js\?v=20260816-canvas-skill-nodes-r2/);
assert.match(source, /\/api\/canvas\/documents\//);
assert.match(source, /\/api\/projects\//);
assert.match(source, /step01Projection/);
assert.match(source, /evidence_ready/);
assert.match(source, /persistRuntimeProjection/);
assert.match(source, /canvas-rev-/);
assert.match(source, /scheduleStep01Poll/);
assert.match(source, /\/s1-chain/);
assert.match(source, /if-match/);
assert.match(source, /x-niannian-project-kind/);
assert.match(source, /rightsConfirmed/);
assert.match(source, /preflightStatus/);
assert.match(source, /sourceAssetIds/);
assert.match(source, /sourceParameters\.rightsConfirmed/);
assert.match(source, /sourceParameters\.preflightStatus/);
assert.match(source, /data-node=source/);
assert.match(source, /step01-analysis/);
assert.match(source, /开始 Step01 分析/);
assert.match(source, /data-node="source"/);
assert.match(source, /data-node="step01"/);
assert.match(source, /data-node="step02"/);
assert.match(source, /Skill 节点/);
assert.match(source, /输入节点/);
assert.match(source, /输出/);
assert.match(source, /Image2 关键帧生成/);
assert.match(source, /image2-storyboard-video/);
assert.match(source, /yunfei-gpt-image-2-1k/);
assert.match(source, /yunfei-gpt-image-2-hd/);
assert.match(source, /data-s2-resolution/);
assert.match(source, /data-s2-aspect/);
assert.match(source, /data-s2-assets/);
assert.match(source, /skill-node-layout/);
assert.match(source, /setPointerCapture/);
assert.match(source, /s1-selected/);
assert.match(source, /data-s1-delete/);
assert.match(source, /删除节点/);
assert.match(source, /event\.key !== 'Delete'/);
assert.match(source, /event\.key !== 'Backspace'/);
assert.match(source, /canvasDocument\.edges = previousEdges\.filter/);
assert.match(source, /contextmenu/);
assert.match(source, /host\.addEventListener\('contextmenu', showCanvasSkillMenu, true\)/);
assert.match(source, /document\.addEventListener\('pointerdown', dismissContextMenu, true\)/);
assert.match(source, /document\.addEventListener\('click', dismissContextMenu, true\)/);
assert.match(source, /event\.target\.closest\('#s1-chain-canvas'\)/);
assert.match(source, /data-s1-add-skill/);
assert.match(source, /data-s1-output-port/);
assert.match(source, /data-s1-input-port/);
assert.match(source, /connectPorts/);
assert.match(source, /s1-typed-edge/);
assert.match(source, /screenwriter/);
assert.match(source, /chaoge-assets-trial/);
assert.match(source, /shotlist-builder/);
assert.match(source, /hell-grind/);
assert.match(source, /executionMode:'orchestration'/);
assert.doesNotMatch(source, /\[data-node-id\^="nn-skill-"\]\{display:none/);
assert.match(source, /selectedImage2Ids/);
assert.match(source, /outputBindings/);
assert.match(source, /inputBindings/);
assert.match(source, /data-s1-port/);
assert.match(source, /source_asset：/);
assert.match(source, /evidence_manifest：/);
assert.match(source, /referenceAssetIds/);
assert.match(source, /s2-image2/);
assert.match(source, /建立 Image2 候选并执行 dry-run/);
assert.match(source, /H3 生视频/);
assert.match(source, /data-s3-prompt/);
assert.match(source, /data-s1-add-generation/);
assert.match(source, /\/s3-h3/);
assert.match(source, /建立 H3 候选并执行 dry-run/);
assert.match(source, /data-champion-input/);
assert.match(source, /data-champion-save/);
assert.match(source, /data-s1-drag-handle/);
assert.match(source, /uiVersion:'native-card-v2'/);
assert.match(source, /canvas\/skill-nodes/);
assert.match(source, /检查服务端输入合同/);
assert.match(source, /生成交付包/);
assert.match(source, /canvas\/skill-nodes\/.*\/compile/);
assert.match(source, /confirmProviderCall:true/);
assert.match(source, /点击兼容输入端完成连接/);
assert.match(source, /返回项目库/);
assert.match(source, /window\.location\.assign\('\/studio\/#\/studio'\)/);
assert.match(source, /isStudioLibraryRoute/);
assert.match(source, /removeProjectLibraryBack/);
assert.match(source, /removeWorkbenchBack/);
assert.match(source, /s1-library-workbench-back/);
assert.match(source, /返回主站工作台/);
assert.match(source, /window\.location\.assign\('\/#workbench'\)/);
assert.match(source, /s1Empty/);
assert.match(source, /生成画布工具栏/);
assert.match(source, /打开原片转绘链/);
assert.match(source, /data-s1-native-add/);
assert.match(source, /添加文本节点/);
assert.match(source, /nomi-appbar__breadcrumb-seg--lib/);
assert.match(source, /stopImmediatePropagation/);
assert.doesNotMatch(source, /window\.location\.assign\('\/#projects'\)/);
assert.match(source, /\[aria-label="AI 影像创作画布"\]/);
assert.match(source, /new MutationObserver/);
assert.match(source, /host\.appendChild\(panel\)/);
assert.doesNotMatch(source, /\|\| document\.body/);
assert.ok(source.includes('/canvas/jobs'));
assert.ok(source.includes('/dry-run'));
assert.match(source, /idempotency-key/);
assert.doesNotMatch(source, /confirmProviderSpend/);

console.log(JSON.stringify({ok:true,verified:['Studio loads the S1 control surface','S1 ports render persisted source and evidence bindings','revision protection is sent on creation','Step01 uses the source-only server route','the UI cannot submit a paid canvas provider job']}));
