'use strict';

const assert=require('assert');
const crypto=require('crypto');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const transport=require('./bridge/niannian_redraw_step01_mac_app_phase_transport');

function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
async function writeJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});await fsp.writeFile(filePath,JSON.stringify(value,null,2)+'\n','utf8');}
async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}
async function makeExport(root,suffix='A'){
  const packageRoot=path.join(root,'export-'+suffix);await fsp.mkdir(path.join(packageRoot,'input'),{recursive:true});const sourceSha=sha256('source-'+suffix);const rightsEvent='rights-'+sha256('rights-'+suffix).slice(0,24);const rightsSha=sha256('rights-bytes-'+suffix);const phase=transport.phaseKey({remote_project_id:'NN-STEP01-TRANSPORT-'+suffix+'-0001',local_job_id:'web_nn-step01-transport-'+suffix.toLowerCase()+'-0001',source_sha256:sourceSha,rights_authority_event_id:rightsEvent,rights_authority_sha256:rightsSha,authorization_event_id:'step01-'+sha256('auth-'+suffix).slice(0,24),settings_version:2,dispatch_id:'STEP01EMP-TRANSPORT-'+suffix+'-0001'});
  const dispatch={schema_version:transport.DISPATCH_SCHEMA,execution_mode:'step01_hq_full_authorized_analysis_only',test_only:false,real_delivery:false,phase_key:{...phase},dispatch_id:phase.dispatch_id,remote_project_id:phase.remote_project_id,local_job_id:phase.local_job_id,source_sha256:phase.source_sha256,source_bytes:8,rights_authority:{event_id:rightsEvent,sha256:rightsSha,bytes:10,scope:'source_video_redraw_full_chain_under_explicit_provider_and_delivery_gates',status:'confirmed',revoked:false},authorization_event_id:phase.authorization_event_id,settings_version:phase.settings_version,idempotency_key:sha256(phase.canonical),employee:{employee:'01',title:'念念 AI · Mac 员工 01',thread_id:'019f6201-c013-7cf3-b155-61d2789085f4',project_root:'/Users/lsb/AI-Brain/niannian-ai-canonical-local',workspace:'/Users/lsb/.local/share/niannian-ai/employee-workspaces/01/'+phase.dispatch_id},analysis_service_network_authority:{status:'authorized',media_provider_authority_granted:false},media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,package_send_requested:false,registry_promotion_requested:false,deployment_requested:false,local_image_editing_requested:false};await writeJson(path.join(packageRoot,'step01_employee_dispatch.json'),dispatch);await writeJson(path.join(packageRoot,'input','task.json'),{source_sha256:sourceSha});
  const files=[];for(const relative of ['step01_employee_dispatch.json','input/task.json'])files.push({relative_path:relative,...await transport.fileEvidence(path.join(packageRoot,...relative.split('/')))});const manifest={schema_version:transport.EXPORT_MANIFEST_SCHEMA,phase_key:{...phase},files,generated_at:new Date().toISOString()};await writeJson(path.join(packageRoot,'step01_phase_manifest.json'),manifest);return {dispatch,manifestSha:(await transport.fileEvidence(path.join(packageRoot,'step01_phase_manifest.json'))).sha256,packageRoot,phase};
}
async function completeWorkspace(workspace,current,verified=true){
  const artifactPath=path.join(workspace,'evidence','validation.json');await writeJson(artifactPath,{status:verified?'passed':'blocked'});const artifact={relative_path:'evidence/validation.json',...await transport.fileEvidence(artifactPath)};const completion={method:'turn/completed',turn_id:'turn-'+current.phase.key_id.slice(-12),status:'completed',error:null};const rights={...current.dispatch.rights_authority};const receipt={schema_version:'niannian_redraw_step01_mac_employee_receipt_v2',dispatch_id:current.phase.dispatch_id,phase_key:current.phase.key_id,source_sha256:current.phase.source_sha256,rights_authority:rights,authorization_event_id:current.phase.authorization_event_id,settings_version:current.phase.settings_version,status:verified?'step01_verified':'blocked_contract',step01_verified:verified,analysis_service_network:{requested:true,used:true,media_provider_authority_granted:false},completion_event:completion,test_only:false,real_delivery:false,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,package_send_requested:false,registry_promotion_requested:false,deployment_requested:false,local_image_editing_requested:false};const control={schema_version:'niannian_redraw_step01_mac_app_control_receipt_v2',dispatch_id:current.phase.dispatch_id,phase_key:current.phase.key_id,rights_authority:rights,employee:{thread_id:current.dispatch.employee.thread_id},completion_event:completion,step01_verified:verified,analysis_service_network:{requested:true,used:true,media_provider_authority_granted:false},test_only:false,real_delivery:false,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,package_send_requested:false,registry_promotion_requested:false,deployment_requested:false,local_image_editing_requested:false};const evidenceManifest={schema_version:'step01_evidence_manifest_v1',status:verified?'verified':'blocked_contract',downstream_consumable:verified,artifacts:[artifact]};
  await Promise.all([writeJson(path.join(workspace,'route_decision.json'),{schema_version:'niannian_step01_mac_skill_route_decision_v1',decision_authority:'mac_codex_desktop_app_turn',selected_skill:verified?'mx-shortdrama-01-frame-extract':null,test_only:false}),writeJson(path.join(workspace,'skill_execution_receipt.json'),{schema_version:'niannian_step01_skill_execution_receipt_v1',status:verified?'route_selected':'blocked_contract',test_only:false}),writeJson(path.join(workspace,'evidence','analysis_service_reconciliation.json'),{schema_version:'niannian_step01_analysis_service_reconciliation_v1',status:verified?'completed_reconciled':'blocked_reconcile_required',test_only:false}),writeJson(path.join(workspace,'step01_employee_worker_receipt.json'),receipt),writeJson(path.join(workspace,'step01_employee_control_receipt.json'),control),fsp.writeFile(path.join(workspace,'step01_dispatch_attempt_events.jsonl'),JSON.stringify({type:'dispatch_claimed'})+'\n','utf8'),writeJson(path.join(workspace,'step01_evidence_manifest.json'),evidenceManifest),writeJson(path.join(workspace,'checkpoint.json'),{status:verified?'step01_verified':'blocked_contract'}),writeJson(path.join(workspace,'gate_dashboard.json'),{overall_status:verified?'step01_verified':'blocked_contract'}),writeJson(path.join(workspace,'artifact_ledger.json'),{artifacts:[]}),writeJson(path.join(workspace,'result_manifest.json'),{step01_verified:verified}),fsp.writeFile(path.join(workspace,'worker_report.md'),'transport fixture only\n','utf8')]);
}
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'niannian-step01-transport-'));try{
  const current=await makeExport(root,'A');const workspace=path.join(root,'workspace-a');const imported=await transport.importDispatchToMac({packageRoot:current.packageRoot,expectedManifestSha256:current.manifestSha,expectedPhase:current.phase,workspacePath:workspace});assert.equal(imported.status,'promoted');await completeWorkspace(workspace,current,true);const finalized=await transport.finalizeMacReturn({workspacePath:workspace});assert.match(finalized.manifestSha256,/^[a-f0-9]{64}$/);assert.equal(finalized.manifest.step01_verified,true);assert(finalized.manifest.files.some(item=>item.relative_path==='step01_employee_control_receipt.json'));assert(finalized.manifest.files.some(item=>item.relative_path==='evidence/validation.json'));
  const windowsReturn=path.join(root,'windows-return-a');const returned=await transport.importMacReturnToWindows({packageRoot:workspace,expectedManifestSha256:finalized.manifestSha256,expectedPhase:current.phase,windowsReturnRoot:windowsReturn});assert.equal(returned.status,'promoted');const replay=await transport.importMacReturnToWindows({packageRoot:workspace,expectedManifestSha256:finalized.manifestSha256,expectedPhase:current.phase,windowsReturnRoot:windowsReturn});assert.equal(replay.status,'replayed');
  const tamper=await fsp.mkdtemp(path.join(root,'tamper-'));await fsp.cp(workspace,tamper,{recursive:true});await fsp.appendFile(path.join(tamper,'evidence','validation.json'),'x');await assert.rejects(()=>transport.importMacReturnToWindows({packageRoot:tamper,expectedManifestSha256:finalized.manifestSha256,expectedPhase:current.phase,windowsReturnRoot:path.join(root,'bad-return')}),/manifest_file_mismatch/);
  const blocked=await makeExport(root,'B');const blockedWorkspace=path.join(root,'workspace-b');await transport.importDispatchToMac({packageRoot:blocked.packageRoot,expectedManifestSha256:blocked.manifestSha,workspacePath:blockedWorkspace});await completeWorkspace(blockedWorkspace,blocked,false);const blockedFinal=await transport.finalizeMacReturn({workspacePath:blockedWorkspace});assert.equal(blockedFinal.manifest.blocked,true);assert.equal(blockedFinal.manifest.step01_verified,false);
  await assert.rejects(()=>transport.verifyManifest(current.packageRoot,'step01_phase_manifest.json',transport.EXPORT_MANIFEST_SCHEMA,current.manifestSha,{...current.phase,source_sha256:'0'.repeat(64)}),/phase_key_mismatch/);
  assert.equal('acquireLease' in transport,false);assert.equal('releaseLease' in transport,false);
  process.stdout.write(JSON.stringify({ok:true,verified:['exact Step01 phase manifest import','source/auth/settings/dispatch phase binding','atomic replay-safe promotion','dynamic evidence bundle return manifest','worker/control receipts included after completion','blocked return remains non-verified','tamper and phase drift rejected','transport exposes no TTL lease admission API','analysis service identity separated from media provider']})+'\n');
}finally{await fsp.rm(root,{recursive:true,force:true});}}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
