const assert = require('assert/strict');
const fs = require('fs');
const runtime=fs.readFileSync(require.resolve('./bridge/niannian_step03_runtime'),'utf8');
const worker=fs.readFileSync(require.resolve('./bridge/niannian_step03_worker'),'utf8');
const workerEntry=fs.readFileSync(require.resolve('./scripts/run_step03_worker'),'utf8');
const planner=fs.readFileSync(require.resolve('./bridge/niannian_step03_planner'),'utf8');
const ui=fs.readFileSync(require.resolve('./mvp-step03-r1.js'),'utf8');
const server=fs.readFileSync(require.resolve('./server.js'),'utf8');
const index=fs.readFileSync(require.resolve('./index.html'),'utf8');
const serviceWorker=fs.readFileSync(require.resolve('./sw.js'),'utf8');
const legacyStep02Ui=fs.readFileSync(require.resolve('./mvp-step02-r13.js'),'utf8');
const css=fs.readFileSync(require.resolve('./product.css'),'utf8');
const ledgerUi=fs.readFileSync(require.resolve('./mvp-step01-ledger-r1.js'),'utf8');
for(const value of ["['styles','风格选择']","['characters','人物定稿']","['assets','场景与道具']","['firstframes','镜头首帧']","['confirmation','视频参考确认']",'data-step03-style-choice','data-step03-style-confirm','data-step03-asset-confirm','data-step03-revise-group','data-step03-reload-image','market'])assert.ok(ui.includes(value),value);
for(const value of ['STYLE-REALISTIC-SHORTDRAMA','STYLE-CINEMATIC-WARM','STYLE-DOCUMENTARY-NATURAL','STEP03_STYLE_CONFIRMED','STEP03_ASSET_DECISION_RECORDED'])assert.ok((runtime+server).includes(value),value);
assert.match(runtime,/max_first_round_candidates/);assert.match(ui,/人物 6 · 场景 2 · 道具 1 · 首帧 2/);assert.match(css,/step03-style-workspace/);assert.match(css,/step03-style-grid/);
for(const value of ['runninghub','krill','local_pixel_edit','planning_result','downstream_consumable'])assert.ok((runtime+worker+planner).toLowerCase().includes(value.toLowerCase()),value);
assert.match(css,/step03-group-revision/);assert.match(css,/step03-image-empty\.is-error/);assert.doesNotMatch(ui,/PIL|OpenCV|ImageMagick|ffmpeg/i);
assert.match(server,/private, max-age=31536000, immutable/);assert.match(server,/request\.headers\['if-none-match'\]===etag/);assert.match(server,/'Vary':'Cookie'/);
assert.match(ui,/prefetchCharacterArtifacts/);assert.match(ui,/navigator\.connection\?\.saveData/);assert.match(ui,/prefetchedArtifacts:new Set\(\)/);
assert.match(ui,/20260728-redraw-review-authority-r1/);
for(const source of [index,serviceWorker])assert.match(source,/20260727-media-direct-r1/);
assert.match(server,/step03WebPreview/);assert.match(server,/image\/webp/);assert.match(server,/X-Source-SHA256/);
assert.match(ui,/view=preview&width=/);assert.match(ui,/original:true/);assert.match(ui,/step01_source_ledger_sha256===ledgerSha/);
assert.match(ui,/data-step03-resolution/);assert.match(ui,/1K · 默认/);assert.match(ui,/\['1k','2k','4k'\]/);assert.match(ui,/resolution:store\.generationResolution/);
for(const handler of ['queueCharacterCandidates','queueAssets','rerollAsset','queueFirstFrames'])assert.match(server,new RegExp(handler+'\\(\\{[^}]*resolution:body\\.resolution'));
assert.match(ui,/loading=.*escape\(loading\).*fetchpriority=.*escape\(fetchPriority\).*decoding="async"/);
assert.match(ui,/mediaView\(task,selected\.description,\{emptyText:state\.label,fetchPriority:'high'\}\)/);
assert.match(ui,/mediaView\(task,asset\.description,\{emptyText:state\.label,loading:'lazy',fetchPriority:'low'\}\)/);
assert.match(ledgerUi,/step01\/shot-ledger/);assert.match(ledgerUi,/step01-evidence/);assert.match(ledgerUi,/If-Match/);assert.match(ledgerUi,/data-ledger-edit/);assert.match(css,/ledger-stage/);
assert.match(ui,/function normalizeReadyAssets\(\)/);assert.match(ui,/asset\.status='awaiting_generation'/);
assert.match(ui,/row\.status==='awaiting_generation'/);assert.doesNotMatch(ui,/\['awaiting_generation','rejected','failed'\]/);
assert.match(legacyStep02Ui,/\['03','04'\]\.includes\(route\.stageId\)/);
assert.match(legacyStep02Ui,/isFuture\?' disabled aria-disabled="true"'/);
assert.match(legacyStep02Ui,/if\(Number\(redrawStudioStage\.dataset\.redrawStudioStage\)>Number\(currentStage\)\)return/);
assert.doesNotMatch(ui,/<dd>RunningHub<\/dd>/);
assert.match(ui,/<dt>生成方式<\/dt><dd>受控生成服务<\/dd>/);
assert.match(ui,/stage\\\/\(03\|04\)\\\/market/);
assert.match(ui,/if\(value\.legacyStage\)history\.replaceState/);
assert.match(worker,/LOCALIZATION_PROVIDER_PREFLIGHT_REQUIRED/);assert.match(workerEntry,/requireProviderTask/);assert.match(workerEntry,/providerPreflight/);
process.stdout.write(JSON.stringify({ok:true,substeps:5,style_authority:true,asset_user_confirmation:true,group_revision_controls:true,image_failure_retry:true,private_immutable_artifact_cache:true,sequential_character_prefetch:true,default_image_resolution:'1k',selectable_image_resolutions:['1k','2k','4k'],lazy_asset_thumbnails:true,no_local_pixel_edit_route:true,step03_route_single_writer:true})+'\n');
