'use strict';

const assert=require('assert');
const crypto=require('crypto');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const transport=require('./bridge/niannian_redraw_step01_mac_app_phase_transport');
const {EXPECTED_ROUTER_SKILL,EXPECTED_SCRIPT_ENTRYPOINTS,EXPECTED_STEP_SKILL,reconcileStep01Return,validateSkillAuthority}=require('./bridge/niannian_redraw_step01_return_reducer');
const {appendEvidenceEvent}=require('./bridge/niannian_step01_evidence_events');

function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
async function writeJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});await fsp.writeFile(filePath,JSON.stringify(value,null,2)+'\n','utf8');}
async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}

async function fixture(root,suffix='A',verified=true){
  const jobRoot=path.join(root,'jobs','web_nn-reducer-'+suffix.toLowerCase()+'-0001');
  const returnRoot=path.join(root,'returns',suffix);await fsp.mkdir(returnRoot,{recursive:true});await fsp.mkdir(jobRoot,{recursive:true});
  const sourceSha=sha256('source-'+suffix);const rights={schema_version:'niannian_source_rights_authority_v1',event_id:'rights-'+sha256('rights-'+suffix).slice(0,24),status:'confirmed',confirmed_by_user_id:'user-fixture',source_sha256:sourceSha,source_bytes:10,scope:'source_video_redraw_full_chain_under_explicit_provider_and_delivery_gates',declaration:'user_confirmed_rights_to_use_and_adapt_uploaded_source',confirmed_at:new Date().toISOString(),revoked:false};
  await writeJson(path.join(jobRoot,'rights_authority.json'),rights);const rightsEvidence=await transport.fileEvidence(path.join(jobRoot,'rights_authority.json'));
  const phase=transport.phaseKey({remote_project_id:'NN-REDUCER-'+suffix+'-0001',local_job_id:'web_nn-reducer-'+suffix.toLowerCase()+'-0001',source_sha256:sourceSha,rights_authority_event_id:rights.event_id,rights_authority_sha256:rightsEvidence.sha256,authorization_event_id:'step01-'+sha256('auth-'+suffix).slice(0,24),settings_version:2,dispatch_id:'STEP01EMP-REDUCER-'+suffix+'-0001'});
  const analysisRunId='analysis-1-reducer-'+suffix;const phaseManifestSha=sha256('phase-manifest-'+suffix);
  await Promise.all([
    writeJson(path.join(jobRoot,'task.json'),{remote_job_id:phase.remote_project_id,job_id:phase.local_job_id,source_video:{sha256:sourceSha,bytes:10,media_contract:{duration_seconds:12}},analysis_run:{id:analysisRunId,source_revision:1,source_sha256:sourceSha},rights_authority:{event_id:rights.event_id,sha256:rightsEvidence.sha256}}),
    writeJson(path.join(jobRoot,'step01_authorization.json'),{event_id:phase.authorization_event_id,settings_version:2,rights_authority:{event_id:rights.event_id,sha256:rightsEvidence.sha256}}),
    writeJson(path.join(jobRoot,'route_decision.json'),{source_sha256:sourceSha,rights_authority_event_id:rights.event_id,rights_authority_sha256:rightsEvidence.sha256,authorization_event_id:phase.authorization_event_id})
  ]);
  const eventBase={project_id:phase.remote_project_id,analysis_run_id:analysisRunId,source_revision:1,source_sha256:sourceSha,dispatch_id:phase.dispatch_id,phase_key:phase.key_id};const eventPath=path.join(jobRoot,'evidence_events.jsonl');await appendEvidenceEvent(eventPath,{...eventBase,type:'analysis_run_created',status:'queued',evidence_sha256:sha256(analysisRunId)});await appendEvidenceEvent(eventPath,{...eventBase,type:'dispatch_claimed',status:'claimed',evidence_sha256:phaseManifestSha,phase_manifest_sha256:phaseManifestSha,employee_thread_id:'019f6201-c013-7cf3-b155-61d2789085f4'});await appendEvidenceEvent(eventPath,{...eventBase,type:'codex_turn_started',status:'authorized_before_turn_start',evidence_sha256:phaseManifestSha,phase_manifest_sha256:phaseManifestSha,employee_thread_id:'019f6201-c013-7cf3-b155-61d2789085f4'});
  const completion={method:'turn/completed',turn_id:'turn-'+suffix,status:'completed',error:null};
  const rightsPointer={event_id:rights.event_id,sha256:rightsEvidence.sha256,bytes:rightsEvidence.bytes,scope:rights.scope,status:'confirmed',revoked:false};
  const common={dispatch_id:phase.dispatch_id,phase_key:phase.key_id,source_sha256:sourceSha,rights_authority:rightsPointer,authorization_event_id:phase.authorization_event_id,settings_version:2,test_only:false,real_delivery:false,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,package_send_requested:false,registry_promotion_requested:false,deployment_requested:false,local_image_editing_requested:false};
  const analysisServiceIdempotency=['mimo_asr|chinese_transcript','paddle_ocr|subtitle_text_qa'].map(value=>{const [service_id,purpose]=value.split('|');return {service_id,purpose,key:sha256([analysisRunId,sourceSha,service_id,purpose].join('|'))};});
  const dispatch={...common,schema_version:transport.DISPATCH_SCHEMA,execution_mode:'step01_hq_full_authorized_analysis_only',phase_key:{...phase},remote_project_id:phase.remote_project_id,local_job_id:phase.local_job_id,analysis_run_id:analysisRunId,source_revision:1,source_bytes:10,employee:{thread_id:'019f6201-c013-7cf3-b155-61d2789085f4'},analysis_service_idempotency:analysisServiceIdempotency,analysis_service_network_authority:{status:'authorized',media_provider_authority_granted:false}};
  const skillBundle={bundle_id:'niannian-mac-production-skills-v2',artifact_set_id:'macskillset-ceb5015e5d4b129e5e2eb5a7a89af468eed547d43df2c50780dde5f26aba3549',manifest_sha256:'59035cd1b97540ec85c926d4e957c3766b8c106012af725b0abad2f8d1548b09'};const routerSkill={...EXPECTED_ROUTER_SKILL};const stepSkill={...EXPECTED_STEP_SKILL};const route={schema_version:'niannian_step01_mac_skill_route_decision_v1',decision_authority:'mac_codex_desktop_app_turn',project_id:phase.remote_project_id,analysis_run_id:analysisRunId,source_revision:1,source_sha256:sourceSha,required_router:'mx-shortdrama-00-router',selected_skill:verified?'mx-shortdrama-01-frame-extract':null,skill_bundle:skillBundle,router_skill:routerSkill,step_skill:stepSkill,test_only:false};
  await writeJson(path.join(returnRoot,'route_decision.json'),route);const routeEvidence=await transport.fileEvidence(path.join(returnRoot,'route_decision.json'));
  const skillReceipt={schema_version:'niannian_step01_skill_execution_receipt_v1',status:verified?'route_selected':'blocked_contract',analysis_run_id:analysisRunId,source_sha256:sourceSha,dispatch_id:phase.dispatch_id,phase_key:phase.key_id,route_decision:{relative_path:'route_decision.json',...routeEvidence},skill_bundle:skillBundle,router_skill:routerSkill,step_skill:stepSkill,script_entrypoints:structuredClone(EXPECTED_SCRIPT_ENTRYPOINTS),test_only:false};
  await writeJson(path.join(returnRoot,'skill_execution_receipt.json'),skillReceipt);const skillEvidence=await transport.fileEvidence(path.join(returnRoot,'skill_execution_receipt.json'));
  const reconciliation={schema_version:'niannian_step01_analysis_service_reconciliation_v1',status:verified?'completed_reconciled':'blocked_reconcile_required',analysis_run_id:analysisRunId,source_sha256:sourceSha,registry_id:sha256([analysisRunId,sourceSha].join('|')),claim:{dispatch_id:phase.dispatch_id,phase_key:phase.key_id},services:analysisServiceIdempotency.map(item=>({...item,prior_task_status:'none',action:verified?'submitted_once':'do_not_resubmit_recover_prior_receipt',status:verified?'completed':'reconcile_required',provider_task_ids:item.service_id==='paddle_ocr'?['paddle-job-'+suffix]:[]})),media_provider_authority_granted:false,test_only:false};await writeJson(path.join(returnRoot,'evidence','analysis_service_reconciliation.json'),reconciliation);const reconciliationEvidence=await transport.fileEvidence(path.join(returnRoot,'evidence','analysis_service_reconciliation.json'));
  const receipt={...common,status:verified?'step01_verified':'blocked_contract',production_status:verified?'step01_verified':'blocked_contract',step01_verified:verified,route_decision:{relative_path:'route_decision.json',...routeEvidence},skill_execution:{relative_path:'skill_execution_receipt.json',...skillEvidence},analysis_service_reconciliation:{relative_path:'evidence/analysis_service_reconciliation.json',...reconciliationEvidence},analysis_service_network:{requested:true,used:true,media_provider_authority_granted:false},completion_event:completion};
  const control={...common,schema_version:'niannian_redraw_step01_mac_app_control_receipt_v2',employee:dispatch.employee,attempt:{schema_version:'niannian_step01_mac_app_attempt_v1',attempt_id:'step01attempt-'+sha256('attempt-'+suffix),status:'completed',dispatch_id:phase.dispatch_id,phase_key:phase.key_id,phase_manifest_sha256:phaseManifestSha},step01_verified:verified,analysis_service_network:{requested:true,used:true,media_provider_authority_granted:false},completion_event:completion};
  const ptr=async relative=>({relative_path:relative.replace(/\\/g,'/'),...await transport.fileEvidence(path.join(returnRoot,relative))});
  if(verified){
    await writeJson(path.join(returnRoot,'evidence','ffprobe.json'),{duration_seconds:12,width:1080,height:1920,fps:25});
    await writeJson(path.join(returnRoot,'evidence','shots.json'),{status:'accepted',detector:'TransNetV2',shots:[{shot_id:'1',start_sec:0,end_sec:6},{shot_id:'2',start_sec:6,end_sec:12}]});
    const frameRows=[];for(const shot of ['1','2'])for(const point of ['start','mid','end']){const relative=path.join('evidence','frames',shot+'-'+point+'.png');await fsp.mkdir(path.dirname(path.join(returnRoot,relative)),{recursive:true});await fsp.writeFile(path.join(returnRoot,relative),Buffer.from(shot+'-'+point));frameRows.push({shot_id:shot,point,relative_path:relative.replace(/\\/g,'/'),...await transport.fileEvidence(path.join(returnRoot,relative))});}
    await writeJson(path.join(returnRoot,'evidence','supplement.json'),{rows:frameRows});
    await writeJson(path.join(returnRoot,'evidence','native.json'),{frames:frameRows});
    await writeJson(path.join(returnRoot,'evidence','chunks.json'),[{chunk_index:1,start_sec:0,end_sec:12}]);
    await fsp.writeFile(path.join(returnRoot,'evidence','audio.wav'),Buffer.from('wav'));
    await fsp.writeFile(path.join(returnRoot,'evidence','audio.csv'),'start_sec,end_sec,speaker,text\n0,2,A,hello\n7,8,B,reply\n','utf8');
    await writeJson(path.join(returnRoot,'evidence','mimo.json'),{status:'passed',backend:'mimo'});
    await writeJson(path.join(returnRoot,'evidence','aligner.json'),{status:'passed',backend:'Qwen3-ForcedAligner-0.6B'});
    await fsp.writeFile(path.join(returnRoot,'evidence','ocr.csv'),'start_sec,end_sec,text\n1,2,DOOR\n8,9,PHONE\n','utf8');
    await writeJson(path.join(returnRoot,'evidence','ocr.json'),{status:'passed',backend:'PaddleOCR'});
    await writeJson(path.join(returnRoot,'evidence','validation.json'),{status:'passed',hard_gates:{artifact_hashes_pass:true}});
  }
  const nativeFrames=verified?['1','2'].flatMap(shot=>['start','mid','end'].map(point=>'evidence/frames/'+shot+'-'+point+'.png')):[];
  const evidenceManifest=verified?{schema_version:'step01_evidence_manifest_v1',status:'verified',profile:'hq_full',downstream_consumable:true,test_only:false,source_sha256:sourceSha,source_bytes:10,source:{ffprobe:await ptr('evidence/ffprobe.json')},minute_chunks:{index:await ptr('evidence/chunks.json')},native_frames:{manifest:await ptr('evidence/native.json'),frames:await Promise.all(nativeFrames.map(ptr))},transnet:{accepted_shots:await ptr('evidence/shots.json'),shot_supplement:await ptr('evidence/supplement.json')},audio:{wav:await ptr('evidence/audio.wav'),event_ledger:await ptr('evidence/audio.csv'),mimo_transcript_receipt:await ptr('evidence/mimo.json'),forced_aligner_receipt:await ptr('evidence/aligner.json')},ocr:{ledger:await ptr('evidence/ocr.csv'),receipt:await ptr('evidence/ocr.json')},validation:{receipt:await ptr('evidence/validation.json')},artifacts:[]}:{schema_version:'step01_evidence_manifest_v1',status:'blocked_contract',downstream_consumable:false,artifacts:[]};
  const roles=['step01_evidence_manifest','step01_validation_report','step01_analysis_service_reconciliation','step01_mimo_asr_evidence','step01_forced_aligner_evidence','step01_transnet_shot_evidence','step01_paddle_ocr_evidence','step01_native_frame_evidence_0001'];
  const ledger={schema_version:'artifact_ledger_v1',artifacts:verified?roles.map(artifact_id=>({artifact_id,status:'verified'})):[]};
  const files={'step01_employee_dispatch.json':dispatch,'route_decision.json':route,'skill_execution_receipt.json':skillReceipt,'evidence/analysis_service_reconciliation.json':reconciliation,'step01_employee_worker_receipt.json':receipt,'step01_employee_control_receipt.json':control,'step01_dispatch_attempt_events.jsonl':JSON.stringify({type:'dispatch_claimed',attempt_id:control.attempt.attempt_id})+'\n','step01_evidence_manifest.json':evidenceManifest,'checkpoint.json':{status:verified?'step01_verified':'blocked_contract'},'gate_dashboard.json':{overall_status:verified?'step01_verified':'blocked_contract'},'artifact_ledger.json':ledger,'result_manifest.json':{step01_verified:verified},'worker_report.md':'fixture\n'};
  for(const [name,value] of Object.entries(files)){if(name.endsWith('.json'))await writeJson(path.join(returnRoot,name),value);else await fsp.writeFile(path.join(returnRoot,name),value,'utf8');}
  const rows=[];for(const name of Object.keys(files))rows.push({relative_path:name,...await transport.fileEvidence(path.join(returnRoot,name))});
  if(verified)for(const relative of ['evidence/ffprobe.json','evidence/shots.json','evidence/supplement.json','evidence/native.json','evidence/chunks.json','evidence/audio.wav','evidence/audio.csv','evidence/mimo.json','evidence/aligner.json','evidence/ocr.csv','evidence/ocr.json','evidence/validation.json','evidence/frames/1-start.png','evidence/frames/1-mid.png','evidence/frames/1-end.png','evidence/frames/2-start.png','evidence/frames/2-mid.png','evidence/frames/2-end.png'])rows.push({relative_path:relative,...await transport.fileEvidence(path.join(returnRoot,relative))});
  await writeJson(path.join(returnRoot,'step01_return_transport_manifest.json'),{schema_version:transport.RETURN_MANIFEST_SCHEMA,phase_key:{...phase},files:rows});
  return {jobRoot,returnRoot,phase,manifestSha:(await transport.fileEvidence(path.join(returnRoot,'step01_return_transport_manifest.json'))).sha256};
}

async function main(){
  const root=await fsp.mkdtemp(path.join(os.tmpdir(),'niannian-step01-reducer-'));
  try{
    const driftedScripts=structuredClone(EXPECTED_SCRIPT_ENTRYPOINTS);driftedScripts.smart_selective_ocr.bytes+=1;assert.throws(()=>validateSkillAuthority({router_skill:EXPECTED_ROUTER_SKILL,step_skill:EXPECTED_STEP_SKILL},{router_skill:EXPECTED_ROUTER_SKILL,step_skill:EXPECTED_STEP_SKILL,script_entrypoints:driftedScripts}),/script_entrypoint_authority_invalid/);
    const pass=await fixture(root,'A',true);const result=await reconcileStep01Return({jobRoot:pass.jobRoot,returnRoot:pass.returnRoot,expectedManifestSha256:pass.manifestSha,expectedPhase:pass.phase});assert.equal(result.status,'step01_evidence_ready_reconciled');assert.equal((await readJson(path.join(pass.jobRoot,'status.json'))).status,'evidence_ready');assert.equal((await readJson(path.join(pass.jobRoot,'result_manifest.json'))).real_delivery,false);const evidenceIndex=await readJson(path.join(pass.jobRoot,'analysis_runs','analysis-1-reducer-A','evidence','step01_customer_evidence_index.json'));assert.equal(evidenceIndex.status,'evidence_ready');const events=await fsp.readFile(path.join(pass.jobRoot,'evidence_events.jsonl'),'utf8');assert(events.includes('skill_route_selected'));assert(events.includes('analysis_service_task_reconciled'));assert(events.includes('artifact_paths_verified'));assert(events.includes('step01_evidence_accepted'));const replay=await reconcileStep01Return({jobRoot:pass.jobRoot,returnRoot:pass.returnRoot,expectedManifestSha256:pass.manifestSha,expectedPhase:pass.phase});assert.equal(replay.status,'step01_evidence_ready_reconciled');
    const blocked=await fixture(root,'B',false);assert.equal((await reconcileStep01Return({jobRoot:blocked.jobRoot,returnRoot:blocked.returnRoot})).status,'step01_blocked_reconciled');assert.equal((await readJson(path.join(blocked.jobRoot,'step01_evidence_manifest.json'))).downstream_consumable,false);
    const stale=await fixture(root,'C',true);const task=await readJson(path.join(stale.jobRoot,'task.json'));task.source_video.sha256='0'.repeat(64);await writeJson(path.join(stale.jobRoot,'task.json'),task);await assert.rejects(()=>reconcileStep01Return({jobRoot:stale.jobRoot,returnRoot:stale.returnRoot}),/current_authority_binding_invalid/);
    const tamperedRights=await fixture(root,'D',true);const rights=await readJson(path.join(tamperedRights.jobRoot,'rights_authority.json'));rights.revoked=true;await writeJson(path.join(tamperedRights.jobRoot,'rights_authority.json'),rights);await assert.rejects(()=>reconcileStep01Return({jobRoot:tamperedRights.jobRoot,returnRoot:tamperedRights.returnRoot}),/current_authority_binding_invalid/);
    process.stdout.write(JSON.stringify({ok:true,verified:['return manifest exact SHA','source/rights/auth/settings/phase current-authority revalidation','turn/completed receipt binding','verified artifact role gate','atomic job projection','worker receipt and artifact path evidence events','idempotent archive replay','typed blocked return remains non-consumable','stale source or revoked rights authority rejected','media provider/spend/delivery remain false']})+'\n');
  }finally{await fsp.rm(root,{recursive:true,force:true});}
}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
