'use strict';
const assert=require('assert'),crypto=require('crypto'),fsp=require('fs').promises,os=require('os'),path=require('path'),{build,REQUIRED}=require('./bridge/niannian_step01_hq_full_gate_v2');
const {syncHqCapabilityStatus}=require('./bridge/mac-employee-training/build_step01_hq_full_gate_v2');
const h=value=>crypto.createHash('sha256').update(value).digest('hex');
async function w(file,value){await fsp.mkdir(path.dirname(file),{recursive:true});await fsp.writeFile(file,JSON.stringify(value,null,2)+'\n');}
async function e(file){const bytes=await fsp.readFile(file);return{exact_path:path.resolve(file),sha256:h(bytes),bytes:bytes.length};}
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'hqv2-'));try{
  const now=Date.parse('2026-07-15T03:30:00Z'),entry=path.join(root,'entry.py');await fsp.writeFile(entry,'entry');
  const candidate=path.join(root,'candidate.json'),install=path.join(root,'install.json'),parity=path.join(root,'parity.json'),adoption=path.join(root,'adoption.json'),status=path.join(root,'status.json'),probe=path.join(root,'probe.json'),composite=path.join(root,'composite.json'),receipt=path.join(root,'receipt.json');
  await w(candidate,{status:'blocked_install_pending',execution_authority_granted:false,bundle_v2:{manifest:{sha256:'a'.repeat(64)}},entrypoint:{exact_path:entry,sha256:h(await fsp.readFile(entry))}});await w(install,{status:'installed_verified',manifest_sha256:'a'.repeat(64)});await w(parity,{status:'exact_parity_verified',manifest_sha256:'a'.repeat(64)});
  const cb=(await e(candidate)).sha256,ib=(await e(install)).sha256,pb=(await e(parity)).sha256,entrySha=h(await fsp.readFile(entry));await w(adoption,{status:'verified',completed:5,bindings:{toolchain_candidate_sha256:'0'.repeat(64),bundle_manifest_sha256:'a'.repeat(64),install_receipt_sha256:ib,parity_receipt_sha256:pb,entrypoint_sha256:entrySha}});const ab=(await e(adoption)).sha256;
  const bindings={toolchain_candidate_sha256:cb,bundle_manifest_sha256:'a'.repeat(64),install_receipt_sha256:ib,parity_receipt_sha256:pb,adoption_manifest_sha256:ab,entrypoint_sha256:entrySha},checkedAt=new Date(now-1000).toISOString(),caps={};for(const key of REQUIRED)caps[key]={status:'ready',checked_at:checkedAt,...(key.startsWith('credential:')?{expires_at:new Date(now+3600000).toISOString()}:{}),evidence:{method:'presence_and_synthetic_health',summary:'No secret material recorded; fresh synthetic health passed.'}};
  await w(status,{schema_version:'niannian_runtime_capability_status_v1',capabilities:caps});await w(probe,{schema_version:'niannian_step01_analysis_service_composite_probe_receipt_v1',status:'passed',test_media_kind:'synthetic_non_project_media',bindings,analysis_service_spend_authorized:true,analysis_service_network_requested:true,analysis_service_network_used:true,analysis_service_requests_created:2,analysis_service_jobs_created:1,mimo_asr:{status:'passed',provider_request_created:true,provider_job_created:false},paddle_ocr:{status:'passed',provider_job_created:true},secret_output:false,secret_persisted:false,secret_in_argv:false,provider_upload_requested:false,provider_submit_requested:false,spend_requested:false,real_project_media_processed:false,checked_at:checkedAt});const probePointer=await e(probe);
  await w(composite,{schema_version:'niannian_hq_full_composite_evidence_v2',status:'passed',test_media_kind:'synthetic_non_project_media',bindings,analysis_probe_receipt:probePointer,analysis_service_spend_authorized:true,analysis_service_network_requested:true,analysis_service_network_used:true,analysis_service_requests_created:2,analysis_service_jobs_created:1,provider_upload_requested:false,provider_submit_requested:false,spend_requested:false,real_project_media_processed:false,checked_at:checkedAt});
  const options={candidatePath:candidate,installPath:install,parityPath:parity,adoptionPath:adoption,statusPath:status,compositePath:composite,receiptPath:receipt,projectRoot:root,platform:'darwin',settingsVersion:2,settingsProfile:'fixture-v2',nowMs:now},ready=await build(options);assert.equal(ready.ready,true);assert.deepEqual(Object.keys(ready.capability_audits).sort(),[...REQUIRED,'runtime:hq'].sort());assert.equal(ready.composite.analysis_probe_receipt.sha256,probePointer.sha256);
  const runtimeHq=await syncHqCapabilityStatus(status,ready);assert.equal(runtimeHq.status,'ready');assert.equal(runtimeHq.checked_at,ready.checked_at);assert.equal(runtimeHq.expires_at,ready.expires_at);assert.equal(runtimeHq.evidence.method,'mac_step01_hq_v2_gate');
  await assert.rejects(()=>syncHqCapabilityStatus(status,{...ready,ready:false,status:'blocked'}),/gate_not_ready/);
  await assert.rejects(()=>syncHqCapabilityStatus(status,{...ready,expires_at:ready.checked_at}),/freshness_invalid/);
  const stale=JSON.parse(await fsp.readFile(status));stale.capabilities['runtime:transnetv2'].checked_at=new Date(now-56*60000).toISOString();await w(status,stale);assert.equal((await build({...options,receiptPath:path.join(root,'blocked.json')})).ready,false);
  await w(status,{schema_version:'niannian_runtime_capability_status_v1',capabilities:caps});const bad=JSON.parse(await fsp.readFile(composite));bad.bindings.install_receipt_sha256='0'.repeat(64);await w(composite,bad);assert.equal((await build({...options,receiptPath:path.join(root,'cross.json')})).ready,false);
  await w(composite,{schema_version:'niannian_hq_full_composite_evidence_v2',status:'passed',test_media_kind:'synthetic_non_project_media',bindings,analysis_probe_receipt:{...probePointer,sha256:'0'.repeat(64)},analysis_service_spend_authorized:true,analysis_service_network_requested:true,analysis_service_network_used:true,analysis_service_requests_created:2,analysis_service_jobs_created:1,provider_upload_requested:false,provider_submit_requested:false,spend_requested:false,real_project_media_processed:false,checked_at:checkedAt});assert.equal((await build({...options,receiptPath:path.join(root,'probe-tamper.json')})).ready,false);
  process.stdout.write(JSON.stringify({ok:true,verified:['v2 schema/host/project/settings/freshness/expiry','exact candidate/manifest/install/parity/adoption/entrypoint bindings','five capability audits','credential future expiry','runtime:hq derived from four fresh plus hash-bound paid synthetic analysis probe','stale/cross-binding/probe-tamper blocked','media provider upload/submit/spend false']})+'\n');
}finally{await fsp.rm(root,{recursive:true,force:true});}}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
