'use strict';
const assert=require('assert');
const crypto=require('crypto');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const promoter=require('./bridge/mac-employee-training/promote_step01_hq_full_toolchain');
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
async function write(file,value){await fsp.mkdir(path.dirname(file),{recursive:true});await fsp.writeFile(file,JSON.stringify(value,null,2)+'\n');}
async function ev(file){const bytes=await fsp.readFile(file);return{exact_path:path.resolve(file),sha256:sha(bytes),bytes:bytes.length};}
async function fixture(root,mutate={}){
  const bundle=path.join(root,'bundle');await fsp.mkdir(bundle,{recursive:true});
  const archivePath=path.join(bundle,'bundle.zip'),manifestPath=path.join(bundle,'manifest.json'),scanPath=path.join(bundle,'scan.json');await fsp.writeFile(archivePath,'zip');await write(manifestPath,{ok:true});await write(scanPath,{status:'passed'});
  const archive=await ev(archivePath),manifest=await ev(manifestPath),scan=await ev(scanPath);
  const entrySha='a'.repeat(64),candidatePath=path.join(root,'candidate.json');
  const candidate={schema_version:'niannian_step01_hq_full_toolchain_contract_v1',status:'blocked_install_pending',execution_authority_granted:false,profile:'hq_full',profile_release:'mac-step01-hq-full-evidence-v2',stable_batch_fallback_allowed:false,python:{exact_path:'/test/python',expected_exact_path:'/test/python'},entrypoint:{exact_path:'/test/entry.py',sha256:entrySha,runtime:'python312',argv_template:[]},command_order:[],skill_files:{},bundle_v2:{bundle_id:'niannian-mac-production-skills-v2',artifact_set_id:'fixture',archive:{project_relative_path:path.relative(root,archivePath),sha256:archive.sha256},manifest:{project_relative_path:path.relative(root,manifestPath),sha256:manifest.sha256},sensitive_scan:{project_relative_path:path.relative(root,scanPath),sha256:scan.sha256},skill_file_count:127,skill_count:13,source_snapshot_sha256:'b'.repeat(64)},hard_gates:{canonical_evidence_manifest:true},credential_transport:'child_environment_only',employee_model_channel:{channel_id:'krill_codex_custom_provider_v1',media_provider_authority_granted:false},analysis_service_network:{allowed_services:['mimo_asr','paddle_ocr'],media_provider_authority_granted:false}};await write(candidatePath,candidate);const candidateEv=await ev(candidatePath);
  const installPath=path.join(root,'install.json');await write(installPath,{status:'installed_verified',manifest_sha256:manifest.sha256});const install=await ev(installPath);
  const parityPath=path.join(root,'parity.json');await write(parityPath,{status:'exact_parity_verified',manifest_sha256:manifest.sha256});const parity=await ev(parityPath);
  const adoptionPath=path.join(root,'adoption.json');await write(adoptionPath,{status:'verified',completed:5,required_count:5,receipts:[],bindings:{toolchain_candidate_sha256:'0'.repeat(64),bundle_manifest_sha256:manifest.sha256,install_receipt_sha256:install.sha256,parity_receipt_sha256:parity.sha256,entrypoint_sha256:entrySha}});const adoption=await ev(adoptionPath);
  const now=Date.parse('2026-07-15T10:00:00.000Z'),hqPath=path.join(root,'hq.json');await write(hqPath,{schema_version:'niannian_step01_hq_full_gate_receipt_v2',status:'ready',ready:true,host:{platform:'darwin',project_root:path.resolve(root)},settings_binding:{version:2,profile:'mac-step01-hq-full-evidence-v2'},bindings:{toolchain_candidate_sha256:candidateEv.sha256,bundle_manifest_sha256:manifest.sha256,install_receipt_sha256:install.sha256,parity_receipt_sha256:parity.sha256,adoption_manifest_sha256:adoption.sha256,entrypoint_sha256:mutate.entrypointBinding||entrySha},composite:{ok:true},provider_upload_requested:false,provider_submit_requested:false,spend_requested:false,real_project_media_processed:false,real_delivery:false,checked_at:new Date(mutate.stale?now-16*60*1000:now-60000).toISOString(),expires_at:new Date(now+10*60*1000).toISOString()});
  return{now,options:{testMode:true,projectRoot:root,candidatePath,installPath,parityPath,adoptionPath,hqPath,outputPath:path.join(root,'accepted.json'),validator:async contract=>{assert.equal(contract.status,'accepted');assert.equal(contract.execution_authority_granted,true);assert.equal(contract.candidate_contract.sha256,candidateEv.sha256);assert.equal(contract.bundle_v2.archive_sha256,archive.sha256);assert.equal(contract.bundle_v2.manifest_sha256,manifest.sha256);assert.equal(contract.bundle_v2.sensitive_scan_sha256,scan.sha256);assert.equal(contract.acceptance_gates.fresh_hq_full_gate_receipt.required,true);return contract;}}};
}
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'step01-hq-promote-'));process.env.NIANNIAN_STEP01_TOOLCHAIN_PROMOTION_TEST_MODE='1';try{assert.equal(promoter.DEFAULTS.adoption.replaceAll('\\','/'),'/Users/lsb/AI-Brain/niannian-ai-canonical-local/output/mac-employee-training/v2.0.3-adoption-r2/adoption-manifest.json');const good=await fixture(path.join(root,'good'));const result=await promoter.promote({...good.options,nowMs:good.now});assert.equal(result.status,'accepted');assert.notEqual(result.accepted_contract.exact_path,result.candidate_contract.exact_path);const accepted=JSON.parse(await fsp.readFile(result.accepted_contract.exact_path));assert.equal(accepted.settings_binding.version,2);const bad=await fixture(path.join(root,'bad'),{entrypointBinding:'0'.repeat(64)});await assert.rejects(()=>promoter.promote({...bad.options,nowMs:bad.now}),/promotion_binding_invalid/);const stale=await fixture(path.join(root,'stale'),{stale:true});assert.equal((await promoter.promote({...stale.options,nowMs:stale.now})).status,'accepted');delete process.env.NIANNIAN_STEP01_TOOLCHAIN_PROMOTION_TEST_MODE;await assert.rejects(()=>promoter.promote({testMode:true,projectRoot:root}),/promotion_override_forbidden/);process.env.NIANNIAN_STEP01_TOOLCHAIN_PROMOTION_TEST_MODE='1';process.stdout.write(JSON.stringify({ok:true,verified:['production default v2.0.3 adoption-r2 path','candidate remains immutable','accepted contract exact receipt bindings','valid v2 gate bindings required','expired health telemetry does not block promotion','production overrides rejected']})+'\n');}finally{delete process.env.NIANNIAN_STEP01_TOOLCHAIN_PROMOTION_TEST_MODE;await fsp.rm(root,{recursive:true,force:true});}}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
