'use strict';

const assert=require('assert');
const crypto=require('crypto');
const events=require('events');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const {PROJECT_ROOT,THREADS}=require('./bridge/mac_codex_app_employee_bootstrap');
const fixed=require('./bridge/mac_codex_app_fixed_thread_turn');

function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
function b64url(bytes){return Buffer.from(bytes).toString('base64').replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_');}
function envelope(requestId,threadId,prompt='只读确认固定线程身份，不读取 secret，不写文件，不调用 Provider。'){
  return Buffer.from(JSON.stringify({schema_version:fixed.REQUEST_SCHEMA,request_id:requestId,thread_id:threadId,project_root:PROJECT_ROOT,purpose:'focused_test_read_only',read_only:true,network_access:false,prompt,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,package_send_requested:false,registry_promotion_requested:false,deployment_requested:false,local_image_editing_requested:false,production_write_requested:false,shell_command_requested:false},null,2)+'\n','utf8');
}
class FakeClient extends events.EventEmitter{
  constructor(options={}){super();this.options=options;this.reads=0;this.starts=0;this.resumes=[];this.interrupts=[];this.compactionStarts=0;this.turnId='turn-fixed-test';this.compactTurnId='compact-turn-fixed-test';this.completed=false;this.interrupted=false;this.compacted=false;}
  threadFor(fixedThread){
    this.reads+=1;const selected=fixedThread.thread_id===this.options.selectedThreadId;let title=fixedThread.title,cwd=PROJECT_ROOT,status={type:'idle'},turns=[];
    if(this.options.wrongIdentity&&selected)title='Wrong Title';
    if(this.options.activeThreadId===fixedThread.thread_id)status={type:'active'};
    if(this.options.notLoadedSelected&&selected&&this.resumes.length===0)status={type:'notLoaded'};
    if(this.options.casChange&&this.reads>THREADS.length&&fixedThread.employee==='02')turns=[{id:'external-turn',status:'completed',error:null,items:[{type:'agentMessage',text:'external'}]}];
    if(this.options.compactionFlow&&selected){turns=[{id:'historical-anchor',status:'completed',error:null,items:[{type:'agentMessage',text:'history'}]}];if(this.compacted)turns.push({id:this.compactTurnId,status:'completed',error:null,items:[{type:'compaction'}]});}
    if(this.completed&&selected)turns.push({id:this.turnId,status:this.options.stuck?(this.interrupted?'interrupted':'inProgress'):'completed',error:null,items:this.options.stuck?[]:[{type:'agentMessage',text:this.options.responseText===undefined?(this.options.expectLowEffort?'NIANNIAN_NATIVE_ACCOUNT_PROBE_OK':'readback ok'):this.options.responseText}]});
    return {id:fixedThread.thread_id,name:title,cwd,status,turns};
  }
  async request(method,params){
    if(method==='account/read')return {account:{type:'chatgpt'},requiresOpenaiAuth:true};
    if(method==='model/list')return {data:[{id:'native-default',model:'gpt-native-default',isDefault:true,hidden:false}]};
    if(method==='thread/read'){const fixedThread=THREADS.find(item=>item.thread_id===params.threadId);assert(fixedThread);return {thread:this.threadFor(fixedThread)};}
    if(method==='thread/resume'){this.resumes.push(params);assert.equal(params.threadId,this.options.selectedThreadId);assert.equal(params.cwd,PROJECT_ROOT);assert.equal(params.modelProvider,'openai');assert.equal(params.model,'gpt-native-default');return {ok:true};}
    if(method==='turn/start'){this.starts+=1;assert.equal(params.threadId,this.options.selectedThreadId);assert.equal(params.cwd,PROJECT_ROOT);assert.equal(params.model,'gpt-native-default');if(this.options.expectLowEffort)assert.equal(params.effort,'low');else assert.equal(params.effort,undefined);assert.equal(params.sandboxPolicy.type,'readOnly');assert.equal(params.sandboxPolicy.networkAccess,false);assert.equal(params.input[0].type,'text');this.completed=true;if(!this.options.stuck&&!this.options.missingNotification)setImmediate(()=>this.emit('notification',{method:'turn/completed',params:{threadId:this.options.selectedThreadId,turn:{id:this.turnId,status:this.options.objectNotificationStatus?{type:'completed'}:'completed',error:null}}}));return {turn:{id:this.turnId}};}
    if(method==='turn/interrupt'){assert.equal(params.threadId,this.options.selectedThreadId);assert.equal(params.turnId,this.turnId);this.interrupts.push(params);this.interrupted=true;return {};}
    if(method==='thread/compact/start'){assert.deepEqual(params,{threadId:this.options.selectedThreadId});this.compactionStarts+=1;this.compacted=true;setImmediate(()=>this.emit('notification',{method:'thread/compacted',params:{threadId:this.options.selectedThreadId,turnId:this.compactTurnId}}));return {};}
    throw new Error('unexpected_method:'+method);
  }
  async waitForTurn(threadId,turnId){assert.equal(threadId,this.options.selectedThreadId);assert.equal(turnId,this.turnId);return {id:this.turnId,status:'completed',error:null};}
  close(){}
}
async function assertRejectsCode(fn,pattern){await assert.rejects(fn,error=>pattern.test(String(error.message||error)));}
async function main(){
  const root=await fsp.mkdtemp(path.join(os.tmpdir(),'niannian-fixed-app-turn-'));
  try{
    assert.equal(fixed.markerProbe({prompt:'这是 Employee 01 的 native-account 只读鉴权探针。不要调用任何工具。只回复：NIANNIAN_NATIVE_ACCOUNT_PROBE_OK'}),true);assert.equal(fixed.markerProbe({prompt:'普通只读审计 NIANNIAN_NATIVE_ACCOUNT_PROBE_OK'}),false);
    const previousKrill=process.env.KRILL_CODEX_API_KEY,previousOpenAi=process.env.OPENAI_API_KEY;delete process.env.KRILL_CODEX_API_KEY;delete process.env.OPENAI_API_KEY;const envResult=fixed.ensureEmployeeModelRuntime();assert.equal(envResult.source,'codex_home_account_session');assert.equal(envResult.launch_mode,'native_account');assert.deepEqual(envResult.env_key_names,[]);assert.equal(envResult.raw_auth_read,false);assert.equal(process.env.KRILL_CODEX_API_KEY,undefined);assert.equal(process.env.OPENAI_API_KEY,undefined);if(previousKrill===undefined)delete process.env.KRILL_CODEX_API_KEY;else process.env.KRILL_CODEX_API_KEY=previousKrill;if(previousOpenAi===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=previousOpenAi;
    const selected=THREADS[0].thread_id,requestId='fixed-turn-test-0001',bytes=envelope(requestId,selected),sha=sha256(bytes);
    const receiptPath=path.join(root,'receipt.json');const client=new FakeClient({selectedThreadId:selected});
    const result=await fixed.runAppTurn({requestId,threadId:selected,envelopeSha256:sha,envelopeBase64Url:b64url(bytes),receiptPath,client});
    assert.equal(result.status,'completed_verified');assert.equal(result.receipt.thread_id,selected);assert.equal(result.receipt.media_provider_network_requested,false);assert.equal(result.receipt.thread_readback.response_sha256,sha256(Buffer.from('readback ok','utf8')));assert.equal(client.starts,1);
    const stats=await fsp.stat(receiptPath);if(process.platform!=='win32')assert.equal((stats.mode & 0o777),0o600);
    const replay=await fixed.runAppTurn({requestId,threadId:selected,envelopeSha256:sha,envelopeBase64Url:b64url(bytes),receiptPath,client:new FakeClient({selectedThreadId:selected})});assert.equal(replay.status,'replayed');
    const failedRequest='fixed-turn-failed-replay',failedBytes=envelope(failedRequest,selected),failedPath=path.join(root,'failed-replay.json');await fsp.writeFile(failedPath,JSON.stringify({schema_version:fixed.RECEIPT_SCHEMA,status:'failed',request_id:failedRequest,thread_id:selected,envelope_sha256:sha256(failedBytes),turn_start:{turn_id:'failed-turn'},error:{message:'readback_mismatch'},failure_readback:{latest_turn_id:'newer-turn'}},null,2)+'\n');const failedReplay=await fixed.runAppTurn({requestId:failedRequest,threadId:selected,envelopeSha256:sha256(failedBytes),envelopeBase64Url:b64url(failedBytes),receiptPath:failedPath,client:new FakeClient({selectedThreadId:selected})});assert.equal(failedReplay.status,'replayed_failed');assert.equal(failedReplay.receipt.turn_start.turn_id,'failed-turn');assert.equal(failedReplay.receipt.failure_readback.latest_turn_id,'newer-turn');
    const changed=envelope(requestId,selected,'只读确认固定线程身份，内容不同。');await assertRejectsCode(()=>fixed.runAppTurn({requestId,threadId:selected,envelopeSha256:sha256(changed),envelopeBase64Url:b64url(changed),receiptPath,client:new FakeClient({selectedThreadId:selected})}),/replay_conflict/);
    await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-bad-0001',threadId:'019f0000-0000-0000-0000-000000000000',envelopeSha256:sha,envelopeBase64Url:b64url(bytes),receiptPath:path.join(root,'bad.json'),client:new FakeClient({selectedThreadId:selected})}),/thread_id_rejected/);
    await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-bad-0002',threadId:selected,envelopeSha256:'0'.repeat(64),envelopeBase64Url:b64url(bytes),receiptPath:path.join(root,'bad2.json'),client:new FakeClient({selectedThreadId:selected})}),/sha_mismatch/);
    await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-bad-0003',threadId:selected,envelopeSha256:sha,envelopeBase64Url:'not+base64',receiptPath:path.join(root,'bad3.json'),client:new FakeClient({selectedThreadId:selected})}),/base64url_invalid/);
    const secretBytes=envelope('fixed-turn-bad-0004',selected,'这里有 sk-testsecret1234567890');await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-bad-0004',threadId:selected,envelopeSha256:sha256(secretBytes),envelopeBase64Url:b64url(secretBytes),receiptPath:path.join(root,'bad4.json'),client:new FakeClient({selectedThreadId:selected})}),/secret_like_content_rejected/);
    const over=Buffer.alloc(fixed.MAX_ENVELOPE_BYTES+1,65).toString('base64').replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_');await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-bad-0005',threadId:selected,envelopeSha256:'a'.repeat(64),envelopeBase64Url:over,receiptPath:path.join(root,'bad5.json'),client:new FakeClient({selectedThreadId:selected})}),/envelope_size_invalid/);
    const activeClient=new FakeClient({selectedThreadId:selected,activeThreadId:THREADS[2].thread_id});await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-active-1',threadId:selected,envelopeSha256:sha256(envelope('fixed-turn-active-1',selected)),envelopeBase64Url:b64url(envelope('fixed-turn-active-1',selected)),receiptPath:path.join(root,'active.json'),client:activeClient}),/active_thread/);assert.equal(activeClient.starts,0);
    const casBytes=envelope('fixed-turn-cas-0001',selected),casClient=new FakeClient({selectedThreadId:selected,casChange:true});await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-cas-0001',threadId:selected,envelopeSha256:sha256(casBytes),envelopeBase64Url:b64url(casBytes),receiptPath:path.join(root,'cas.json'),client:casClient}),/thread_cas_changed/);assert.equal(casClient.starts,0);
    const attemptRows=(await fsp.readFile(receiptPath+'.attempts.jsonl','utf8')).trim().split(/\r?\n/).map(line=>JSON.parse(line));assert.deepEqual(attemptRows.map(row=>row.event_type),['dispatch_claimed','codex_turn_completed']);assert.equal(attemptRows[0].request_id,requestId);assert.equal(attemptRows[1].turn_id,client.turnId);
    const wrongBytes=envelope('fixed-turn-wrong-01',selected),wrongClient=new FakeClient({selectedThreadId:selected,wrongIdentity:true});await assertRejectsCode(()=>fixed.runAppTurn({requestId:'fixed-turn-wrong-01',threadId:selected,envelopeSha256:sha256(wrongBytes),envelopeBase64Url:b64url(wrongBytes),receiptPath:path.join(root,'wrong.json'),client:wrongClient}),/thread_identity_mismatch/);
    const nlBytes=envelope('fixed-turn-nl-0001',selected),nlClient=new FakeClient({selectedThreadId:selected,notLoadedSelected:true});const nl=await fixed.runAppTurn({requestId:'fixed-turn-nl-0001',threadId:selected,envelopeSha256:sha256(nlBytes),envelopeBase64Url:b64url(nlBytes),receiptPath:path.join(root,'nl.json'),client:nlClient});assert.equal(nl.status,'completed_verified');assert.equal(nlClient.resumes.length,1);assert.equal(nlClient.starts,1);
    const emptyTextBytes=envelope('fixed-turn-emptytxt',selected),emptyTextClient=new FakeClient({selectedThreadId:selected,emitNotification:true,responseText:''});const emptyText=await fixed.runAppTurn({requestId:'fixed-turn-emptytxt',threadId:selected,envelopeSha256:sha256(emptyTextBytes),envelopeBase64Url:b64url(emptyTextBytes),receiptPath:path.join(root,'empty-text.json'),client:emptyTextClient});assert.equal(emptyText.status,'completed_verified');assert.equal(emptyText.receipt.completion_event.notification_shape.method,'turn/completed');assert.equal(emptyText.receipt.completion_event.notification_shape.turn_status,'completed');assert.equal(emptyText.receipt.thread_readback.response_bytes,0);
    const objectStatusBytes=envelope('fixed-turn-object-status',selected),objectStatusClient=new FakeClient({selectedThreadId:selected,objectNotificationStatus:true});const objectStatus=await fixed.runAppTurn({requestId:'fixed-turn-object-status',threadId:selected,envelopeSha256:sha256(objectStatusBytes),envelopeBase64Url:b64url(objectStatusBytes),receiptPath:path.join(root,'object-status.json'),client:objectStatusClient});assert.equal(objectStatus.status,'completed_verified');assert.equal(objectStatus.receipt.completion_event.status,'completed');
    const markerRequest='fixed-turn-marker-low',markerBytes=envelope(markerRequest,selected,'NIANNIAN_NATIVE_ACCOUNT_PROBE_OK'),markerClient=new FakeClient({selectedThreadId:selected,expectLowEffort:true});const markerResult=await fixed.runAppTurn({requestId:markerRequest,threadId:selected,envelopeSha256:sha256(markerBytes),envelopeBase64Url:b64url(markerBytes),receiptPath:path.join(root,'marker.json'),client:markerClient,pollMs:1,notificationGraceMs:5});assert.equal(markerResult.receipt.turn_start.reasoning_effort,'low');assert.equal(markerResult.receipt.turn_start.timeout_class,'marker_probe');assert.equal(markerResult.receipt.turn_start.timeout_ms,fixed.MARKER_PROBE_TIMEOUT_MS);assert.equal(markerResult.receipt.lifecycle_monitor.interrupt_requested,false);
    const missingRequest='fixed-turn-missing-notification',missingBytes=envelope(missingRequest,selected),missingPath=path.join(root,'missing-notification.json'),missingClient=new FakeClient({selectedThreadId:selected,missingNotification:true});await assertRejectsCode(()=>fixed.runAppTurn({requestId:missingRequest,threadId:selected,envelopeSha256:sha256(missingBytes),envelopeBase64Url:b64url(missingBytes),receiptPath:missingPath,client:missingClient,timeoutMs:100,pollMs:1,notificationGraceMs:5}),/completion_notification_missing/);assert.equal(missingClient.interrupts.length,0);assert.equal((JSON.parse(await fsp.readFile(missingPath,'utf8'))).lifecycle_monitor.stage,'completed_readback_without_notification');
    const stuckRequest='fixed-turn-stuck-exact',stuckBytes=envelope(stuckRequest,selected,'NIANNIAN_NATIVE_ACCOUNT_PROBE_OK'),stuckPath=path.join(root,'stuck.json'),stuckClient=new FakeClient({selectedThreadId:selected,stuck:true,expectLowEffort:true});await assertRejectsCode(()=>fixed.runAppTurn({requestId:stuckRequest,threadId:selected,envelopeSha256:sha256(stuckBytes),envelopeBase64Url:b64url(stuckBytes),receiptPath:stuckPath,client:stuckClient,timeoutMs:20,pollMs:1,interruptGraceMs:20,notificationGraceMs:5}),/completion_timeout_interrupted/);assert.equal(stuckClient.interrupts.length,1);assert.deepEqual(stuckClient.interrupts[0],{threadId:selected,turnId:stuckClient.turnId});const stuckReceipt=JSON.parse(await fsp.readFile(stuckPath,'utf8'));assert.equal(stuckReceipt.lifecycle_monitor.interrupt_requested,true);assert.equal(stuckReceipt.lifecycle_monitor.interrupt_turn_id,stuckClient.turnId);assert.equal(stuckReceipt.failure_readback.latest_turn_status,'interrupted');const stuckReplay=await fixed.runAppTurn({requestId:stuckRequest,threadId:selected,envelopeSha256:sha256(stuckBytes),envelopeBase64Url:b64url(stuckBytes),receiptPath:stuckPath,client:new FakeClient({selectedThreadId:selected})});assert.equal(stuckReplay.status,'replayed_failed');assert.equal(stuckReplay.receipt.turn_start.turn_id,stuckClient.turnId);
    const recoveryRequest='fixed-turn-compact-probe',recoveryPrompt='这是 Employee 01 的 native-account 只读鉴权探针。不要调用任何工具，不要读取或修改文件。只回复：NIANNIAN_NATIVE_ACCOUNT_PROBE_OK',recoveryBytes=envelope(recoveryRequest,selected,recoveryPrompt),recoveryClient=new FakeClient({selectedThreadId:selected,expectLowEffort:true,compactionFlow:true}),recoveryResult=await fixed.runAppTurn({requestId:recoveryRequest,threadId:selected,envelopeSha256:sha256(recoveryBytes),envelopeBase64Url:b64url(recoveryBytes),receiptPath:path.join(root,'recovery.json'),compactionReceiptPath:path.join(root,'compaction.json'),client:recoveryClient,pollMs:1,notificationGraceMs:5,compactionTimeoutMs:100,compactionTerminalTimeoutMs:100,compactionPollMs:1});assert.equal(recoveryClient.compactionStarts,1);assert.equal(recoveryResult.receipt.pre_turn_compaction.status,'completed_verified');assert.equal(recoveryResult.receipt.pre_turn_compaction.thread_id,selected);assert.equal(recoveryResult.receipt.marker_probe.verified,true);
    assert.equal(fixed.normalizeTurnStatus({status:'completed'}),'completed');assert.equal(fixed.normalizeTurnStatus({completed:null}),'completed');assert.equal(fixed.normalizeTurnStatus({failed:{message:'hidden'}}),'failed');
    process.stdout.write(JSON.stringify({ok:true,verified:['fixed five thread allowlist','schema/request/thread/sha/base64/size validation','secret-like content rejection','native account route reads only account presence booleans and injects no API key','append-only dispatch and completion attempt events','all-five active rejection before start','second-read CAS rejection','selected notLoaded exact resume only','read-only networkAccess false turn/start','exact turn/completed notification status=completed error=null','exact latest-turn thread/readback matches started turn','mode-600 receipt','same request replay','failed replay exposes redacted turn/error/readback evidence','same request different payload conflict','no assistant text still clean completion with empty response hash/bytes','redacted response hash and bytes']})+'\n');
  }finally{await fsp.rm(root,{recursive:true,force:true});}
}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
