'use strict';

const assert = require('assert');
const crypto = require('crypto');
const fsp = require('fs').promises;
const os = require('os');
const path = require('path');
const dispatcher = require('./bridge/niannian_redraw_step02_mac_app_dispatcher');
const step02 = require('./bridge/niannian_redraw_step02_vertical');
const {PROJECT_ROOT,THREADS} = require('./bridge/mac_codex_app_employee_bootstrap');

const sha256 = value => crypto.createHash('sha256').update(value).digest('hex');
async function writeJson(filePath,value) { await fsp.mkdir(path.dirname(filePath),{recursive:true}); await fsp.writeFile(filePath,JSON.stringify(value,null,2)+'\n'); }
async function pointer(filePath) { const bytes=await fsp.readFile(filePath); return {sha256:sha256(bytes),bytes:bytes.length}; }
const effects = () => Object.fromEntries(step02.EFFECTS.map(key => [key,false]));
function candidate(dispatch) { return {schema_version:step02.SCHEMAS.candidate,status:'candidate',downstream_consumable:false,test_only:false,fixture_evidence:false,transaction_id:dispatch.transaction_id,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key,project_id:dispatch.project_id,job_id:dispatch.job_id,source_sha256:dispatch.source_sha256,rights_authority_sha256:dispatch.rights_authority_sha256,step01_manifest_sha256:dispatch.step01_manifest_sha256,settings_version:dispatch.settings_version,source_media_contract:{duration_seconds:10,visual_duration_seconds:9.9},sourceRows:[{shot_id:'S001',source_start_sec:0,source_end_sec:3,story_beat:'相遇',visual_composition:'角色甲站在门内，角色乙位于前景右侧。',blocking_movement:'角色甲向前一步，角色乙转身。'}],dialogueBindings:[{dialogue_id:'D001',source_start_sec:.4,source_end_sec:2,onset_shot:'S001',best_evidence_shot:'S001',source_speaker:'角色甲',source_text:'你终于来了。',evidence_basis:['forced_aligner','subtitle','mouth'],speaker_attribution_status:'onscreen_mouth'}],visualFactCards:[],textEvidence:[],assetCandidates:[],hardSceneCandidates:[],rejectedEvidence:[],blockers:[],...effects()}; }
async function seed(root,suffix='base') {
  const workspace=path.join(root,suffix), sourceSha=sha256('source-'+suffix), rightsSha=sha256('rights-'+suffix), step01Sha=sha256('step01-'+suffix);
  const authority={schema_version:step02.SCHEMAS.authority,status:'verified',transaction_id:'txn-'+suffix,project_id:'NN-'+suffix.toUpperCase().padEnd(10,'X'),job_id:'job-'+suffix,owner_id:'owner-'+suffix,source:{sha256:sourceSha,bytes:123},rights_authority:{event_id:'rights-'+suffix,sha256:rightsSha,status:'confirmed',revoked:false},settings_version:2,step01:{manifest:{sha256:step01Sha,bytes:100},receipt:{sha256:sha256('r'),bytes:1},control:{sha256:sha256('c'),bytes:1}},source_media_contract:{duration_seconds:10,visual_duration_seconds:9.9},...effects()};
  await writeJson(path.join(workspace,'upstream_authority_snapshot.json'),authority); const authorityEvidence=await pointer(path.join(workspace,'upstream_authority_snapshot.json'));
  const employee=THREADS[1];
  const dispatch={schema_version:step02.SCHEMAS.dispatch,status:'prepared',test_only:false,execution_mode:'fixed_existing_mac_app_candidate_only',transaction_id:authority.transaction_id,dispatch_id:'dispatch-'+suffix,phase_key:'phase-'+suffix,project_id:authority.project_id,job_id:authority.job_id,owner_id:authority.owner_id,owner_action_event_id:'owner-action-'+suffix,source_sha256:sourceSha,rights_authority_sha256:rightsSha,step01_manifest_sha256:step01Sha,upstream_authority_sha256:authorityEvidence.sha256,settings_version:2,employee:{...employee,project_root:dispatcher.MAC_PROJECT},transport:{fixed_app_required:true,thread_read_before_start:true,active_turn_reject:true,cli_fallback_allowed:false,ephemeral_thread_allowed:false,legacy_latest_lookup_allowed:false},allowed_write_paths:['step02_source_truth_candidate.json','step02_employee_receipt.json','step02_control_receipt.json','step02_app_server_audit.json','step02_app_server_response.json','step02_return_manifest.json'],...effects()};
  await writeJson(path.join(workspace,'step02_employee_dispatch.json'),dispatch);
  const roleNames={source_ffprobe:'ffprobe.json',minute_chunks:'minute_chunks.json',native_frame:'native/frame.png',accepted_transnet_shots:'transnet.json',transnet_start_mid_end_supplement:'supplement.json',source_audio_wav:'audio.wav',audio_event_ledger:'audio_events.json',mimo_transcript:'mimo.json',forced_aligner:'aligner.json',paddle_ocr:'ocr.json',strict_validation:'validation.json'};
  const entries=[]; for(const [role,name] of Object.entries(roleNames)){const relative='upstream/evidence/'+name;await fsp.mkdir(path.dirname(path.join(workspace,relative)),{recursive:true});await fsp.writeFile(path.join(workspace,relative),Buffer.from('evidence-'+role));entries.push({original_relative_path:name,package_relative_path:relative,...await pointer(path.join(workspace,relative)),role});}
  await writeJson(path.join(workspace,'step02_portable_evidence_index.json'),{schema_version:'niannian_redraw_step02_portable_evidence_index_v1',status:'verified',project_id:dispatch.project_id,transaction_id:dispatch.transaction_id,source_sha256:dispatch.source_sha256,step01_manifest_sha256:dispatch.step01_manifest_sha256,artifact_count:entries.length,entries,test_only:false,fixture_evidence:false,...effects()});
  const skillRoot=path.join(workspace,'installed-skills'),skillRows=[];for(const relative of ['mx-shortdrama-00-router/SKILL.md','mx-shortdrama-02-source-timeline/SKILL.md']){const exact=path.join(skillRoot,...relative.split('/'));await fsp.mkdir(path.dirname(exact),{recursive:true});await fsp.writeFile(exact,'# synthetic '+relative+'\n');skillRows.push({relative_path:relative,mac_exact_path:'/Users/lsb/.codex/skills/'+relative,...await pointer(exact)});}
  const installPath=path.join(workspace,'governance/mac_v2_install_receipt.json'),parityPath=path.join(workspace,'governance/mac_v2_parity_receipt.json'),adoptionPath=path.join(workspace,'governance/five_employee_adoption_manifest.json'),routePath=path.join(workspace,'governance/route_matrix.json');await writeJson(installPath,{schema_version:'niannian_mac_skill_bundle_install_receipt_v2',status:'installed_verified'});await writeJson(parityPath,{schema_version:'niannian_mac_skill_bundle_parity_receipt_v2',status:'exact_parity_verified'});const installEv=await pointer(installPath),parityEv=await pointer(parityPath);await writeJson(adoptionPath,{schema_version:'niannian_mac_employee_v2_adoption_manifest_v1',status:'verified',bindings:{install_receipt_sha256:installEv.sha256,parity_receipt_sha256:parityEv.sha256},employee_model_channel:{channel_id:'krill_codex_custom_provider_v1',used:true,network_used:true,media_provider_authority_granted:false}});await writeJson(routePath,{schema_version:'niannian_mac_employee_route_matrix_v1',employee_model_channel:{channel_id:'krill_codex_custom_provider_v1',media_provider_authority_granted:false}});const adoptionEv=await pointer(adoptionPath),routeEv=await pointer(routePath);
  await writeJson(path.join(workspace,'step02_runtime_governance.json'),{schema_version:'niannian_redraw_step02_runtime_governance_v1',status:'verified',bundle_id:'niannian-mac-production-skills-v2',bundle_manifest_sha256:sha256('bundle'),managed_skills:13,managed_file_count:127,unmanaged_preserved:true,receipts:{install:{relative_path:'governance/mac_v2_install_receipt.json',...installEv},parity:{relative_path:'governance/mac_v2_parity_receipt.json',...parityEv},adoption:{relative_path:'governance/five_employee_adoption_manifest.json',...adoptionEv},route_matrix:{relative_path:'governance/route_matrix.json',...routeEv}},skills:skillRows,employee_model_channel:{channel_id:'krill_codex_custom_provider_v1',used:true,network_used:true,media_provider_authority_granted:false}});
  return {workspace,dispatch,authority,skillRoot};
}
class FakeClient {
  constructor(dispatch,candidateValue,scenario={}) { this.dispatch=dispatch;this.candidateValue=candidateValue;this.scenario=scenario;this.calls=[];this.starts=0;this.waits=0;this.threadReads=0;this.turnId='turn-'+dispatch.dispatch_id;this.completed=false; }
  thread(employee) {
    const wrong=this.scenario.wrongIdentity===employee.employee, active=this.scenario.activeEmployee===employee.employee;
    let turns=[]; if(employee.thread_id===this.dispatch.employee.thread_id&&this.completed){const target={id:this.scenario.wrongFinalTurn?'other-turn':this.turnId,status:'completed',error:this.scenario.targetError?{message:'synthetic terminal error'}:null,items:this.scenario.missingAssistant?[]:[{type:'agentMessage',text:JSON.stringify(this.candidateValue)}]};turns=[target];if(this.scenario.laterNewer)turns.push({id:'newer-unrelated-turn',status:'completed',error:null,items:[{type:'agentMessage',text:'unrelated newer response'}]});}
    if(this.scenario.secondReadMutation&&this.threadReads>5&&employee.employee==='03')turns=[{id:'concurrent-change',status:'completed',error:null,items:[{type:'agentMessage',text:'changed'}]}];
    if(active) turns=[{id:'active-'+employee.employee,status:'inProgress',items:[]}];
    return {id:employee.thread_id,name:wrong?'wrong title':employee.title,cwd:wrong?'/tmp/wrong':PROJECT_ROOT,status:{type:this.scenario.notLoaded===employee.employee?'notLoaded':'loaded'},turns};
  }
  async request(method,params){this.calls.push({method,params});if(method==='thread/read'){this.threadReads++;const employee=THREADS.find(item=>item.thread_id===params.threadId);return {thread:this.thread(employee)};}if(method==='thread/resume')return {thread:{id:params.threadId}};if(method==='turn/start'){this.starts++;assert.equal(params.threadId,this.dispatch.employee.thread_id);this.completed=true;return {turn:{id:this.turnId}};}throw new Error('unexpected:'+method);}
  async waitForTurn(){this.waits++;if(this.scenario.waitDelay)await new Promise(resolve=>setTimeout(resolve,this.scenario.waitDelay));if(this.scenario.turnError)return {id:this.turnId,status:'failed',error:{message:'synthetic'}};return {id:this.turnId,status:'completed',error:null};}
}
async function expectCode(work,errorCode,client){await assert.rejects(work,error=>error.code===errorCode||error.message===errorCode);if(client)assert.equal(client.starts,0);}
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'step02-app-dispatcher-'));try{
  const pass=await seed(root,'pass'), passClient=new FakeClient(pass.dispatch,candidate(pass.dispatch),{notLoaded:'02'});const result=await dispatcher.run({dispatchPath:path.join(pass.workspace,'step02_employee_dispatch.json'),workspace:pass.workspace,leaseRoot:path.join(root,'leases-pass'),client:passClient,timeoutMs:100,testMode:true,skillRoot:pass.skillRoot});assert.equal(result.replay,false);assert.equal(passClient.starts,1);const firstStart=passClient.calls.findIndex(item=>item.method==='turn/start');assert.equal(passClient.calls.slice(0,firstStart).filter(item=>item.method==='thread/read').length,10);assert(passClient.calls.findIndex(item=>item.method==='thread/resume')<firstStart);const request=passClient.calls[firstStart].params;assert.equal(request.sandboxPolicy.type,'readOnly');assert.equal(request.sandboxPolicy.networkAccess,false);assert(request.input[0].text.includes('portable_step01_evidence_index=step02_portable_evidence_index.json'));assert(request.input[0].text.includes('禁止 old/latest/15秒项目'));
  const replayClient=new FakeClient(pass.dispatch,candidate(pass.dispatch));const replay=await dispatcher.run({dispatchPath:path.join(pass.workspace,'step02_employee_dispatch.json'),workspace:pass.workspace,leaseRoot:path.join(root,'leases-replay'),client:replayClient,testMode:true,skillRoot:pass.skillRoot});assert.equal(replay.replay,true);assert.equal(replayClient.starts,0);
  const tampered=await fsp.readFile(path.join(pass.workspace,'step02_source_truth_candidate.json'),'utf8');await fsp.writeFile(path.join(pass.workspace,'step02_source_truth_candidate.json'),tampered+' ');const tamperClient=new FakeClient(pass.dispatch,candidate(pass.dispatch));await expectCode(()=>dispatcher.run({dispatchPath:path.join(pass.workspace,'step02_employee_dispatch.json'),workspace:pass.workspace,leaseRoot:path.join(root,'leases-tamper'),client:tamperClient,testMode:true,skillRoot:pass.skillRoot}),'STEP02_APP_REPLAY_INVALID',tamperClient);
  const active=await seed(root,'active'),activeClient=new FakeClient(active.dispatch,candidate(active.dispatch),{activeEmployee:'04'});await expectCode(()=>dispatcher.run({dispatchPath:path.join(active.workspace,'step02_employee_dispatch.json'),workspace:active.workspace,leaseRoot:path.join(root,'leases-active'),client:activeClient,testMode:true,skillRoot:active.skillRoot}),'STEP02_APP_ACTIVE_TURN_PRESENT',activeClient);assert.equal(activeClient.calls.filter(item=>item.method==='thread/read').length,5);
  const wrong=await seed(root,'wrong'),wrongClient=new FakeClient(wrong.dispatch,candidate(wrong.dispatch),{wrongIdentity:'03'});await expectCode(()=>dispatcher.run({dispatchPath:path.join(wrong.workspace,'step02_employee_dispatch.json'),workspace:wrong.workspace,leaseRoot:path.join(root,'leases-wrong'),client:wrongClient,testMode:true,skillRoot:wrong.skillRoot}),'STEP02_APP_THREAD_IDENTITY_INVALID:03',wrongClient);
  const error=await seed(root,'error'),errorClient=new FakeClient(error.dispatch,candidate(error.dispatch),{turnError:true});await assert.rejects(()=>dispatcher.run({dispatchPath:path.join(error.workspace,'step02_employee_dispatch.json'),workspace:error.workspace,leaseRoot:path.join(root,'leases-error'),client:errorClient,timeoutMs:100,testMode:true,skillRoot:error.skillRoot}));assert.equal(errorClient.starts,1);assert.equal(await fsp.stat(path.join(root,'leases-error',error.dispatch.employee.thread_id)).then(s=>s.isDirectory()),true);
  const final=await seed(root,'final'),finalClient=new FakeClient(final.dispatch,candidate(final.dispatch),{wrongFinalTurn:true});await expectCode(()=>dispatcher.run({dispatchPath:path.join(final.workspace,'step02_employee_dispatch.json'),workspace:final.workspace,leaseRoot:path.join(root,'leases-final'),client:finalClient,timeoutMs:100,testMode:true,skillRoot:final.skillRoot}),'STEP02_APP_THREAD_READBACK_MISMATCH');assert.equal(finalClient.starts,1);
  const cross=await seed(root,'cross'),bad=candidate(cross.dispatch);bad.project_id='NN-FOREIGN';const crossClient=new FakeClient(cross.dispatch,bad);await expectCode(()=>dispatcher.run({dispatchPath:path.join(cross.workspace,'step02_employee_dispatch.json'),workspace:cross.workspace,leaseRoot:path.join(root,'leases-cross'),client:crossClient,timeoutMs:100,testMode:true,skillRoot:cross.skillRoot}),'STEP02_APP_CANDIDATE_BINDING_INVALID');assert.equal(crossClient.starts,1);
  const crash=await seed(root,'crash'),crashClient=new FakeClient(crash.dispatch,candidate(crash.dispatch));await assert.rejects(()=>dispatcher.run({dispatchPath:path.join(crash.workspace,'step02_employee_dispatch.json'),workspace:crash.workspace,leaseRoot:path.join(root,'leases-crash'),client:crashClient,afterTurnAcceptedBeforeJournal:()=>{throw step02.codeError('SYNTHETIC_CRASH');},testMode:true,skillRoot:crash.skillRoot}),/SYNTHETIC_CRASH/);assert.equal(crashClient.starts,1);const resumed=await dispatcher.run({dispatchPath:path.join(crash.workspace,'step02_employee_dispatch.json'),workspace:crash.workspace,leaseRoot:path.join(root,'leases-crash'),client:crashClient,timeoutMs:100,testMode:true,skillRoot:crash.skillRoot});assert.equal(resumed.replay,false);assert.equal(crashClient.starts,1);assert.equal(resumed.audit.recovered_existing_turn,true);
  const stale=await seed(root,'stale');await fsp.writeFile(path.join(stale.workspace,'upstream/evidence/ffprobe.json'),'tampered');const staleClient=new FakeClient(stale.dispatch,candidate(stale.dispatch));await expectCode(()=>dispatcher.run({dispatchPath:path.join(stale.workspace,'step02_employee_dispatch.json'),workspace:stale.workspace,leaseRoot:path.join(root,'leases-stale'),client:staleClient,testMode:true,skillRoot:stale.skillRoot}),'STEP02_APP_PORTABLE_EVIDENCE_TAMPERED',staleClient);
  for(const [index,name] of ['step02_employee_receipt.json','step02_control_receipt.json','step02_app_server_audit.json','step02_app_server_response.json'].entries()){const current=await seed(root,'replaytamper'+index),client=new FakeClient(current.dispatch,candidate(current.dispatch));await dispatcher.run({dispatchPath:path.join(current.workspace,'step02_employee_dispatch.json'),workspace:current.workspace,leaseRoot:path.join(root,'leases-rt'+index),client,testMode:true,skillRoot:current.skillRoot});await fsp.appendFile(path.join(current.workspace,name),' ');const replayTamperClient=new FakeClient(current.dispatch,candidate(current.dispatch));await expectCode(()=>dispatcher.run({dispatchPath:path.join(current.workspace,'step02_employee_dispatch.json'),workspace:current.workspace,leaseRoot:path.join(root,'leases-rt-replay'+index),client:replayTamperClient,testMode:true,skillRoot:current.skillRoot}),'STEP02_APP_REPLAY_INVALID',replayTamperClient);}
  const skillTamper=await seed(root,'skilltamper');await fsp.appendFile(path.join(skillTamper.skillRoot,'mx-shortdrama-02-source-timeline','SKILL.md'),'tamper');const skillClient=new FakeClient(skillTamper.dispatch,candidate(skillTamper.dispatch));await expectCode(()=>dispatcher.run({dispatchPath:path.join(skillTamper.workspace,'step02_employee_dispatch.json'),workspace:skillTamper.workspace,leaseRoot:path.join(root,'leases-skill'),client:skillClient,testMode:true,skillRoot:skillTamper.skillRoot}),'STEP02_APP_RUNTIME_SKILL_TAMPERED',skillClient);
  const leaseRoot=path.join(root,'lease-stale-unknown'),leasePath=path.join(leaseRoot,pass.dispatch.employee.thread_id);await fsp.mkdir(leasePath,{recursive:true});await writeJson(path.join(leasePath,'lease.json'),{schema_version:dispatcher.LEASE_SCHEMA,status:'claimed',dispatch_id:'foreign-dispatch',phase_key:'foreign-phase',transaction_id:'foreign-txn',employee_thread_id:pass.dispatch.employee.thread_id,expires_at:'2020-01-01T00:00:00.000Z'});await assert.rejects(()=>dispatcher.acquireLease(leasePath,pass.dispatch),error=>error.code==='STEP02_APP_STALE_LEASE_UNKNOWN_TURN');assert.equal(await fsp.stat(leasePath).then(s=>s.isDirectory()),true);
  const emptyLeasePath=path.join(root,'empty-lease',pass.dispatch.employee.thread_id);await fsp.mkdir(emptyLeasePath,{recursive:true});const recoveredEmpty=await dispatcher.acquireLease(emptyLeasePath,pass.dispatch);assert.equal(recoveredEmpty.replay,false);assert.equal((await fsp.readdir(emptyLeasePath)).includes('lease.json'),true);await fsp.rm(path.dirname(emptyLeasePath),{recursive:true,force:true});
  const replayLeasePath=path.join(root,'leases-replay-cleanup',pass.dispatch.employee.thread_id);await fsp.mkdir(replayLeasePath,{recursive:true});await writeJson(path.join(replayLeasePath,'lease.json'),{schema_version:dispatcher.LEASE_SCHEMA,status:'claimed',dispatch_id:pass.dispatch.dispatch_id,phase_key:pass.dispatch.phase_key,transaction_id:pass.dispatch.transaction_id,employee_thread_id:pass.dispatch.employee.thread_id,expires_at:'2030-01-01T00:00:00.000Z'});const cleanupReplayClient=new FakeClient(pass.dispatch,candidate(pass.dispatch));await assert.rejects(()=>dispatcher.run({dispatchPath:path.join(pass.workspace,'step02_employee_dispatch.json'),workspace:pass.workspace,leaseRoot:path.join(root,'leases-replay-cleanup'),client:cleanupReplayClient,testMode:true,skillRoot:pass.skillRoot}),error=>error.code==='STEP02_APP_REPLAY_INVALID');
  const cleanReplay=await seed(root,'cleanreplay'),cleanClient=new FakeClient(cleanReplay.dispatch,candidate(cleanReplay.dispatch));await dispatcher.run({dispatchPath:path.join(cleanReplay.workspace,'step02_employee_dispatch.json'),workspace:cleanReplay.workspace,leaseRoot:path.join(root,'leases-cleanreplay'),client:cleanClient,testMode:true,skillRoot:cleanReplay.skillRoot});const staleSame=path.join(root,'leases-cleanreplay',cleanReplay.dispatch.employee.thread_id);await fsp.mkdir(staleSame,{recursive:true});await writeJson(path.join(staleSame,'lease.json'),{schema_version:dispatcher.LEASE_SCHEMA,status:'claimed',dispatch_id:cleanReplay.dispatch.dispatch_id,phase_key:cleanReplay.dispatch.phase_key,transaction_id:cleanReplay.dispatch.transaction_id,employee_thread_id:cleanReplay.dispatch.employee.thread_id,expires_at:'2030-01-01T00:00:00.000Z'});const cleanReplayClient=new FakeClient(cleanReplay.dispatch,candidate(cleanReplay.dispatch));await dispatcher.run({dispatchPath:path.join(cleanReplay.workspace,'step02_employee_dispatch.json'),workspace:cleanReplay.workspace,leaseRoot:path.join(root,'leases-cleanreplay'),client:cleanReplayClient,testMode:true,skillRoot:cleanReplay.skillRoot});assert.equal(await fsp.stat(staleSame).then(()=>true,()=>false),false);assert.equal(cleanReplayClient.starts,0);
  const cas=await seed(root,'cas'),casClient=new FakeClient(cas.dispatch,candidate(cas.dispatch),{secondReadMutation:true});await expectCode(()=>dispatcher.run({dispatchPath:path.join(cas.workspace,'step02_employee_dispatch.json'),workspace:cas.workspace,leaseRoot:path.join(root,'leases-cas'),client:casClient,testMode:true,skillRoot:cas.skillRoot}),'STEP02_APP_THREAD_STATE_CHANGED_BEFORE_START',casClient);
  for(const [suffix,scenario,code] of [['terminalerror',{targetError:true},'STEP02_APP_TARGET_TURN_COMPLETED_ERROR'],['missingassistant',{missingAssistant:true},'STEP02_APP_TARGET_TURN_ASSISTANT_MISSING']]){const current=await seed(root,suffix),client=new FakeClient(current.dispatch,candidate(current.dispatch));await assert.rejects(()=>dispatcher.run({dispatchPath:path.join(current.workspace,'step02_employee_dispatch.json'),workspace:current.workspace,leaseRoot:path.join(root,'leases-'+suffix),client,testMode:true,skillRoot:current.skillRoot,afterTurnStarted:()=>{throw step02.codeError('SYNTHETIC_AFTER_JOURNAL_CRASH');}}),/SYNTHETIC_AFTER_JOURNAL_CRASH/);Object.assign(client.scenario,scenario);await expectCode(()=>dispatcher.run({dispatchPath:path.join(current.workspace,'step02_employee_dispatch.json'),workspace:current.workspace,leaseRoot:path.join(root,'leases-'+suffix),client,testMode:true,skillRoot:current.skillRoot}),code);assert.equal(client.starts,1);}
  const newer=await seed(root,'newer'),newerClient=new FakeClient(newer.dispatch,candidate(newer.dispatch));await assert.rejects(()=>dispatcher.run({dispatchPath:path.join(newer.workspace,'step02_employee_dispatch.json'),workspace:newer.workspace,leaseRoot:path.join(root,'leases-newer'),client:newerClient,testMode:true,skillRoot:newer.skillRoot,afterTurnStarted:()=>{throw step02.codeError('SYNTHETIC_AFTER_JOURNAL_CRASH');}}),/SYNTHETIC_AFTER_JOURNAL_CRASH/);newerClient.scenario.laterNewer=true;const recoveredNewer=await dispatcher.run({dispatchPath:path.join(newer.workspace,'step02_employee_dispatch.json'),workspace:newer.workspace,leaseRoot:path.join(root,'leases-newer'),client:newerClient,testMode:true,skillRoot:newer.skillRoot});assert.equal(recoveredNewer.audit.recovered_existing_turn,true);assert.equal(newerClient.starts,1);assert.equal(newerClient.waits,0);
  const heartbeatCase=await seed(root,'heartbeat'),heartbeatClient=new FakeClient(heartbeatCase.dispatch,candidate(heartbeatCase.dispatch),{waitDelay:100});let renewCalls=0;await expectCode(()=>dispatcher.run({dispatchPath:path.join(heartbeatCase.workspace,'step02_employee_dispatch.json'),workspace:heartbeatCase.workspace,leaseRoot:path.join(root,'leases-heartbeat'),client:heartbeatClient,testMode:true,skillRoot:heartbeatCase.skillRoot,leaseHeartbeatMs:20,renewLease:async()=>{renewCalls++;if(renewCalls>1)throw new Error('synthetic renew failure');}}),'STEP02_APP_LEASE_RENEWAL_FAILED');assert.equal(await fsp.stat(path.join(root,'leases-heartbeat',heartbeatCase.dispatch.employee.thread_id)).then(s=>s.isDirectory()),true);
  process.stdout.write(JSON.stringify({ok:true,status:'PASS_SYNTHETIC_FIXED_APP_DISPATCHER',verified:['all five exact threads read twice with pre-start CAS','active fourth employee and second-read mutation produce zero start','fixed identity and notLoaded resume','readOnly no-network start request','clean completion and exact readback','validated replay zero duplicate and cleans same-dispatch stale lease','atomic staged lease claim and empty pre-turn lease recovery','candidate/receipt/control/audit/response/journal byte bindings','turn error/wrong final/completed-error/missing-assistant fail closed','later newer turn and notification gap recover exact journal-known target','cross-project candidate rejected','turn accepted before journal crash recovers exact same turn with zero duplicate','heartbeat failure is typed and retains recovery lease','expired foreign lease with unknown turn retained and rejected','portable evidence and exact installed Skill tamper rejected','Bundle v2/install/parity/adoption/Krill runtime bindings read back'],real_mac_turn_started:false,provider_called:false,spend_requested:false,local_image_editing_requested:false})+'\n');
}finally{await fsp.rm(root,{recursive:true,force:true});}}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
