'use strict';

const assert=require('assert/strict');
const crypto=require('crypto');
const fsp=require('fs/promises');
const fs=require('fs');
const net=require('net');
const os=require('os');
const path=require('path');
const {spawn}=require('child_process');
const dag=require('./bridge/niannian_redraw_canonical_dag');
const {createLocalizationConfirmationService}=require('./bridge/niannian_localization_confirmation');
const {Step05ReferenceAuthority}=require('./bridge/niannian_step05_reference_authority');
const step03Runtime=require('./bridge/niannian_step03_runtime');

const hash=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
async function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.unref();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(error=>error?reject(error):resolve(port));});});}
async function start(dataRoot,port){const logs=[];const child=spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(port),DATA_DIR:dataRoot,NIANNIAN_VIDEO_BATCH_FIXTURE_MODE:'1',NIANNIAN_EXACT_STEP01_EVIDENCE_ROOT:path.join(__dirname,'data-local','step01-evidence','NN-20260715083045-8120F5','EP001'),NIANNIAN_MEDIA_PREFLIGHT:'off',NIANNIAN_STEP01_AUTO_EXECUTE:'off'},stdio:['ignore','pipe','pipe'],windowsHide:true});child.stdout.on('data',chunk=>logs.push(String(chunk)));child.stderr.on('data',chunk=>logs.push(String(chunk)));for(let i=0;i<180;i+=1){if(child.exitCode!==null)throw new Error('server_exited:'+logs.join(''));try{if((await fetch('http://127.0.0.1:'+port+'/api/health')).ok)return child;}catch{}await new Promise(resolve=>setTimeout(resolve,50));}throw new Error('server_timeout:'+logs.join(''));}
async function stop(child){if(!child||child.exitCode!==null)return;child.kill();await new Promise(resolve=>{child.once('exit',resolve);setTimeout(resolve,2000).unref();});}

(async()=>{
  const temp=await fsp.mkdtemp(path.join(os.tmpdir(),'niannian-step05-http-')),dataRoot=path.join(temp,'data'),projectId='NN-20260715083045-8120F5',owner='USR-STEP05-HTTP',token=crypto.randomBytes(32).toString('hex'),authority='analysis-1-0dc5c5d751592e9fd0656a81',sourceSha='a46f74392e2b3f7ec813b4eba5a0cd9756a7c30225e0033fd671d2cab21cd30c',sourceBytes=145897161,acceptance='b'.repeat(64),port=await freePort(),base='http://127.0.0.1:'+port;
  let child;
  try{
    await fsp.mkdir(dataRoot,{recursive:true});
    const canonical=dag.resolveCanonicalState({legacy:{step:'Step02'},authority_revision:authority,current_authority_revision:authority,input_contract:{S01_EVIDENCE:true},output_contract:{accepted:true,artifact_ledger_verified:true}});
    const project={id:projectId,ownerId:owner,name:'Step05 HTTP fixture',productionStatus:'step02_accepted',source:{originalName:'fixture.mp4',mimeType:'video/mp4',bytes:sourceBytes,sha256:sourceSha,storedPath:'fixture-only'},analysis:{status:'completed',runId:authority},step02:{status:'accepted',acceptance:{status:'accepted',downstream_consumable:true,sha256:acceptance}},canonical};
    await Promise.all([
      fsp.writeFile(path.join(dataRoot,'projects.json'),JSON.stringify([project])),
      fsp.writeFile(path.join(dataRoot,'users.json'),JSON.stringify([{id:owner,email:'step05-http@example.test',status:'active'}])),
      fsp.writeFile(path.join(dataRoot,'sessions.json'),JSON.stringify([{id:'session-step05-http',userId:owner,tokenHash:hash(token),createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()}])),
      fsp.writeFile(path.join(dataRoot,'script-projects.json'),'[]'),
    ]);
    const acceptedStep02={project_id:projectId,authority_revision:authority,acceptance_identity:acceptance,accepted:true,status:'accepted',artifact_ledger_verified:true,downstream_consumable:true};
    const localization=createLocalizationConfirmationService({root:path.join(dataRoot,'localization-confirmation')});
    const candidate=await localization.createCandidate({projectId,authorityRevision:authority,acceptedStep02,targetRegion:{code:'es-MX',label:'墨西哥'},projection:{character_relationship_adaptations:[],story_outline_zh:'最小首条视频。',localized_key_dialogue:[],replacements:{locations:[],currency:[],address_terms:[],cultural_context:[]},confirmation_items:[]},idempotencyKey:'step05-http-loc'});
    await localization.confirm({projectId,authorityRevision:authority,acceptedStep02,localizationRevision:candidate.candidate.localization_revision,ifMatch:candidate.etag,actor:owner});
    const localizationRevision=candidate.candidate.localization_revision;
    const seed=JSON.parse(await fsp.readFile(path.join(__dirname,'docs/agent-team/step05-reference-dual-track-20260727/fixtures/reference-authority.seed.json'),'utf8'));
    seed.project_id=projectId;seed.authority_revision=authority;seed.localization_revision=localizationRevision;
    for(const ref of seed.references){ref.project_id=projectId;ref.authority_revision=authority;ref.localization_revision=localizationRevision;}
    const planId='S03-es-MX-'+hash('step05-http-plan').slice(0,20),artifactBytes=await fsp.readFile(path.join(__dirname,'assets','home','niannian-hero-oil-paint-quiet-v1.png')),artifactSha=crypto.createHash('sha256').update(artifactBytes).digest('hex'),artifactId='ART-'+artifactSha.slice(0,24),ownerPlanRoot=path.join(dataRoot,'step03-runtime','v1','owners',hash(owner),'projects',projectId,'plans',planId),artifactKey='artifacts/'+artifactId+'.png';
    const planCore={schema_version:'niannian.step03_plan.v1',plan_id:planId,project_id:projectId,analysis_run_id:authority,source_sha256:sourceSha,source_bytes:sourceBytes,locale:'es-MX',created_at:'2026-07-27T00:00:00.000Z'},plan={...planCore,plan_sha256:step03Runtime.sha256(step03Runtime.canonical(planCore))},state={schema_version:'niannian.step03_state.v1',status:'episode_review',substep:'confirmation',characters:[],continuity_ledger:[],assets:[],groups:[{group_id:'G-001',sequence:1,revision:1,start_sec:0,end_sec:8,duration_sec:8,action_summary:'第一条最小可验证视频',dialogue_bindings:[{speaker:'女主',text:'开始'}],asset_dependencies:[],source_shot_ids:['S001']}],firstframes:[],tasks:[{task_id:'TASK-STEP05-MEDIA',type:'readonly_fixture',status:'accepted',artifact_id:artifactId,artifact_key:artifactKey,artifact_sha256:artifactSha,artifact_bytes:artifactBytes.length,artifact_mime:'image/png'}],updated_at:'2026-07-27T00:00:00.000Z'};
    await fsp.mkdir(path.join(ownerPlanRoot,'artifacts'),{recursive:true});await fsp.writeFile(path.join(ownerPlanRoot,'plan.json'),JSON.stringify(plan));await fsp.writeFile(path.join(ownerPlanRoot,'state.json'),JSON.stringify(state));await fsp.writeFile(path.join(ownerPlanRoot,...artifactKey.split('/')),artifactBytes);
    for(const ref of seed.references){ref.candidate.artifact_id=artifactId;ref.candidate.plan_id=planId;ref.readback={bytes:artifactBytes.length,content_type:'image/png'};ref.locked_prompt_lineage.prompt_sha=hash('prompt:'+ref.ref_key);}seed.step04_registry_revision='S04REG-'+hash('step05-http-registry').slice(0,24);seed.references.find(ref=>ref.ref_key==='FIRST-V01').candidate.content_sha=artifactSha;seed.references.find(ref=>ref.ref_key==='SUPPORT-HERO').candidate.content_sha=artifactSha;seed.references.find(ref=>ref.ref_key==='IDENTITY-HERO').candidate.content_sha='e'.repeat(64);
    const registryRoot=path.join(dataRoot,'step04-reference-registry');await fsp.mkdir(registryRoot,{recursive:true});await fsp.writeFile(path.join(registryRoot,hash(projectId)+'.json'),JSON.stringify(seed));
    child=await start(dataRoot,port);
    const headers={cookie:'niannian_session='+token,'X-Localization-Revision':localizationRevision};
    const missingRevision=await fetch(base+'/api/projects/'+projectId+'/step05/references',{headers:{cookie:headers.cookie}});assert.equal(missingRevision.status,409);
    const initial=await fetch(base+'/api/projects/'+projectId+'/step05/references',{headers}),etag=initial.headers.get('etag'),initialBody=await initial.json();assert.equal(initial.status,200);assert.ok(etag);assert.equal(initialBody.references.counts.video_reference_pending,2);assert.equal(initialBody.references.support_assets.system_checked.length,1);assert.equal(initialBody.references.support_assets.system_checked[0].status,'系统已检查');
    const publicText=JSON.stringify(initialBody);for(const forbidden of ['content_sha','authority_revision','localization_revision','authority_event_id','locked_prompt','provider','receipt','internal_path','signature='])assert(!publicText.toLowerCase().includes(forbidden));
    const candidateGet=await fetch(base+'/api/projects/'+projectId+'/step05/references/FIRST-V01/candidate',{headers}),candidateGetBytes=Buffer.from(await candidateGet.arrayBuffer());assert.equal(candidateGet.status,200,candidateGetBytes.toString('utf8'));assert.deepEqual(candidateGetBytes,artifactBytes);
    const candidateHead=await fetch(base+'/api/projects/'+projectId+'/step05/references/FIRST-V01/candidate',{method:'HEAD',headers});assert.equal(candidateHead.status,200);assert.equal(candidateHead.headers.get('content-type'),'image/png');assert.equal(candidateHead.headers.get('content-length'),String(artifactBytes.length));assert.equal(candidateHead.headers.get('cache-control'),'private, max-age=31536000, immutable');assert.match(candidateHead.headers.get('etag'),/^"step05-candidate-[A-Za-z0-9_-]+"$/);assert.notEqual(candidateHead.headers.get('etag'),'"'+artifactSha+'"');assert.equal(candidateHead.headers.get('x-content-sha256'),null);
    const candidateMismatch=await fetch(base+'/api/projects/'+projectId+'/step05/references/IDENTITY-HERO/candidate',{method:'HEAD',headers});assert.equal(candidateMismatch.status,409);assert.equal(candidateMismatch.headers.get('cache-control'),'private, no-store');assert.equal(candidateMismatch.headers.get('etag'),null);
    const jobsRoot=path.join(dataRoot,'jobs'),jobsBeforeGate=(await fsp.readdir(jobsRoot,{recursive:true}).catch(error=>error.code==='ENOENT'?[]:Promise.reject(error))).sort(),projectsBeforeGate=await fsp.readFile(path.join(dataRoot,'projects.json'),'utf8');
    const prepareBlocked=await fetch(base+'/api/projects/'+projectId+'/source-video-execution/V01/prepare',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:'{}'}),prepareBlockedBody=await prepareBlocked.json();assert.equal(prepareBlocked.status,409);assert.match(prepareBlockedBody.error,/尚未全部确认|版本已更新/);
    const submitBlocked=await fetch(base+'/api/projects/'+projectId+'/source-video-execution/V01/submit-real',{method:'POST',headers:{...headers,'Content-Type':'application/json',Origin:base,'Sec-Fetch-Site':'same-origin'},body:'{}'}),submitBlockedBody=await submitBlocked.json();assert.equal(submitBlocked.status,409);assert.match(submitBlockedBody.error,/尚未全部确认|版本已更新/);
    assert.deepEqual((await fsp.readdir(jobsRoot,{recursive:true}).catch(error=>error.code==='ENOENT'?[]:Promise.reject(error))).sort(),jobsBeforeGate,'blocked prepare/submit must not create job state');assert.equal(await fsp.readFile(path.join(dataRoot,'projects.json'),'utf8'),projectsBeforeGate,'blocked prepare/submit must not mutate the project');
    for(const blockedText of [JSON.stringify(prepareBlockedBody),JSON.stringify(submitBlockedBody)])for(const forbidden of ['provider','receipt','sha','path','code','task'])assert(!blockedText.toLowerCase().includes(forbidden));
    const blocked=await fetch(base+'/api/projects/'+projectId+'/step05/video-gate/provider_submit',{method:'POST',headers});assert.equal(blocked.status,409);
    const decisions=initialBody.references.video_reference_cards.map(card=>({ref_key:card.ref_key,decision:'pass'}));
    const noMatch=await fetch(base+'/api/projects/'+projectId+'/step05/references/confirm-batch',{method:'POST',headers:{...headers,'Content-Type':'application/json','Idempotency-Key':'batch-no-match'},body:JSON.stringify({decisions})});assert.equal(noMatch.status,428);
    const partial=await fetch(base+'/api/projects/'+projectId+'/step05/references/confirm-batch',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':etag,'Idempotency-Key':'batch-partial'},body:JSON.stringify({decisions:decisions.slice(0,1)})});assert.equal(partial.status,409);
    const stale=await fetch(base+'/api/projects/'+projectId+'/step05/references/confirm-batch',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':'"stale"','Idempotency-Key':'batch-stale'},body:JSON.stringify({decisions})});assert.equal(stale.status,412);
    const confirmed=await fetch(base+'/api/projects/'+projectId+'/step05/references/confirm-batch',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':etag,'Idempotency-Key':'batch-confirm'},body:JSON.stringify({decisions})}),confirmedBody=await confirmed.json(),confirmedEtag=confirmed.headers.get('etag');assert.equal(confirmed.status,200);assert.equal(confirmedBody.references.status,'视频参考图已确认');assert.equal(confirmedBody.references.video_references_confirmed,true);assert.equal('video_task_spec_locked' in confirmedBody.references,false);
    const replay=await fetch(base+'/api/projects/'+projectId+'/step05/references/confirm-batch',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':etag,'Idempotency-Key':'batch-confirm'},body:JSON.stringify({decisions})});assert.equal(replay.status,200);assert.equal((await replay.json()).result.idempotent,true);
    const allowed=await fetch(base+'/api/projects/'+projectId+'/step05/video-gate/provider_submit',{method:'POST',headers}),allowedBody=await allowed.json();assert.equal(allowed.status,200);assert.equal(allowedBody.gate_ready,true);assert.equal(allowedBody.provider_action_performed,false);
    const batchPlan=await fetch(base+'/api/projects/'+projectId+'/video-batches/current',{headers}),batchBody=await batchPlan.json(),batchEtag=batchPlan.headers.get('etag');assert.equal(batchPlan.status,200,JSON.stringify(batchBody));assert.match(batchEtag,/^".+"$/);assert.equal(batchBody.plan.task_count,1);assert.equal(batchBody.plan.total_duration_seconds,8);assert.equal(batchBody.preflight.status,'pass');assert.equal(batchBody.preflight.submit_allowed,false);assert.equal(batchBody.submit_allowed,false);assert.equal(batchBody.real_provider_submit,false);assert.equal(batchPlan.headers.get('cache-control').includes('no-store'),true);
    const batchMissingMatch=await fetch(base+'/api/projects/'+projectId+'/video-batches/current/confirm',{method:'POST',headers:{...headers,'Content-Type':'application/json','Idempotency-Key':'video-batch-missing-match'},body:JSON.stringify({confirm_generate:true,quote_revision:batchBody.quote.revision,confirmed_max_cost:{currency:batchBody.quote.currency,minor_units:batchBody.quote.max_cost_minor_units}})});assert.equal(batchMissingMatch.status,412);
    const confirmPayload={confirm_generate:true,quote_revision:batchBody.quote.revision,confirmed_max_cost:{currency:batchBody.quote.currency,minor_units:batchBody.quote.max_cost_minor_units}};
    const batchConfirmed=await fetch(base+'/api/projects/'+projectId+'/video-batches/current/confirm',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':batchEtag,'Idempotency-Key':'video-batch-confirm-1'},body:JSON.stringify(confirmPayload)}),batchConfirmedBody=await batchConfirmed.json();assert.equal(batchConfirmed.status,200,JSON.stringify(batchConfirmedBody));assert.equal(batchConfirmedBody.submit_allowed,true);assert.equal(batchConfirmedBody.state,'等待提交/处理中');assert.equal(batchConfirmedBody.real_provider_submit,false);
    const batchReplay=await fetch(base+'/api/projects/'+projectId+'/video-batches/current/confirm',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':batchEtag,'Idempotency-Key':'video-batch-confirm-1'},body:JSON.stringify(confirmPayload)});assert.equal(batchReplay.status,200);assert.equal((await batchReplay.json()).submit_allowed,true);
    await stop(child);child=null;child=await start(dataRoot,port);
    const batchAfterRestart=await fetch(base+'/api/projects/'+projectId+'/video-batches/current',{headers}),batchAfterRestartBody=await batchAfterRestart.json();assert.equal(batchAfterRestart.status,200,JSON.stringify(batchAfterRestartBody));assert.equal(batchAfterRestartBody.submit_allowed,true);assert.equal(batchAfterRestartBody.state,'等待提交/处理中');
    const rerollRequest=await fetch(base+'/api/projects/'+projectId+'/step05/references/FIRST-V01/reroll',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':confirmedEtag,'Idempotency-Key':'reroll-request-1'},body:JSON.stringify({issue_category:'构图不一致',note:'返回生成区重做'})});assert.equal(rerollRequest.status,202);assert.equal((await rerollRequest.json()).references.video_references_confirmed,true,'request alone must not invalidate unchanged exact candidate');let actionEtag=rerollRequest.headers.get('etag');
    for(const action of ['reroll','return_upstream','remove']){const supportAction=await fetch(base+'/api/projects/'+projectId+'/step05/references/SUPPORT-HERO/action',{method:'POST',headers:{...headers,'Content-Type':'application/json','If-Match':actionEtag,'Idempotency-Key':'support-'+action},body:JSON.stringify({action,note:'HTTP fixture action'})});assert.equal(supportAction.status,202,action);actionEtag=supportAction.headers.get('etag');}
    await stop(child);child=null;
    const stateFile=path.join(dataRoot,'step05-reference-authority','v1',hash(projectId),hash(authority),hash(localizationRevision),'state.json');assert(fs.existsSync(stateFile));
    const store=new Step05ReferenceAuthority({stateFile});store.reroll({ifMatch:store.etag(),ref_key:'FIRST-V01',candidate_revision:'C-2',content_sha:'d'.repeat(64),authority_event_id:'AE-FIRST-2'});assert.equal(store.gateStatus().confirmed_count,1);
    child=await start(dataRoot,port);
    const restoredBatch=await fetch(base+'/api/projects/'+projectId+'/video-batches/current',{headers}),restoredBatchBody=await restoredBatch.json();assert.equal(restoredBatch.status,409,'rerolled ref must invalidate exact batch before any stale authorization can be projected');assert.equal(restoredBatchBody.code,'VIDEO_BATCH_REQUEST_FAILED');
    const restored=await fetch(base+'/api/projects/'+projectId+'/step05/references',{headers}),restoredBody=await restored.json();assert.equal(restored.status,200);assert.equal(restoredBody.references.counts.video_reference_pending,1);assert.equal(restoredBody.references.video_reference_cards.find(card=>card.ref_key==='IDENTITY-HERO').decision,'通过');
    const blockedAfterReroll=await fetch(base+'/api/projects/'+projectId+'/step05/video-gate/provider_preflight',{method:'POST',headers});assert.equal(blockedAfterReroll.status,409);
    console.log(JSON.stringify({status:'PASS',real_http:true,strong_etag:true,atomic_batch:true,idempotent:true,local_reroll_invalidation:true,support_actions:['reroll','return_upstream','remove'],source_prepare_submit_blocked_before_side_effect:true,candidate_media_200_exact_readback:true,candidate_media_mismatch_fail_closed:true,candidate_media_opaque_etag:true,server_restart_recovery:true,provider_calls:0}));
  }finally{await stop(child);await fsp.rm(temp,{recursive:true,force:true});}
})().catch(error=>{console.error(error.stack||error);process.exit(1);});
