'use strict';

const assert=require('assert');
const crypto=require('crypto');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const transport=require('./bridge/niannian_redraw_step02_mac_app_phase_transport');
const carrier=require('./bridge/niannian_redraw_step02_windows_mac_phase_carrier');
const step02=require('./bridge/niannian_redraw_step02_vertical');
const {THREADS}=require('./bridge/mac_codex_app_employee_bootstrap');

const sha256=value=>crypto.createHash('sha256').update(value).digest('hex');
async function writeJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});await fsp.writeFile(filePath,JSON.stringify(value,null,2)+'\n');}
async function evidence(filePath){const bytes=await fsp.readFile(filePath);return {relative_path:path.basename(filePath),sha256:sha256(bytes),bytes:bytes.length};}
async function build(root,suffix='base',mutate={}){
  const job=path.join(root,suffix),stepRoot=path.join(job,'step02'),step01=path.join(job,'step01-workspace');await fsp.mkdir(step01,{recursive:true});
  const names=['ffprobe.json','minute_chunks.json','native/frame001.png','transnet.json','supplement.json','audio.wav','audio_events.json','mimo_receipt.json','aligner_receipt.json','ocr_ledger.json','validation.json'];const artifacts=[];
  for(const name of names){const exact=path.join(step01,name);await fsp.mkdir(path.dirname(exact),{recursive:true});await fsp.writeFile(exact,Buffer.from('exact-step01-evidence:'+name));const item=await evidence(exact);item.relative_path=name;artifacts.push(item);}
  if(mutate.duplicate)artifacts.push({...artifacts[0]});if(mutate.casefold)artifacts.push({...artifacts[0],relative_path:'FFPROBE.JSON'});if(mutate.escape)artifacts[0]={...artifacts[0],relative_path:'../outside.json'};if(mutate.missing)await fsp.rm(path.join(step01,'audio.wav'));if(mutate.tamper)await fsp.writeFile(path.join(step01,'transnet.json'),'tampered');
  if(mutate.parentJunction){const outside=path.join(root,'outside-junction');await fsp.mkdir(outside,{recursive:true});await fsp.writeFile(path.join(outside,'frame.png'),'junction-frame');const p=await evidence(path.join(outside,'frame.png'));artifacts.push({...p,relative_path:'linked/frame.png'});await fsp.symlink(outside,path.join(step01,'linked'),'junction');}
  const manifest={schema_version:'step01_evidence_manifest_v1',status:'verified',downstream_consumable:true,source_sha256:sha256('source-'+suffix),source_bytes:123,artifacts};await writeJson(path.join(step01,'step01_evidence_manifest.json'),manifest);const manifestEv=await transport.fileEvidence(path.join(step01,'step01_evidence_manifest.json'));
  await writeJson(path.join(step01,'step01_employee_receipt.json'),{schema_version:'niannian_redraw_step01_mac_employee_receipt_v2',step01_verified:true});await writeJson(path.join(step01,'step01_control_receipt.json'),{schema_version:'niannian_redraw_step01_mac_app_control_receipt_v2'});const receiptEv=await transport.fileEvidence(path.join(step01,'step01_employee_receipt.json')),controlEv=await transport.fileEvidence(path.join(step01,'step01_control_receipt.json'));
  const authority={schema_version:step02.SCHEMAS.authority,status:'verified',transaction_id:'txn-'+suffix,project_id:'NN-TRANSPORT-'+suffix.toUpperCase(),job_id:'job-'+suffix,owner_id:'owner-'+suffix,source:{sha256:manifest.source_sha256,bytes:123},rights_authority:{event_id:'rights-'+suffix,sha256:sha256('rights-'+suffix),status:'confirmed',revoked:false},settings_version:2,step01:{manifest:{exact_path:path.join(step01,'step01_evidence_manifest.json'),...manifestEv},receipt:{exact_path:path.join(step01,'step01_employee_receipt.json'),...receiptEv},control:{exact_path:path.join(step01,'step01_control_receipt.json'),...controlEv}},source_media_contract:{duration_seconds:10,visual_duration_seconds:9.9},...step02.falseEffects()};
  await writeJson(path.join(stepRoot,'upstream_authority_snapshot.json'),authority);const authorityEv=await transport.fileEvidence(path.join(stepRoot,'upstream_authority_snapshot.json'));const employee=THREADS[0];const dispatch={schema_version:step02.SCHEMAS.dispatch,status:'prepared',test_only:false,execution_mode:'fixed_existing_mac_app_candidate_only',transaction_id:authority.transaction_id,dispatch_id:'dispatch-'+suffix,phase_key:'phase-'+suffix,project_id:authority.project_id,job_id:authority.job_id,owner_id:authority.owner_id,owner_action_event_id:'owner-action-'+suffix,source_sha256:authority.source.sha256,rights_authority_sha256:authority.rights_authority.sha256,step01_manifest_sha256:manifestEv.sha256,upstream_authority_sha256:authorityEv.sha256,settings_version:2,employee:{...employee,project_root:'/Users/lsb/AI-Brain/niannian-ai-canonical-local'},transport:{fixed_app_required:true,thread_read_before_start:true,active_turn_reject:true,cli_fallback_allowed:false,ephemeral_thread_allowed:false,legacy_latest_lookup_allowed:false},...step02.falseEffects()};const transaction={schema_version:step02.SCHEMAS.transaction,status:'prepared',test_only:false,transaction_id:dispatch.transaction_id,project_id:dispatch.project_id,job_id:dispatch.job_id,owner_id:dispatch.owner_id,bindings:{upstream_authority_sha256:authorityEv.sha256,step01_manifest_sha256:manifestEv.sha256},...step02.falseEffects()};await writeJson(path.join(stepRoot,'transaction_intent.json'),transaction);await writeJson(path.join(stepRoot,'step02_employee_dispatch.json'),dispatch);return {job,stepRoot,step01,authority,dispatch};
}
async function expectExportFailure(root,name,mutate,codePart){const current=await build(root,name,mutate);await assert.rejects(()=>transport.exportWindowsPhase({step02Root:current.stepRoot,packageRoot:path.join(current.job,'package')}),error=>String(error.code||error.message).includes(codePart));}
async function writeReturn(workspace,dispatch){
  const candidate={schema_version:step02.SCHEMAS.candidate,status:'candidate',downstream_consumable:false,test_only:false,fixture_evidence:false,transaction_id:dispatch.transaction_id,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key,project_id:dispatch.project_id,job_id:dispatch.job_id,source_sha256:dispatch.source_sha256,rights_authority_sha256:dispatch.rights_authority_sha256,step01_manifest_sha256:dispatch.step01_manifest_sha256,settings_version:2,sourceRows:[{shot_id:'S001',source_start_sec:0,source_end_sec:1,visual_composition:'角色站在门口。',blocking_movement:'角色向左一步。'}],dialogueBindings:[],visualFactCards:[],textEvidence:[],assetCandidates:[],hardSceneCandidates:[],rejectedEvidence:[],blockers:[],...step02.falseEffects()};
  await writeJson(path.join(workspace,'step02_source_truth_candidate.json'),candidate);const candidateEv=await transport.fileEvidence(path.join(workspace,'step02_source_truth_candidate.json'));
  const responseText=JSON.stringify(candidate),responseBytes=Buffer.from(responseText);await writeJson(path.join(workspace,'step02_app_server_response.json'),{schema_version:'niannian_redraw_step02_app_server_response_v1',thread_id:dispatch.employee.thread_id,turn_id:'turn-1',sha256:sha256(responseBytes),bytes:responseBytes.length,text:responseText});const responseEv=await transport.fileEvidence(path.join(workspace,'step02_app_server_response.json'));
  const employeeModelChannel={channel_id:'krill_codex_custom_provider_v1',used:true,network_used:true,media_provider_authority_granted:false};const common={transaction_id:dispatch.transaction_id,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key,project_id:dispatch.project_id,job_id:dispatch.job_id,source_sha256:dispatch.source_sha256,rights_authority_sha256:dispatch.rights_authority_sha256,step01_manifest_sha256:dispatch.step01_manifest_sha256,upstream_authority_sha256:dispatch.upstream_authority_sha256,settings_version:2,owner_action_event_id:dispatch.owner_action_event_id,employee:dispatch.employee,employee_model_channel:employeeModelChannel,completion_event:{method:'turn/completed',thread_id:dispatch.employee.thread_id,turn_id:'turn-1',status:'completed',error:null},completion_provenance:'fixed_mac_app_server_readback_v1',test_only:false,fixture_evidence:false,...step02.falseEffects()};
  const receipt={schema_version:step02.SCHEMAS.receipt,status:'candidate',downstream_consumable:false,...common,candidate:{relative_path:'step02_source_truth_candidate.json',...candidateEv},app_server_response:{sha256:sha256(responseBytes),bytes:responseBytes.length}},control={schema_version:step02.SCHEMAS.control,status:'completed_candidate_only',...common,app_server_sequence:{thread_read_before_start:true,turn_start:true,turn_completed:true,thread_readback:true},cli_fallback_used:false,ephemeral_thread_used:false,ssh_employee_used:false,provider_used:false};await writeJson(path.join(workspace,'step02_employee_receipt.json'),receipt);await writeJson(path.join(workspace,'step02_control_receipt.json'),control);const receiptEv=await transport.fileEvidence(path.join(workspace,'step02_employee_receipt.json')),controlEv=await transport.fileEvidence(path.join(workspace,'step02_control_receipt.json'));
  const governance=JSON.parse(await fsp.readFile(path.join(workspace,'step02_runtime_governance.json'),'utf8')),governanceEv=await transport.fileEvidence(path.join(workspace,'step02_runtime_governance.json'));const runtime={governance_sha256:governanceEv.sha256,governance_bytes:governanceEv.bytes,bundle_id:governance.bundle_id,bundle_manifest_sha256:governance.bundle_manifest_sha256,install_receipt_sha256:governance.receipts.install.sha256,parity_receipt_sha256:governance.receipts.parity.sha256,adoption_manifest_sha256:governance.receipts.adoption.sha256,skills:governance.skills,test_only_runtime:true};
  const audit={schema_version:step02.SCHEMAS.appAudit,status:'completed_readback_verified',dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key,transaction_id:dispatch.transaction_id,project_id:dispatch.project_id,owner_action_event_id:dispatch.owner_action_event_id,employee_thread_id:dispatch.employee.thread_id,employee_model_channel:employeeModelChannel,turn_start_request:{method:'turn/start',sha256:sha256('request'),bytes:7,cwd:'/Users/lsb/AI-Brain/niannian-ai-canonical-local',sandbox_policy:'readOnly',network_access:false},turn_start_response:{turn_id:'turn-1'},completion_event:common.completion_event,thread_readback:{thread_id:dispatch.employee.thread_id,exact_turn_id:'turn-1',exact_turn_status:'completed',exact_turn_error:null,exact_turn_assistant_message_count:1,latest_completed_assistant_turn_id:'turn-1',latest_turn_status:'completed',latest_turn_error:null},assistant_response:{sha256:sha256(responseBytes),bytes:responseBytes.length,evidence_sha256:responseEv.sha256,evidence_bytes:responseEv.bytes},candidate:candidateEv,employee_receipt:receiptEv,control_receipt:controlEv,runtime_governance:runtime,test_only:false,fixture_evidence:false,...step02.falseEffects()};await writeJson(path.join(workspace,'step02_app_server_audit.json'),audit);
}
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'step02-transport-'));try{const current=await build(root,'pass');const packageRoot=path.join(current.job,'package'),exported=await transport.exportWindowsPhase({step02Root:current.stepRoot,packageRoot});const replayExport=await transport.exportWindowsPhase({step02Root:current.stepRoot,packageRoot});assert.equal(replayExport.evidence.sha256,exported.evidence.sha256);const index=JSON.parse(await fsp.readFile(path.join(packageRoot,'step02_portable_evidence_index.json'),'utf8'));assert.equal(index.artifact_count,11);for(const role of ['source_ffprobe','minute_chunks','native_frame','accepted_transnet_shots','transnet_start_mid_end_supplement','source_audio_wav','audio_event_ledger','mimo_transcript','forced_aligner','paddle_ocr','strict_validation'])assert(index.entries.some(item=>item.role===role));for(const name of ['native/frame001.png','audio.wav','mimo_receipt.json','aligner_receipt.json','ocr_ledger.json','transnet.json'])assert(await fsp.stat(path.join(packageRoot,'upstream','evidence',name)).then(s=>s.isFile()));const governance=JSON.parse(await fsp.readFile(path.join(packageRoot,'step02_runtime_governance.json'),'utf8'));assert.equal(governance.bundle_id,'niannian-mac-production-skills-v2');assert.equal(governance.managed_file_count,127);assert.equal(governance.employee_model_channel.used,true);assert.equal(governance.employee_model_channel.media_provider_authority_granted,false);assert.deepEqual(governance.skills.map(item=>item.relative_path),['mx-shortdrama-00-router/SKILL.md','mx-shortdrama-02-source-timeline/SKILL.md']);
  const workspace=path.join(current.job,'mac-workspace');const imported=await transport.importDispatchToMac({packageRoot:path.join(current.job,'package'),expectedManifestSha256:exported.evidence.sha256,workspacePath:workspace});assert.equal(imported.status,'imported');assert.equal((await transport.importDispatchToMac({packageRoot:path.join(current.job,'package'),expectedManifestSha256:exported.evidence.sha256,workspacePath:workspace})).status,'replayed');await assert.rejects(()=>transport.finalizeMacReturn({workspacePath:workspace}),error=>['STEP02_TRANSPORT_FILE_NOT_REGULAR','STEP02_TRANSPORT_SYMLINK_REJECTED'].includes(error.code));await writeReturn(workspace,current.dispatch);const finalized=await transport.finalizeMacReturn({workspacePath:workspace});const windowsReturn=path.join(current.stepRoot,'returns',current.dispatch.phase_key);await transport.importMacReturnToWindows({returnRoot:workspace,expectedManifestSha256:finalized.evidence.sha256,windowsReturnRoot:windowsReturn});const trusted=await carrier.createTrustedReceipt({importRoot:windowsReturn,dispatch:current.dispatch,testMode:true});assert.equal(trusted.value.test_only,true);assert.equal(trusted.value.fixture_evidence,true);assert.equal(trusted.value.windows_independent_hash_readback,true);
  await expectExportFailure(root,'tamper',{tamper:true},'TAMPERED');await expectExportFailure(root,'missing',{missing:true},'NOT_REGULAR');await expectExportFailure(root,'dup',{duplicate:true},'DUPLICATE');await expectExportFailure(root,'case',{casefold:true},'CASEFOLD');await expectExportFailure(root,'escape',{escape:true},'RELATIVE_PATH');await expectExportFailure(root,'junction',{parentJunction:true},'SYMLINK');
  const returnTamper=await build(root,'returntamper');const exp2=await transport.exportWindowsPhase({step02Root:returnTamper.stepRoot,packageRoot:path.join(returnTamper.job,'package')});const ws2=path.join(returnTamper.job,'mac');await transport.importDispatchToMac({packageRoot:path.join(returnTamper.job,'package'),expectedManifestSha256:exp2.evidence.sha256,workspacePath:ws2});await writeReturn(ws2,returnTamper.dispatch);const fin2=await transport.finalizeMacReturn({workspacePath:ws2});await fsp.writeFile(path.join(ws2,'step02_source_truth_candidate.json'),'{}\n');await assert.rejects(()=>transport.importMacReturnToWindows({returnRoot:ws2,expectedManifestSha256:fin2.evidence.sha256,windowsReturnRoot:path.join(returnTamper.stepRoot,'returns',returnTamper.dispatch.phase_key)}),/STEP02_TRANSPORT_FILE_TAMPERED/);
  const treeTamper=await build(root,'treetamper'),treePackage=path.join(treeTamper.job,'package');await transport.exportWindowsPhase({step02Root:treeTamper.stepRoot,packageRoot:treePackage});await fsp.appendFile(path.join(treePackage,'upstream','evidence','audio.wav'),'tamper');await assert.rejects(()=>transport.exportWindowsPhase({step02Root:treeTamper.stepRoot,packageRoot:treePackage}),/STEP02_TRANSPORT_FILE_TAMPERED/);
  const originalMethods={running:step02.markCarrierRunning,blocked:step02.markCarrierBlocked,reconcile:step02.reconcileReturn,review:step02.loadReview};let blockedEvidence=null;try{step02.markCarrierRunning=async()=>({status:'carrier_running'});step02.markCarrierBlocked=async args=>{blockedEvidence=args.blocker;return {status:'step02_blocked_resource'};};step02.reconcileReturn=async()=>({status:'candidate_return_ready',step04_ready:false});step02.loadReview=async()=>({status:'candidate_return_ready',step04_ready:false});const integrated=await build(root,'carrier'),project={id:integrated.dispatch.project_id,ownerId:integrated.dispatch.owner_id};const remoteWorkspace=path.join(integrated.job,'fake-mac');const carried=await carrier.runCarrier({project,jobRoot:integrated.job,ownerId:project.ownerId,ownerActionEventId:integrated.dispatch.owner_action_event_id,testMode:true,remoteExecute:async({packageRoot,manifestSha256})=>{await transport.importDispatchToMac({packageRoot,expectedManifestSha256:manifestSha256,workspacePath:remoteWorkspace});await writeReturn(remoteWorkspace,integrated.dispatch);const finalized=await transport.finalizeMacReturn({workspacePath:remoteWorkspace});return{returnRoot:remoteWorkspace,manifestSha256:finalized.evidence.sha256,remote:false};}});assert.equal(carried.status,'candidate_return_ready');assert.equal(carried.receipt.test_only,true);assert.equal(carried.review.step04_ready,false);const replay=await carrier.runCarrier({project,jobRoot:integrated.job,ownerId:project.ownerId,ownerActionEventId:integrated.dispatch.owner_action_event_id,testMode:true,remoteExecute:async()=>{throw new Error('must not rerun');}});assert.equal(replay.status,'replayed');const failed=await build(root,'carrierfail'),failedProject={id:failed.dispatch.project_id,ownerId:failed.dispatch.owner_id};await assert.rejects(()=>carrier.runCarrier({project:failedProject,jobRoot:failed.job,ownerId:failedProject.ownerId,ownerActionEventId:failed.dispatch.owner_action_event_id,testMode:true,remoteExecute:async()=>{throw step02.codeError('STEP02_CARRIER_TIMEOUT');}}),/STEP02_CARRIER_TIMEOUT/);const checkpoint=JSON.parse(await fsp.readFile(path.join(failed.stepRoot,'step02_carrier_checkpoint.json'),'utf8'));assert.equal(checkpoint.code,'STEP02_CARRIER_TIMEOUT');assert.equal(checkpoint.class,'infrastructure');assert.equal(blockedEvidence.code,'STEP02_CARRIER_TIMEOUT');}finally{step02.markCarrierRunning=originalMethods.running;step02.markCarrierBlocked=originalMethods.blocked;step02.reconcileReturn=originalMethods.reconcile;step02.loadReview=originalMethods.review;}
  process.stdout.write(JSON.stringify({ok:true,status:'PASS_SYNTHETIC_STEP02_PHASE_TRANSPORT',verified:['manifest-declared full Step01 evidence closure exported','portable index includes frame/audio/Mimo/ForcedAligner/Paddle/TransNet/validation bytes','Bundle v2/install/parity/adoption/exact two Skill/Krill boundary bound','deterministic export and destination full-tree replay verification','atomic Mac import and replay','partial return rejected','atomic Windows return import','Windows carrier receipt independently rehashes return','carrier replay zero remote execution and candidate never auto-accepted','typed timeout blocker and recoverable checkpoint','missing/tamper/duplicate/casefold/root escape/parent junction rejected','return tamper rejected'],real_mac_turn_started:false,source_001_read:false,provider_called:false,spend_requested:false,local_image_editing_requested:false})+'\n');}finally{await fsp.rm(root,{recursive:true,force:true});}}
if(require.main===module)main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
module.exports={build,writeReturn};
