'use strict';
const assert=require('assert'),fsp=require('fs').promises,os=require('os'),path=require('path');
const release=require('./bridge/niannian_mac_bridge_release'),installer=require('./bridge/install_mac_bridge_release');
async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'niannian-bridge-install-'));process.env.NIANNIAN_MAC_BRIDGE_INSTALL_TEST_MODE='1';try{const bundle=await release.buildReleaseBundle({sourceRoot:__dirname,bundleRoot:path.join(root,'bundle')});for(const file of release.BRIDGE_FILE_ALLOWLIST){const target=path.join(root,...file.split('/'));await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,'old-'+file);}
const receipt=await installer.installBridgeRelease({testMode:true,projectRoot:root,bundleRoot:bundle.bundle_root,receiptPath:path.join(root,'receipt.json')});assert.equal(receipt.status,'installed_verified');const state=await release.readInstalledBridgeRelease({projectRoot:root});assert.equal(state.manifest_sha256,bundle.manifest_sha256);const first=release.BRIDGE_FILE_ALLOWLIST[0];assert.notEqual(await fsp.readFile(path.join(root,...first.split('/')),'utf8'),'old-'+first);
if(process.platform!=='win32')assert.equal(await fsp.stat(path.join(root,'.local','bin','ai-brain-mac-relay-gateway.sh')).then(item=>item.mode&0o777),0o700);else assert.equal(await fsp.stat(path.join(root,'.local','bin','ai-brain-mac-relay-gateway.sh')).then(item=>item.isFile()),true);
for(const file of release.BRIDGE_FILE_ALLOWLIST)await fsp.writeFile(path.join(root,...file.split('/')),'rollback-'+file);await assert.rejects(()=>installer.installBridgeRelease({testMode:true,projectRoot:root,bundleRoot:bundle.bundle_root,receiptPath:path.join(root,'receipt-rollback.json'),failAfter:2}),/test_failure/);assert.equal(await fsp.readFile(path.join(root,...first.split('/')),'utf8'),'rollback-'+first);
await fsp.appendFile(path.join(bundle.bundle_root,...first.split('/')),'tamper');const before=await fsp.readFile(path.join(root,...first.split('/')),'utf8');await assert.rejects(()=>installer.installBridgeRelease({testMode:true,projectRoot:root,bundleRoot:bundle.bundle_root,receiptPath:path.join(root,'receipt2.json')}),/hash_mismatch/);assert.equal(await fsp.readFile(path.join(root,...first.split('/')),'utf8'),before);
}finally{delete process.env.NIANNIAN_MAC_BRIDGE_INSTALL_TEST_MODE;await fsp.rm(root,{recursive:true,force:true});}process.stdout.write(JSON.stringify({ok:true,verified:['fixed local install contract','verified installed state','transaction rollback restores previous files','tampered bundle rejected before replace']})+'\n');}main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
