'use strict';

const assert=require('assert');
const events=require('events');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const {PROJECT_ROOT,THREADS}=require('./bridge/mac_codex_app_employee_bootstrap');
const compact=require('./bridge/mac_codex_app_employee01_compaction');

class FakeClient extends events.EventEmitter{
  constructor(options={}){super();this.options=options;this.resumed=false;this.compactStarts=0;this.reads=0;this.compactTurnId='compact-turn-exact';this.turns=new Map(THREADS.map(item=>[item.thread_id,[{id:'anchor-'+item.employee,status:'completed',error:null,items:[{type:'agentMessage',text:'historical'}]}]]));}
  thread(fixed){this.reads+=1;let title=fixed.title;if(this.options.wrongIdentity&&fixed.employee==='01')title='Wrong Employee';const turns=[...(this.turns.get(fixed.thread_id)||[])];if(this.options.casChange&&this.resumed&&fixed.employee==='02'&&!turns.some(item=>item.id==='external-cas'))turns.push({id:'external-cas',status:'completed',error:null,items:[]});const notLoaded=fixed.employee!=='01'||!this.resumed;return{id:fixed.thread_id,name:title,cwd:PROJECT_ROOT,status:{type:notLoaded?'notLoaded':'idle'},turns};}
  async request(method,params){
    if(method==='thread/read'){const fixed=THREADS.find(item=>item.thread_id===params.threadId);assert(fixed);return{thread:this.thread(fixed)};}
    if(method==='thread/resume'){assert.equal(params.threadId,compact.EMPLOYEE01_THREAD_ID);assert.equal(params.modelProvider,'openai');assert.equal(params.model,'gpt-native-default');this.resumed=true;return{};}
    if(method==='thread/compact/start'){assert.deepEqual(params,{threadId:compact.EMPLOYEE01_THREAD_ID});this.compactStarts+=1;if(this.options.noNotification)return{};const turns=this.turns.get(compact.EMPLOYEE01_THREAD_ID);turns.push({id:this.compactTurnId,status:this.options.failedCompact?'failed':'completed',error:this.options.failedCompact?{message:'synthetic compact failure'}:null,items:[{type:this.options.pollOnlyCompaction?'contextCompaction':'compaction'}]});if(!this.options.pollOnlyCompaction)setImmediate(()=>this.emit('notification',this.options.itemCompleted?{method:'item/completed',params:{threadId:compact.EMPLOYEE01_THREAD_ID,turnId:this.compactTurnId,item:{id:'context-item-exact',type:'contextCompaction'},completedAtMs:Date.now()}}:{method:'thread/compacted',params:{threadId:compact.EMPLOYEE01_THREAD_ID,turnId:this.compactTurnId}}));return{};}
    throw new Error('unexpected_method:'+method);
  }
}

async function main(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),'employee01-compact-'));try{
  const auth={provider_config_id:'openai',default_model:'gpt-native-default',raw_auth_read:false},receiptPath=path.join(root,'success.json'),client=new FakeClient();const result=await compact.runEmployee01Compaction({client,auth,receiptPath,timeoutMs:100,terminalTimeoutMs:100,pollMs:1});assert.equal(result.status,'completed_verified');assert.equal(client.compactStarts,1);assert.equal(result.receipt.thread_id,compact.EMPLOYEE01_THREAD_ID);assert.equal(result.receipt.compacted_event.turn_id,client.compactTurnId);assert.equal(result.receipt.terminal_readback.status,'completed');assert.equal(result.receipt.history.anchor_readable_after,true);assert.equal(result.receipt.history.thread_id_unchanged,true);assert.equal(result.receipt.all_fixed_threads_idle_after,true);
  const replayClient=new FakeClient(),replay=await compact.runEmployee01Compaction({client:replayClient,auth,receiptPath});assert.equal(replay.status,'replayed');assert.equal(replayClient.compactStarts,0);
  const mismatchClient=new FakeClient({wrongIdentity:true});await assert.rejects(()=>compact.runEmployee01Compaction({client:mismatchClient,auth,receiptPath:path.join(root,'identity.json'),timeoutMs:50,pollMs:1}),/thread_identity_mismatch/);assert.equal(mismatchClient.compactStarts,0);
  const casClient=new FakeClient({casChange:true});await assert.rejects(()=>compact.runEmployee01Compaction({client:casClient,auth,receiptPath:path.join(root,'cas.json'),timeoutMs:50,pollMs:1}),/thread_cas_changed:02/);assert.equal(casClient.compactStarts,0);
  const failedPath=path.join(root,'failed.json'),failedClient=new FakeClient({failedCompact:true});await assert.rejects(()=>compact.runEmployee01Compaction({client:failedClient,auth,receiptPath:failedPath,timeoutMs:100,terminalTimeoutMs:100,pollMs:1}),/terminal_not_clean:failed/);assert.equal(failedClient.compactStarts,1);const failedReceipt=JSON.parse(await fsp.readFile(failedPath,'utf8'));assert.equal(failedReceipt.status,'failed');assert.equal(failedReceipt.compacted_event.turn_id,failedClient.compactTurnId);const failedReplayClient=new FakeClient();await assert.rejects(()=>compact.runEmployee01Compaction({client:failedReplayClient,auth,receiptPath:failedPath}),/previous_failed/);assert.equal(failedReplayClient.compactStarts,0);
  const notificationClient=new FakeClient({noNotification:true});await assert.rejects(()=>compact.runEmployee01Compaction({client:notificationClient,auth,receiptPath:path.join(root,'notification.json'),timeoutMs:10,pollMs:1}),/notification_timeout/);assert.equal(notificationClient.compactStarts,1);
  const itemCompletedClient=new FakeClient({itemCompleted:true}),itemCompleted=await compact.runEmployee01Compaction({client:itemCompletedClient,auth,receiptPath:path.join(root,'item-completed.json'),timeoutMs:100,terminalTimeoutMs:100,pollMs:1});assert.equal(itemCompleted.status,'completed_verified');assert.equal(itemCompleted.receipt.compacted_event.method,'item/completed');assert.equal(itemCompleted.receipt.compacted_event.item_type,'contextCompaction');assert.equal(itemCompleted.receipt.compacted_event.turn_id,itemCompletedClient.compactTurnId);
  const pollClient=new FakeClient({pollOnlyCompaction:true}),polled=await compact.runEmployee01Compaction({client:pollClient,auth,receiptPath:path.join(root,'poll-only.json'),timeoutMs:100,terminalTimeoutMs:100,pollMs:1});assert.equal(polled.status,'completed_verified');assert.equal(polled.receipt.compacted_event.method,'thread/read_context_compaction');assert.equal(polled.receipt.compacted_event.turn_id,pollClient.compactTurnId);assert.equal(pollClient.compactStarts,1);
  process.stdout.write(JSON.stringify({ok:true,verified:['exact Employee01 identity','all-five initial idle and second CAS','schema thread/compact/start','matching deprecated thread/compacted','matching official item/completed contextCompaction','poll fallback exact new contextCompaction turn','exact compact turn terminal readback','history anchor remains readable','thread id unchanged','all-five idle after','immutable receipt replay zero duplicate','identity mismatch zero compact','CAS mismatch zero compact','failed compact durable receipt','failed replay zero duplicate','missing notification and no compact turn typed failure','no new thread/config/history delete/provider/shell effects']})+'\n');
}finally{await fsp.rm(root,{recursive:true,force:true});}}
main().catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
