const assert = require('assert/strict');
const fs = require('fs').promises;
const os = require('os');
const path = require('path');
const story = require('./bridge/niannian_step01_story_authority');
const roles = require('./bridge/niannian_step01_role_card_authority');

async function run() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'step01-story-'));
  const project = {id:'NN-20260715083045-8120F5'};
  const ledger = {analysis_run_id:'analysis-1',source_sha256:'a'.repeat(64),snapshot_id:'S01LEDGER-test',snapshot_sha256:'b'.repeat(64),shots:[{shot_id:'S001',start_sec:0,end_sec:5,dialogue_ids:['D001'],ocr_ids:[],source_visual_facts:'客厅内红裙女性与另一人相对而立，画面显示文字“沈清柠 林家养女”',characters:['若若'],action:'女主转身离开',props:[]},{shot_id:'S002',start_sec:5,end_sec:9,dialogue_ids:[],ocr_ids:[],source_visual_facts:'',characters:[],action:'',props:[]}],dialogue_rows:[{dialogue_id:'D001',source_text:'司若若，你别再骗我了'}],ocr_rows:[]};
  const generated = await story.generate({root,project,ledger,scriptText:'',requestGemini:false});
  assert.equal(generated.status, 'draft');
  assert.equal(generated.language, 'zh-CN');
  assert.equal(generated.outline.beats.length, 1);
  assert.equal(generated.gemini_sidecar.status, 'not_requested');
  const fullEvidenceIndex = {index_sha256:'d'.repeat(64),frames:[{frame_id:'F-red-1',shot_id:'S001'},{frame_id:'F-red-2',shot_id:'S002'}]};
  generated.gemini_sidecar = {status:'completed',frame_observations:[{frame_id:'F-red-1',visual_subjects:[{continuity_key:'长棕发女性，持花束',visible_description:'长棕发女性穿红色礼服，手持花束',visible_action:'在室内转身',uncertain:false}]},{frame_id:'F-red-2',visual_subjects:[{continuity_key:'长棕发女性，持花束',visible_description:'同一女性',visible_action:'停步回望',uncertain:false}]}]};
  let roleCards = await roles.generate({root:path.join(root, 'roles'),project,ledger,story:generated,fullEvidenceIndex});
  assert.ok(roleCards.cards.some(card => card.original_name === '司若若'));
  assert.ok(roleCards.cards.some(card => card.visual_alias === '长棕发女性，持花束'));
  const nameOnly = roleCards.cards.find(card => card.original_name === '司若若');
  assert.equal(nameOnly.name_binding.status, 'unbound');
  const redDress = roleCards.cards.find(card => card.visual_alias === '长棕发女性，持花束');
  assert.equal(redDress.original_name, '');
  assert.equal(redDress.role_label, '视觉人物（待命名）');
  assert.equal(redDress.evidence_status, 'visual_identity_confirmed_name_unbound');
  assert.equal(redDress.name_binding.status, 'unbound');
  assert.equal(redDress.first_appearance_shot, 'S001');
  assert.equal(redDress.status, 'system_identified');
  assert.equal(roles.allImportantConfirmed(roleCards), true);
  const stateFile = path.join(root, project.id, 'story-authority.json');
  const withSidecar = JSON.parse(await fs.readFile(stateFile, 'utf8'));
  withSidecar.script_source = {provided:true, sha256:'c'.repeat(64), chars:42};
  withSidecar.gemini_sidecar = {status:'completed', provider:'yunwu_openai_compatible', model:'gemini-3.1-pro-preview', selected_shot_ids:['S002'], analyses:[{shot_id:'S002', observed:'走廊内一名女性停步回望。', uncertainty:'无法确认她与前一镜人物的关系。', needs_video_review:true}]};
  await fs.writeFile(stateFile, JSON.stringify(withSidecar));
  const recomposed = await story.generate({root,project,ledger,roleCards,scriptText:'',requestGemini:false,reuseGeminiSidecar:true});
  assert.equal(recomposed.script_source.provided, true);
  assert.equal(recomposed.gemini_sidecar.status, 'completed');
  assert.equal(recomposed.outline.beats[0].confidence, 'evidence_supported');
  assert.match(recomposed.outline.beats[0].review_notes.join(' '), /无法确认/);
  assert.equal(recomposed.recomposition.mode, 'reuse_existing_gemini_sidecar');
  const sidecarOnlyOutline = story.buildEvidenceOutline({...ledger, shots:[ledger.shots[1]]}, '', {analyses:[{shot_id:'S002', observed:'走廊内一名女性停步回望。', uncertainty:'无法确认人物关系。'}]});
  assert.equal(sidecarOnlyOutline.beats[0].confidence, 'sidecar_supported');
  assert.match(sidecarOnlyOutline.beats[0].summary, /回望/);
  const ocrCrosscheckedOutline = story.buildEvidenceOutline({...ledger, shots:[{...ledger.shots[1], ocr_ids:['OCR001']}], ocr_rows:[{ocr_id:'OCR001', source_text:'办理结婚登记业务'}]}, '', {analyses:[{shot_id:'S002', observed:'窗口前有人递出册子。', uncertainty:'无法确认册子内容。'}]});
  assert.equal(ocrCrosscheckedOutline.beats[0].evidence[0].ocr_crosscheck.status, 'text_evidence_available');
  assert.deepEqual(ocrCrosscheckedOutline.beats[0].evidence[0].ocr_crosscheck.texts, ['办理结婚登记业务']);
  assert.match(ocrCrosscheckedOutline.beats[0].evidence[0].ocr_crosscheck.unresolved_scope, /人物身份/);
  assert.equal(story.narrativeBeatSummary({evidence:[], dialogueLines:['大哥，他们不会去了。','司若若，怎么是你？','只要我轻轻勾勾手指，他们就放了你的鸽子。'], ocrLines:[], fallback:'fallback'}), '有人先向“大哥”表示原定对象不会前往；有人认出司若若，随后出现“放了你的鸽子”的挑衅，现场冲突升级。');
  const draftRevision = await story.revise({root,project,ledger,roleCards,ifMatch:story.etag(recomposed),body:{action:'save_draft',outline:recomposed.outline},actor:'U'});
  const original = process.env.YUNWU_GEMINI_PRO_LOWEST_API_KEY;
  delete process.env.GEMINI_API_KEY; delete process.env.GOOGLE_GEMINI_API_KEY;
  process.env.YUNWU_GEMINI_PRO_LOWEST_API_KEY = 'test-key';
  const yunwu = story.defaultGeminiConfig();
  assert.equal(yunwu.provider, 'yunwu_openai_compatible');
  assert.equal(yunwu.model, 'gemini-3.1-pro-preview');
  if (original) process.env.YUNWU_GEMINI_PRO_LOWEST_API_KEY = original; else delete process.env.YUNWU_GEMINI_PRO_LOWEST_API_KEY;
  const evidenceRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'step01-story-frames-'));
  const relative = 'frames/EP001_transnet_shot_0002_mid.png';
  await fs.mkdir(path.join(evidenceRoot, 'artifacts', 'frames'), {recursive:true});
  await fs.writeFile(path.join(evidenceRoot, 'artifacts', ...relative.split('/')), Buffer.from('not-a-real-png'));
  const yunwuLedger = {...ledger, shots:[{...ledger.shots[1], frame_evidence:[{point:'mid', relative_path:relative}]}]};
  const originalFetch = global.fetch;
  let receivedPayload = null;
  global.fetch = async (_url, request) => { receivedPayload = JSON.parse(request.body); return {ok:true, json:async () => ({choices:[{message:{content:'```json\n' + JSON.stringify({analyses:[{shot_id:'S002',observed:'画面可见事实',uncertainty:'无',needs_video_review:false}]}) + '\n```'}}]})}; };
  const yunwuResult = await story.analyzeWithYunwu({config:{configured:true, provider:'yunwu_openai_compatible', apiKey:'test-key', model:'gemini-3.1-pro-preview', endpoint:'https://yunwu.ai'}, ledger:yunwuLedger, shotIds:['S002'], evidenceRoot});
  global.fetch = originalFetch;
  assert.equal(yunwuResult.status, 'completed');
  assert.equal(yunwuResult.analyses[0].shot_id, 'S002');
  assert.equal(receivedPayload.model, 'gemini-3.1-pro-preview');
  assert.equal(receivedPayload.messages[0].content.filter(item => item.type === 'image_url').length, 1);
  const nativeFrames = [];
  for (let index = 0; index < 25; index += 1) {
    const file = path.join(evidenceRoot, 'artifacts', 'frames', 'native-' + index + '.png');
    await fs.writeFile(file, Buffer.from('native-' + index));
    nativeFrames.push({frame_id:'F-' + index, shot_id:index < 18 ? 'S001' : 'S002', absolute_path:file, timecode:'00:00:' + String(index).padStart(2, '0') + '.000', extraction_reason:'audio_event'});
  }
  const calls = [];
  let inFlight = 0;
  let maxInFlight = 0;
  global.fetch = async (_url, request) => {
    const payload = JSON.parse(request.body); calls.push(payload); inFlight += 1; maxInFlight = Math.max(maxInFlight, inFlight);
    await new Promise(resolve => setTimeout(resolve, 5));
    const labels = payload.messages[0].content.filter(item => item.type === 'text').map(item => item.text).join('\n');
    const shotIds = [...labels.matchAll(/原片证据：(S\d{3})/g)].map(match => match[1]);
    const frameIds = [...labels.matchAll(/原片证据：S\d{3} \/ (F-\d+) \//g)].map(match => match[1]);
    inFlight -= 1;
    return {ok:true, json:async () => ({choices:[{message:{content:JSON.stringify({analyses:[...new Set(shotIds)].map(shot_id => ({shot_id,observed:'可见事实',uncertainty:'',needs_video_review:false})),frame_observations:frameIds.map(frame_id => ({frame_id,visual_subjects:[]}))})}}]})};
  };
  const fullBatch = await story.analyzeAllShotsWithYunwu({config:{configured:true, apiKey:'test-key', model:'gemini-3.1-pro-preview', endpoint:'https://yunwu.ai'},ledger,shotIds:['S001','S002'],evidenceRoot,fullEvidenceIndex:{frames:nativeFrames}});
  global.fetch = originalFetch;
  assert.equal(fullBatch.status, 'completed');
  assert.equal(fullBatch.reviewed_frame_ids.length, 25);
  assert.equal(fullBatch.concurrency_initial, 3);
  assert.equal(fullBatch.concurrency_used, 3);
  assert.equal(fullBatch.duplicate_submission_count, 0);
  assert.equal(fullBatch.telemetry.length, 3);
  assert.ok(maxInFlight >= 2 && maxInFlight <= 3);
  assert.ok(calls.every(payload => payload.messages[0].content.filter(item => item.type === 'image_url').length <= 12));
  assert.equal(calls.reduce((sum, payload) => sum + payload.messages[0].content.filter(item => item.type === 'image_url').length, 0), 25);
  calls.length=0;
  global.fetch = async (_url, request) => { const payload=JSON.parse(request.body); calls.push(payload); const labels=payload.messages[0].content.filter(item=>item.type==='text').map(item=>item.text).join('\n'); const frameIds=[...labels.matchAll(/原片证据：S\d{3} \/ (F-\d+) \//g)].map(match=>match[1]); return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({analyses:[{shot_id:'S001',observed:'可见事实',uncertainty:'',needs_video_review:false},{shot_id:'S002',observed:'可见事实',uncertainty:'',needs_video_review:false}],frame_observations:frameIds.map(frame_id=>({frame_id,visual_subjects:[]}))})}}]})}; };
  await story.analyzeAllShotsWithYunwu({config:{configured:true, apiKey:'test-key', model:'gemini-3.1-pro-preview', endpoint:'https://yunwu.ai'},ledger,shotIds:['S001','S002'],evidenceRoot,fullEvidenceIndex:{index_sha256:'f'.repeat(64),frames:nativeFrames},receiptRoot:root,project});
  const paidCallCount=calls.length;
  await story.analyzeAllShotsWithYunwu({config:{configured:true, apiKey:'test-key', model:'gemini-3.1-pro-preview', endpoint:'https://yunwu.ai'},ledger,shotIds:['S001','S002'],evidenceRoot,fullEvidenceIndex:{index_sha256:'f'.repeat(64),frames:nativeFrames},receiptRoot:root,project});
  assert.equal(calls.length, paidCallCount);
  calls.length=0;
  const raceOptions={config:{configured:true,apiKey:'test-key',model:'gemini-3.1-pro-preview',endpoint:'https://yunwu.ai'},ledger,shotIds:['S001','S002'],evidenceRoot,fullEvidenceIndex:{index_sha256:'f'.repeat(64),frames:nativeFrames},receiptRoot:root,receiptNamespace:'race-revision',project};
  const [raceA,raceB]=await Promise.all([story.analyzeAllShotsWithYunwu(raceOptions),story.analyzeAllShotsWithYunwu(raceOptions)]);
  assert.equal(calls.length,3);
  assert.equal(raceA.duplicate_submission_count+raceB.duplicate_submission_count,0);
  assert.ok(raceA.prevented_concurrent_submission_count+raceB.prevented_concurrent_submission_count>=1);
  const raceReceiptDir=path.join(root,project.id,'full-evidence-batches','race-revision');
  const receiptNames=(await fs.readdir(raceReceiptDir)).filter(name=>name.endsWith('.json'));
  const tamperedPath=path.join(raceReceiptDir,receiptNames[0]);
  const tampered=JSON.parse(await fs.readFile(tamperedPath,'utf8'));
  tampered.result.analyses[0].observed='篡改后的结果';
  await fs.writeFile(tamperedPath,JSON.stringify(tampered));
  const callsBeforeTamperReplay=calls.length;
  const tamperReplay=await story.analyzeAllShotsWithYunwu(raceOptions);
  assert.equal(calls.length,callsBeforeTamperReplay);
  assert.equal(tamperReplay.status,'partial');
  assert.ok(tamperReplay.failures.some(item=>item.error_code==='YUNWU_COMPLETED_RECEIPT_INTEGRITY_FAILED'));
  calls.length=0;
  const failedIdentityOptions={...raceOptions,receiptNamespace:'failed-identity-revision'};
  await story.analyzeAllShotsWithYunwu(failedIdentityOptions);
  const failedReceiptDir=path.join(root,project.id,'full-evidence-batches','failed-identity-revision');
  const failedReceiptNames=(await fs.readdir(failedReceiptDir)).filter(name=>name.endsWith('.json'));
  const failedReceiptPath=path.join(failedReceiptDir,failedReceiptNames[0]);
  const failedReceipt=JSON.parse(await fs.readFile(failedReceiptPath,'utf8'));
  failedReceipt.status='failed';
  failedReceipt.identity.authority_revision_id='analysis-identity-drift';
  await fs.writeFile(failedReceiptPath,JSON.stringify(failedReceipt));
  const callsBeforeFailedReplay=calls.length;
  const failedReplay=await story.analyzeAllShotsWithYunwu(failedIdentityOptions);
  assert.equal(calls.length,callsBeforeFailedReplay);
  assert.ok(failedReplay.failures.some(item=>item.error_code==='YUNWU_NONTERMINAL_RECEIPT_IDENTITY_INVALID'));
  global.fetch = originalFetch;
  global.fetch = async () => ({ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({analyses:[{shot_id:'S001',observed:'可见事实'}],frame_observations:[]})}}]})});
  const incomplete = await story.analyzeWithYunwu({config:{configured:true,apiKey:'test-key',model:'gemini-3.1-pro-preview',endpoint:'https://yunwu.ai'},ledger,shotIds:['S001'],evidenceRoot,fullEvidenceIndex:{frames:[nativeFrames[0]]},frameSubset:[nativeFrames[0]]});
  global.fetch = originalFetch;
  assert.equal(incomplete.status, 'incomplete_response');
  assert.equal(incomplete.error_code, 'YUNWU_FRAME_OBSERVATIONS_INCOMPLETE');
  assert.deepEqual(story.parseModelJson('说明 {"analyses":[]}'), {analyses:[]});
  await fs.rm(evidenceRoot,{recursive:true,force:true});
  const loaded = await story.get({root,project,ledger});
  assert.equal(loaded.snapshot_sha256, draftRevision.snapshot_sha256);
  await assert.rejects(() => story.revise({root,project,ledger,ifMatch:'"wrong"',body:{outline:draftRevision.outline},actor:'U'}), error => error.code === 'STEP01_STORY_REVISION_CONFLICT');
  const changedCard = {...redDress, narrative_function:'用户修订的女主功能'};
  roleCards = await roles.revise({root:path.join(root, 'roles'),project,ledger,ifMatch:roles.etag(roleCards),idempotencyKey:'role-edit-red-dress',body:{action:'save_draft',card_id:changedCard.card_id,card:changedCard},actor:'U'});
  assert.equal(roleCards.cards.find(card => card.card_id === changedCard.card_id).status, 'user_edited');
  const replay = await roles.revise({root:path.join(root, 'roles'),project,ledger,ifMatch:'"stale-etag"',idempotencyKey:'role-edit-red-dress',body:{action:'save_draft',card_id:changedCard.card_id,card:changedCard},actor:'U'});
  assert.equal(replay.snapshot_sha256, roleCards.snapshot_sha256);
  const confirmedDraft = await story.generate({root,project,ledger,roleCards,scriptText:'',requestGemini:false,reuseGeminiSidecar:true});
  const revised = await story.revise({root,project,ledger,roleCards,ifMatch:story.etag(confirmedDraft),body:{action:'confirm',reason:'用户核对通过',outline:{...confirmedDraft.outline,synopsis:'用户已确认的中文剧情概要'}},actor:'U'});
  assert.equal(revised.status, 'confirmed');
  assert.match(revised.snapshot_id, /^S01STORY-/);
  await fs.rm(root,{recursive:true,force:true});
  process.stdout.write(JSON.stringify({ok:true,story_authority:true,outline_evidence_bound:true,etag_guard:true,confirmed_revision:true}) + '\n');
}
run().catch(error => { process.stderr.write(String(error.stack || error) + '\n'); process.exitCode = 1; });
