'use strict';

const crypto=require('crypto');
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const os=require('os');
const release=require('./niannian_mac_bridge_release');

const PROJECT_ROOT=path.resolve(__dirname,'..');
const CANONICAL_MAC_PROJECT_ROOT='/Users/lsb/AI-Brain/niannian-ai-canonical-local';
const BUNDLE_RELATIVE_PATH='output/mac-employee-training/mac-bridge-release';
const RECEIPT_RELATIVE_PATH='output/mac-employee-training/mac-bridge-release-install-receipt.json';
function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
async function copyRegular(source,target){const stats=await fsp.lstat(source);if(!stats.isFile()||stats.isSymbolicLink())throw new Error('mac_bridge_install_source_invalid');await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.copyFile(source,target,fs.constants.COPYFILE_EXCL);}
async function atomicJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});const temp=filePath+'.tmp-'+process.pid+'-'+crypto.randomBytes(3).toString('hex');await fsp.writeFile(temp,JSON.stringify(value,null,2)+'\n',{flag:'wx'});await fsp.rename(temp,filePath);}
function resolveContract(options={}){if(options.testMode===true){if(process.env.NIANNIAN_MAC_BRIDGE_INSTALL_TEST_MODE!=='1')throw new Error('mac_bridge_install_test_mode_not_enabled');const root=path.resolve(options.projectRoot);return {projectRoot:root,bundleRoot:path.resolve(options.bundleRoot),receiptPath:path.resolve(options.receiptPath||path.join(root,RECEIPT_RELATIVE_PATH)),gatewayPath:path.join(root,'.local','bin','ai-brain-mac-relay-gateway.sh'),launchAgentPath:path.join(root,'Library','LaunchAgents','com.niannian.ai-brain.hq-refresh.plist')};}if(options.bootstrap===true&&Object.keys(options).length===1)return {projectRoot:CANONICAL_MAC_PROJECT_ROOT,bundleRoot:path.join(CANONICAL_MAC_PROJECT_ROOT,...BUNDLE_RELATIVE_PATH.split('/')),receiptPath:path.join(CANONICAL_MAC_PROJECT_ROOT,...RECEIPT_RELATIVE_PATH.split('/')),gatewayPath:path.join(os.homedir(),'.local','bin','ai-brain-mac-relay-gateway.sh'),launchAgentPath:path.join(os.homedir(),'Library','LaunchAgents','com.niannian.ai-brain.hq-refresh.plist')};if(Object.keys(options).length)throw new Error('mac_bridge_install_override_forbidden');return {projectRoot:PROJECT_ROOT,bundleRoot:path.join(PROJECT_ROOT,...BUNDLE_RELATIVE_PATH.split('/')),receiptPath:path.join(PROJECT_ROOT,...RECEIPT_RELATIVE_PATH.split('/')),gatewayPath:path.join(os.homedir(),'.local','bin','ai-brain-mac-relay-gateway.sh'),launchAgentPath:path.join(os.homedir(),'Library','LaunchAgents','com.niannian.ai-brain.hq-refresh.plist')};}
function targetPath(contract,row){if(row.path==='bridge/mac_relay_ssh_gateway.sh')return contract.gatewayPath;if(row.path==='bridge/com.niannian.ai-brain.hq-refresh.plist')return contract.launchAgentPath;return path.join(contract.projectRoot,...row.path.split('/'));}
async function rollback(transaction){for(const row of [...transaction].reverse()){const target=row.target;await fsp.rm(target,{force:true});if(row.hadOriginal)await fsp.rename(row.backup,target);} }
async function installBridgeRelease(options={}){const contract=resolveContract(options),verified=await release.verifyReleaseBundle({bundleRoot:contract.bundleRoot});const transactionRoot=path.join(contract.projectRoot,'output','mac-employee-training','.mac-bridge-install-'+process.pid+'-'+crypto.randomBytes(3).toString('hex'), 'originals');const transaction=[];try{await fsp.mkdir(transactionRoot,{recursive:true});for(const row of verified.manifest.files){const source=path.join(contract.bundleRoot,...row.path.split('/'));const target=targetPath(contract,row);const staged=path.join(transactionRoot,'staged',...row.path.split('/'));const backup=path.join(transactionRoot,'originals',...row.path.split('/'));await copyRegular(source,staged);const before=await fsp.lstat(target).catch(error=>error.code==='ENOENT'?null:Promise.reject(error));if(before&&(!before.isFile()||before.isSymbolicLink()))throw new Error('mac_bridge_install_target_invalid:'+row.path);if(before){await fsp.mkdir(path.dirname(backup),{recursive:true});await fsp.rename(target,backup);}transaction.push({target,backup,hadOriginal:Boolean(before)});await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.rename(staged,target);if(row.path==='bridge/mac_relay_ssh_gateway.sh'||row.path.endsWith('.command'))await fsp.chmod(target,0o700);if(row.path==='bridge/com.niannian.ai-brain.hq-refresh.plist')await fsp.chmod(target,0o600);if(options.testMode===true&&Number(options.failAfter)===transaction.length)throw new Error('mac_bridge_install_test_failure');}
    const installedAt=new Date().toISOString();const state={schema_version:release.INSTALL_STATE_SCHEMA,status:'installed_verified',release_version:verified.manifest.release_version,manifest_sha256:verified.manifest_sha256,installed_at:installedAt,rollback_record:{transaction_root:transactionRoot,previous_files:transaction.filter(row=>row.hadOriginal).length,rollback_available:true},gateway:{exact_path:contract.gatewayPath,mode:'0700',source:'bridge/mac_relay_ssh_gateway.sh'},provider_network_requested:false,provider_submit_requested:false,project_media_processed:false,real_delivery:false};await atomicJson(path.join(contract.projectRoot,...release.INSTALL_STATE_RELATIVE_PATH.split('/')),state);const receipt={schema_version:'niannian_mac_bridge_install_receipt_v1',status:'installed_verified',release_version:state.release_version,manifest_sha256:state.manifest_sha256,installed_files:verified.manifest.files.map(row=>({path:row.path,sha256:row.sha256,bytes:row.bytes})),gateway:state.gateway,rollback_record:state.rollback_record,secret_output:false,provider_network_requested:false,provider_submit_requested:false,project_media_processed:false,real_delivery:false,installed_at:installedAt};await atomicJson(contract.receiptPath,receipt);return receipt;
  }catch(error){await rollback(transaction).catch(()=>{});throw error;}}
if(require.main===module)installBridgeRelease().then(value=>process.stdout.write(JSON.stringify({ok:true,status:value.status,release_version:value.release_version,manifest_sha256:value.manifest_sha256,secret_output:false})+'\n')).catch(error=>{process.stderr.write(String(error.message||error)+'\n');process.exitCode=1;});
module.exports={BUNDLE_RELATIVE_PATH,CANONICAL_MAC_PROJECT_ROOT,PROJECT_ROOT,RECEIPT_RELATIVE_PATH,installBridgeRelease,resolveContract,targetPath};
