'use strict';

const crypto=require('crypto');
const fs=require('fs');
const fsp=fs.promises;
const os=require('os');
const path=require('path');
const {PROJECT_ROOT,THREADS,hasActiveTurn,safeErrorSummary,summarizeThread}=require('./mac_codex_app_employee_bootstrap');

const CONTRACT_ID='employee01-native-context-r64-v1';
const EMPLOYEE01_THREAD_ID='019f6201-c013-7cf3-b155-61d2789085f4';
const RECEIPT_SCHEMA='niannian_mac_employee01_compaction_receipt_v1';
const RECEIPT_PATH=path.join(os.homedir(),'.local','share','niannian-ai','mac-app-compaction-receipts',CONTRACT_ID+'.json');
const COMPACTION_TIMEOUT_MS=300000;
const TERMINAL_READBACK_TIMEOUT_MS=300000;

const sha256=value=>crypto.createHash('sha256').update(value).digest('hex');
const bytes=value=>Buffer.from(JSON.stringify(value,null,2)+'\n','utf8');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function status(value){if(typeof value==='string')return value;if(value&&typeof value==='object'){if(typeof value.type==='string')return value.type;if(typeof value.status==='string')return value.status;}return null;}
function fixedEmployee01(){const fixed=THREADS.find(item=>item.thread_id===EMPLOYEE01_THREAD_ID);if(!fixed)throw new Error('employee01_compaction_authority_missing');return fixed;}
function assertIdentity(summary,fixed){if(summary.thread_id!==fixed.thread_id||summary.title!==fixed.title||summary.cwd!==PROJECT_ROOT)throw new Error('employee01_compaction_thread_identity_mismatch:'+fixed.employee);}
async function readAll(client){const rows=[];for(const fixed of THREADS){const thread=(await client.request('thread/read',{threadId:fixed.thread_id,includeTurns:true})).thread,summary=summarizeThread(thread);assertIdentity(summary,fixed);if(hasActiveTurn(summary))throw new Error('employee01_compaction_active_thread:'+fixed.employee);rows.push({fixed,thread,summary});}return rows;}
function stableCas(before,after){if(before.length!==THREADS.length||after.length!==THREADS.length)throw new Error('employee01_compaction_all_threads_read_incomplete');for(let index=0;index<THREADS.length;index+=1){const first=before[index].summary,second=after[index].summary,fixed=THREADS[index];if(first.thread_id!==second.thread_id)throw new Error('employee01_compaction_thread_order_changed');if(fixed.thread_id===EMPLOYEE01_THREAD_ID&&first.status?.type==='notLoaded')continue;if(first.turns!==second.turns||first.latest_turn_id!==second.latest_turn_id||first.latest_completed_assistant_turn_id!==second.latest_completed_assistant_turn_id||first.status?.type!==second.status?.type)throw new Error('employee01_compaction_thread_cas_changed:'+fixed.employee);}}
async function atomicReceipt(receiptPath,value){await fsp.mkdir(path.dirname(receiptPath),{recursive:true,mode:0o700});const data=bytes(value),tmp=receiptPath+'.tmp-'+process.pid+'-'+crypto.randomBytes(4).toString('hex');await fsp.writeFile(tmp,data,{flag:'wx',mode:0o600});await fsp.rename(tmp,receiptPath);try{await fsp.chmod(receiptPath,0o600);}catch{}return {sha256:sha256(data),bytes:data.length};}
async function existingReceipt(receiptPath){try{return JSON.parse(await fsp.readFile(receiptPath,'utf8'));}catch(error){if(error.code==='ENOENT')return null;throw error;}}
function validateReplay(receipt){if(receipt?.schema_version!==RECEIPT_SCHEMA||receipt.contract_id!==CONTRACT_ID||receipt.thread_id!==EMPLOYEE01_THREAD_ID||!['completed_verified','failed'].includes(receipt.status))throw new Error('employee01_compaction_replay_receipt_invalid');return receipt;}
function waitForCompacted(client,threadId,beforeTurnIds,start,timeoutMs,pollMs=1000){return new Promise(async(resolve,reject)=>{let settled=false,polling=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timer);client.off('notification',onNotification);error?reject(error):resolve(value);};const isNewTurnId=turnId=>typeof turnId==='string'&&!beforeTurnIds.has(turnId);const onNotification=message=>{const params=message?.params||{};if(message?.method==='thread/compacted'&&params.threadId===threadId&&isNewTurnId(params.turnId)){finish(null,{method:'thread/compacted',thread_id:threadId,turn_id:params.turnId,param_keys:Object.keys(params).sort()});return;}const item=params.item||{};if(message?.method==='item/completed'&&params.threadId===threadId&&isNewTurnId(params.turnId)&&item.type==='contextCompaction'){finish(null,{method:'item/completed',thread_id:threadId,turn_id:params.turnId,item_id:typeof item.id==='string'?item.id:null,item_type:item.type,param_keys:Object.keys(params).sort()});}};const poll=async()=>{if(settled||polling)return;polling=true;try{const thread=(await client.request('thread/read',{threadId,includeTurns:true})).thread;for(const turn of Array.isArray(thread?.turns)?thread.turns:[]){const turnId=String(turn?.id||'');if(isNewTurnId(turnId)&&Array.isArray(turn?.items)&&turn.items.some(item=>item?.type==='contextCompaction')){finish(null,{method:'thread/read_context_compaction',thread_id:threadId,turn_id:turnId,item_type:'contextCompaction'});return;}}}catch(error){finish(error);return;}finally{polling=false;}if(!settled)setTimeout(poll,pollMs);};const timer=setTimeout(()=>finish(new Error('employee01_compaction_notification_timeout')),timeoutMs);client.on('notification',onNotification);try{await start();if(!settled)await poll();}catch(error){finish(error);}});}
async function terminalCompactionReadback(client,threadId,turnId,timeoutMs,pollMs){const started=Date.now();while(Date.now()-started<timeoutMs){const thread=(await client.request('thread/read',{threadId,includeTurns:true})).thread,turn=Array.isArray(thread?.turns)?thread.turns.find(item=>String(item?.id||'')===turnId):null,turnStatus=status(turn?.status);if(turn&&['completed','failed','cancelled','interrupted'].includes(turnStatus))return {thread,turn,turn_status:turnStatus,turn_error:turn.error??null};await delay(pollMs);}throw new Error('employee01_compaction_terminal_readback_timeout');}
function falseEffects(value){for(const key of ['media_provider_network_requested','media_provider_submit_requested','media_provider_upload_requested','spend_requested','project_media_processed','shell_command_requested','new_thread_requested','global_config_write_requested','history_delete_requested'])if(value[key]!==false)throw new Error('employee01_compaction_side_effect_contract_invalid:'+key);}

async function runEmployee01Compaction(options={}){
  const client=options.client;if(!client||typeof client.request!=='function'||typeof client.on!=='function')throw new Error('employee01_compaction_client_required');
  const receiptPath=path.resolve(options.receiptPath||RECEIPT_PATH),prior=await existingReceipt(receiptPath);
  if(prior){const receipt=validateReplay(prior);if(receipt.status==='failed'){const error=new Error('employee01_compaction_previous_failed');error.compaction_receipt=receipt;throw error;}return {status:'replayed',receipt,receipt_path:receiptPath};}
  const fixed=fixedEmployee01(),auth=options.auth;if(auth?.provider_config_id!=='openai'||!auth.default_model||auth.raw_auth_read!==false)throw new Error('employee01_compaction_native_model_binding_invalid');
  let before=null,second=null,notification=null,terminal=null;
  try{
    before=await readAll(client,{allowEmployee01NotLoaded:true});const selectedBefore=before.find(row=>row.fixed.thread_id===EMPLOYEE01_THREAD_ID),historyAnchor=selectedBefore.summary.latest_completed_assistant_turn_id||selectedBefore.summary.latest_turn_id,beforeTurnIds=new Set((selectedBefore.thread.turns||[]).map(turn=>String(turn?.id||'')));if(!historyAnchor||selectedBefore.summary.turns<1)throw new Error('employee01_compaction_history_anchor_missing');
    await client.request('thread/resume',{threadId:EMPLOYEE01_THREAD_ID,cwd:PROJECT_ROOT,approvalPolicy:'never',excludeTurns:true,modelProvider:'openai',model:auth.default_model});
    second=await readAll(client);stableCas(before,second);
    notification=await waitForCompacted(client,EMPLOYEE01_THREAD_ID,beforeTurnIds,()=>client.request('thread/compact/start',{threadId:EMPLOYEE01_THREAD_ID}),Number(options.timeoutMs||COMPACTION_TIMEOUT_MS),Number(options.pollMs||1000));
    terminal=await terminalCompactionReadback(client,EMPLOYEE01_THREAD_ID,notification.turn_id,Number(options.terminalTimeoutMs||TERMINAL_READBACK_TIMEOUT_MS),Number(options.pollMs||1000));
    if(terminal.turn_status!=='completed'||terminal.turn_error!==null)throw new Error('employee01_compaction_terminal_not_clean:'+String(terminal.turn_status));
    const after=await readAll(client),selectedAfter=after.find(row=>row.fixed.thread_id===EMPLOYEE01_THREAD_ID),historyReadable=Array.isArray(selectedAfter.thread.turns)&&selectedAfter.thread.turns.some(item=>String(item?.id||'')===historyAnchor);if(!historyReadable)throw new Error('employee01_compaction_history_readback_missing');
    const receipt={schema_version:RECEIPT_SCHEMA,status:'completed_verified',contract_id:CONTRACT_ID,thread_id:EMPLOYEE01_THREAD_ID,employee:fixed.employee,title:fixed.title,cwd:PROJECT_ROOT,model_binding:{provider_config_id:'openai',model:auth.default_model,raw_auth_read:false},cas:{initial_all_idle:true,second_all_idle:true,fixed_count:THREADS.length},history:{pre_turn_count:selectedBefore.summary.turns,anchor_turn_id:historyAnchor,anchor_readable_after:true,post_turn_count:selectedAfter.summary.turns,thread_id_unchanged:selectedAfter.summary.thread_id===EMPLOYEE01_THREAD_ID},compact_start:{method:'thread/compact/start',thread_id:EMPLOYEE01_THREAD_ID},compacted_event:notification,terminal_readback:{turn_id:notification.turn_id,status:terminal.turn_status,error:null},all_fixed_threads_idle_after:true,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,project_media_processed:false,shell_command_requested:false,new_thread_requested:false,global_config_write_requested:false,history_delete_requested:false,created_at:new Date().toISOString()};falseEffects(receipt);const evidence=await atomicReceipt(receiptPath,receipt);return {status:'completed_verified',receipt:{...receipt,receipt_sha256:evidence.sha256,receipt_bytes:evidence.bytes},receipt_path:receiptPath};
  }catch(error){const failed={schema_version:RECEIPT_SCHEMA,status:'failed',contract_id:CONTRACT_ID,thread_id:EMPLOYEE01_THREAD_ID,employee:fixed.employee,title:fixed.title,cwd:PROJECT_ROOT,compact_start:{method:'thread/compact/start',thread_id:EMPLOYEE01_THREAD_ID},compacted_event:notification,terminal_readback:terminal?{turn_id:notification?.turn_id||null,status:terminal.turn_status,error:terminal.turn_error?safeErrorSummary(terminal.turn_error):null}:null,error:safeErrorSummary(error),media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,project_media_processed:false,shell_command_requested:false,new_thread_requested:false,global_config_write_requested:false,history_delete_requested:false,created_at:new Date().toISOString()};falseEffects(failed);const evidence=await atomicReceipt(receiptPath,failed).catch(()=>null);error.compaction_receipt={...failed,receipt_sha256:evidence?.sha256||null,receipt_bytes:evidence?.bytes||null};throw error;}
}

module.exports={COMPACTION_TIMEOUT_MS,CONTRACT_ID,EMPLOYEE01_THREAD_ID,RECEIPT_PATH,RECEIPT_SCHEMA,runEmployee01Compaction,stableCas,terminalCompactionReadback,validateReplay,waitForCompacted};
