'use strict';

const crypto=require('crypto');
const fsp=require('fs').promises;
const path=require('path');
const {AppServerClient,CODEX_PATH,PROJECT_ROOT,THREADS,assertCompletedTurn,hasActiveTurn,inspectEmployeeModelChannel,inspectNativeAccountRuntime,safeTurnFailureDiagnostic,summarizeThread}=require('./mac_codex_app_employee_bootstrap');
const {activeProfile}=require('./niannian_employee_model_profiles');
const step01Phase=require('./niannian_redraw_step01_mac_app_phase');
const hqExecutor=require('./mac-employee-training/execute_redraw_step01_hq_full');

async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}
async function writeJson(filePath,value){const temp=filePath+'.tmp-'+process.pid;await fsp.writeFile(temp,JSON.stringify(value,null,2)+'\n','utf8');await fsp.rename(temp,filePath);}
async function appendAttemptEvent(filePath,event){await fsp.mkdir(path.dirname(filePath),{recursive:true});const bytes=Buffer.from(JSON.stringify(event)+'\n','utf8');const handle=await fsp.open(filePath,'a',0o600);try{await handle.write(bytes);await handle.sync();}finally{await handle.close();}return {sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length};}
async function claimAttempt(workspace,claim){const claimPath=path.join(workspace,'.step01-dispatch-attempts',claim.attempt_id+'.json');await fsp.mkdir(path.dirname(claimPath),{recursive:true});let handle;try{handle=await fsp.open(claimPath,'wx',0o600);await handle.writeFile(JSON.stringify(claim,null,2)+'\n');await handle.sync();await handle.close();return {status:'claimed',claim_path:claimPath};}catch(error){if(handle)await handle.close().catch(()=>{});if(error.code!=='EEXIST')throw error;const existing=await readJson(claimPath).catch(()=>null);if(!existing||existing.attempt_id!==claim.attempt_id||existing.dispatch_id!==claim.dispatch_id||existing.phase_key!==claim.phase_key||existing.phase_manifest_sha256!==claim.phase_manifest_sha256||existing.employee_thread_id!==claim.employee_thread_id)throw new Error('step01_app_dispatch_attempt_claim_conflict');throw new Error('step01_app_dispatch_attempt_unreconciled');}}
function falseSideEffects(value){for(const key of ['media_provider_network_requested','media_provider_submit_requested','media_provider_upload_requested','spend_requested','package_send_requested','registry_promotion_requested','deployment_requested','local_image_editing_requested'])if(value?.[key]!==false)throw new Error('step01_app_dispatch_side_effect_invalid:'+key);}
function validateReplay(control,dispatch){
  if(control.schema_version!=='niannian_redraw_step01_mac_app_control_receipt_v2'||control.dispatch_id!==dispatch.dispatch_id||control.phase_key!==dispatch.phase_key.key_id||control.idempotency_key!==dispatch.idempotency_key||control.remote_project_id!==dispatch.remote_project_id||control.local_job_id!==dispatch.local_job_id||control.source_sha256!==dispatch.source_sha256||control.rights_authority?.event_id!==dispatch.rights_authority?.event_id||control.rights_authority?.sha256!==dispatch.rights_authority?.sha256||control.authorization_event_id!==dispatch.authorization_event_id||control.settings_version!==dispatch.settings_version||control.employee?.thread_id!==dispatch.employee.thread_id||control.attempt?.status!=='completed'||control.attempt?.dispatch_id!==dispatch.dispatch_id||control.completion_event?.method!=='turn/completed'||control.completion_event?.status!=='completed'||control.completion_event?.error!==null||control.test_only!==false||control.real_delivery!==false||control.cli_fallback_used!==false||control.relay_fallback_used!==false)throw new Error('step01_app_dispatch_replay_binding_invalid');
  falseSideEffects(control);if(control.analysis_service_network?.media_provider_authority_granted!==false)throw new Error('step01_app_dispatch_replay_provider_identity_invalid');return control;
}
function prompt(dispatch,dispatchPath){const executor=path.join(PROJECT_ROOT,'bridge','mac-employee-training','execute_redraw_step01_hq_full.js');const safePath='/Users/lsb/AI-Brain/tools/ffmpeg-runtime:/Users/lsb/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin';return [
  `你正在执行 ${dispatch.employee.title} 的真实 Step01 hq_full evidence phase ${dispatch.dispatch_id}。`,
  '先读取项目 AGENTS.md、route_matrix、exact source/auth/settings/toolchain/runtime receipts，并真实读取 mx-shortdrama-00-router 与 mx-shortdrama-01-frame-extract 的 SKILL.md。必须在本次 App turn 内生成 SHA 绑定的 route_decision.json 与 skill_execution_receipt.json；Windows 预检不能代替该路由决定。',
  '只允许 analysis_service_network_authority 中的 Mimo ASR 与 Paddle OCR；它们不是媒体生成 Provider。禁止 Image2/视频生成、媒体上传/提交、费用、部署、package/send、registry promotion、本地修图与 stable_batch 降级。',
  '必须由 SHA 绑定的 hq_full entrypoint 生成 evidence；Mimo→ForcedAligner、逐 PNG 源分辨率、accepted TransNet 每 shot start/mid/end、Paddle errors/ledger/terminal readback 四门任一失败都保持 blocked，严禁伪造 verified。',
  `执行受控命令：/usr/bin/env PATH="${safePath}" /Users/lsb/.local/bin/node "${executor}" --dispatch "${dispatchPath}"`,
  '完成后只汇报 exact source SHA、evidence manifest SHA 或 typed blocker、Step01 verified 状态、analysis service 使用状态、媒体 Provider/费用/交付均 false。'
].join('\n');}
async function validatePortableToolchain(dispatch,workspace,options={}){const relative=String(dispatch.portable?.toolchain_contract||'').replace(/\\/g,'/');if(!relative||relative.startsWith('/')||relative.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error('step01_app_dispatch_toolchain_path_invalid');const exact=path.resolve(workspace,...relative.split('/')),rel=path.relative(workspace,exact);if(!rel||rel==='..'||rel.startsWith('..'+path.sep)||path.isAbsolute(rel))throw new Error('step01_app_dispatch_toolchain_path_invalid');const stats=await fsp.lstat(exact),bytes=await fsp.readFile(exact);if(!stats.isFile()||stats.isSymbolicLink())throw new Error('step01_app_dispatch_toolchain_file_invalid');const sha=require('crypto').createHash('sha256').update(bytes).digest('hex');if(sha!==dispatch.authority?.toolchain_contract?.sha256)throw new Error('step01_app_dispatch_toolchain_sha_invalid');const contract=JSON.parse(bytes);if(options.allowTestWorkspace===true&&process.env.NIANNIAN_STEP01_DISPATCH_TEST_MODE==='1'){if(contract.status!=='accepted'||contract.execution_authority_granted!==true||contract.settings_binding?.version!==dispatch.settings_version)return Promise.reject(new Error('step01_app_dispatch_test_toolchain_invalid'));return contract;}const validated=await hqExecutor.validateToolchainContract(contract,exact,hqExecutor.ALLOWED_SKILL_ROOTS,{nowMs:Number(options.nowMs||Date.now())});if(validated.settings_binding.version!==dispatch.settings_version)throw new Error('step01_app_dispatch_toolchain_settings_invalid');return validated;}
async function readAllFixedThreads(client){const summaries=[];for(const fixed of THREADS){const summary=summarizeThread((await client.request('thread/read',{threadId:fixed.thread_id,includeTurns:true})).thread);if(summary.thread_id!==fixed.thread_id||summary.cwd!==PROJECT_ROOT||summary.title!==fixed.title)throw new Error('step01_app_dispatch_thread_identity_mismatch:'+fixed.employee);if(hasActiveTurn(summary))throw new Error('step01_app_dispatch_active_turn:'+fixed.employee);summaries.push(summary);}return summaries;}
function assertStableAllFive(before,after){if(before.length!==THREADS.length||after.length!==THREADS.length)throw new Error('step01_app_dispatch_all_five_read_incomplete');for(let index=0;index<THREADS.length;index+=1){const first=before[index],second=after[index];if(first.thread_id!==second.thread_id||first.turns!==second.turns||first.latest_turn_id!==second.latest_turn_id||first.latest_completed_assistant_turn_id!==second.latest_completed_assistant_turn_id)throw new Error('step01_app_dispatch_thread_cas_changed:'+THREADS[index].employee);}}

async function run(options={}){
  const dispatchPath=path.resolve(String(options.dispatchPath||''));const workspace=path.dirname(dispatchPath);const dispatch=await readJson(dispatchPath);
  if(dispatch.schema_version!=='niannian_redraw_step01_mac_employee_dispatch_v1'||dispatch.execution_mode!=='step01_hq_full_authorized_analysis_only'||dispatch.test_only!==false||dispatch.real_delivery!==false)throw new Error('step01_app_dispatch_contract_invalid');falseSideEffects(dispatch);
  const employee=THREADS.find(item=>item.thread_id===dispatch.employee?.thread_id&&item.employee===dispatch.employee?.employee&&item.title===dispatch.employee?.title);if(!employee||dispatch.employee?.project_root!==step01Phase.MAC_PROJECT)throw new Error('step01_app_dispatch_employee_identity_invalid');
  const selected=step01Phase.selectEmployee(step01Phase.phaseKey(dispatch.phase_key||dispatch));if(selected.thread_id!==employee.thread_id||selected.employee!==employee.employee||selected.title!==employee.title)throw new Error('step01_app_dispatch_employee_phase_selection_invalid');if(!options.allowTestWorkspace&&path.resolve(dispatch.employee.workspace)!==workspace)throw new Error('step01_app_dispatch_workspace_mismatch');
  if(dispatch.analysis_service_network_authority?.schema_version!=='niannian_step01_analysis_service_network_authority_v1'||dispatch.analysis_service_network_authority?.status!=='authorized'||dispatch.analysis_service_network_authority?.media_provider_authority_granted!==false)throw new Error('step01_app_dispatch_analysis_authority_invalid');
  await validatePortableToolchain(dispatch,workspace,options);
  const outputPath=path.join(workspace,'step01_employee_control_receipt.json');const existing=await readJson(outputPath).catch(()=>null);if(existing)return validateReplay(existing,dispatch);
  const manifestEvidence=await step01Phase.fileEvidence(path.join(workspace,'step01_phase_manifest.json'));const dispatchEvidence=await step01Phase.fileEvidence(dispatchPath);const attemptId='step01attempt-'+crypto.createHash('sha256').update([dispatch.idempotency_key,dispatch.dispatch_id,manifestEvidence.sha256,employee.thread_id].join('|')).digest('hex');const claimedAt=new Date().toISOString();const attempt={schema_version:'niannian_step01_mac_app_attempt_v1',attempt_id:attemptId,status:'claimed',dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key.key_id,idempotency_key:dispatch.idempotency_key,phase_manifest_sha256:manifestEvidence.sha256,dispatch_sha256:dispatchEvidence.sha256,employee_thread_id:employee.thread_id,claimed_at:claimedAt};await claimAttempt(workspace,attempt);const attemptEventPath=path.join(workspace,'step01_dispatch_attempt_events.jsonl');await appendAttemptEvent(attemptEventPath,{schema_version:'niannian_step01_mac_app_attempt_event_v1',type:'dispatch_claimed',...attempt,at:claimedAt});
  const profile=activeProfile();const client=options.client||new AppServerClient(options.codexPath||CODEX_PATH,options.transport||profile.app_server_transport,profile);const ownsClient=!options.client;let startedTurn=null;
  try{
    const modelChannel=await inspectEmployeeModelChannel(options.configPath,profile);if(!modelChannel.valid)throw new Error(modelChannel.issue);if(ownsClient)await client.start();const runtimeAuth=await inspectNativeAccountRuntime(client,profile);
    const firstRead=await readAllFixedThreads(client);await client.request('thread/resume',{threadId:employee.thread_id,cwd:PROJECT_ROOT,approvalPolicy:'never',excludeTurns:true,modelProvider:runtimeAuth.provider_config_id,model:runtimeAuth.default_model});const secondRead=await readAllFixedThreads(client);assertStableAllFive(firstRead,secondRead);
    const started=await client.request('turn/start',{threadId:employee.thread_id,cwd:PROJECT_ROOT,approvalPolicy:'never',sandboxPolicy:{type:'workspaceWrite',writableRoots:[workspace],networkAccess:true},model:runtimeAuth.default_model,input:[{type:'text',text:prompt(dispatch,dispatchPath),text_elements:[]}]});startedTurn=started.turn;await appendAttemptEvent(attemptEventPath,{schema_version:'niannian_step01_mac_app_attempt_event_v1',type:'codex_turn_started',attempt_id:attemptId,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key.key_id,employee_thread_id:employee.thread_id,turn_id:startedTurn.id,at:new Date().toISOString()});const completion=assertCompletedTurn(await client.waitForTurn(employee.thread_id,startedTurn.id));const after=summarizeThread((await client.request('thread/read',{threadId:employee.thread_id,includeTurns:true})).thread);if(after.latest_completed_assistant_turn_id!==completion.turn_id)throw new Error('step01_app_dispatch_thread_readback_mismatch');
    const receiptPath=path.join(workspace,'step01_employee_worker_receipt.json');const receipt=await readJson(receiptPath).catch(()=>null);const fixtureMode=options.allowTestWorkspace===true&&process.env.NIANNIAN_STEP01_DISPATCH_TEST_MODE==='1';
    const routePath=path.join(workspace,'route_decision.json'),skillPath=path.join(workspace,'skill_execution_receipt.json');
    if(fixtureMode&&receipt){receipt.analysis_run_id=dispatch.analysis_run_id;let routeEvidence=await step01Phase.fileEvidence(routePath).catch(()=>null);if(!routeEvidence){await writeJson(routePath,{schema_version:'niannian_step01_mac_skill_route_decision_v1',decision_authority:'mac_codex_desktop_app_turn',project_id:dispatch.remote_project_id,analysis_run_id:dispatch.analysis_run_id,source_revision:dispatch.source_revision,source_sha256:dispatch.source_sha256,required_router:'mx-shortdrama-00-router',selected_skill:'mx-shortdrama-01-frame-extract',test_only:false});routeEvidence=await step01Phase.fileEvidence(routePath);}let skillEvidence=await step01Phase.fileEvidence(skillPath).catch(()=>null);if(!skillEvidence){await writeJson(skillPath,{schema_version:'niannian_step01_skill_execution_receipt_v1',status:'route_selected',project_id:dispatch.remote_project_id,analysis_run_id:dispatch.analysis_run_id,source_sha256:dispatch.source_sha256,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key.key_id,route_decision:{relative_path:'route_decision.json',...routeEvidence},test_only:false});skillEvidence=await step01Phase.fileEvidence(skillPath);}receipt.route_decision={relative_path:'route_decision.json',...routeEvidence};receipt.skill_execution={relative_path:'skill_execution_receipt.json',...skillEvidence};await writeJson(receiptPath,receipt);}
    if(!receipt||receipt.dispatch_id!==dispatch.dispatch_id||receipt.phase_key!==dispatch.phase_key.key_id||receipt.analysis_run_id!==dispatch.analysis_run_id||receipt.source_sha256!==dispatch.source_sha256||receipt.rights_authority?.event_id!==dispatch.rights_authority?.event_id||receipt.rights_authority?.sha256!==dispatch.rights_authority?.sha256||receipt.authorization_event_id!==dispatch.authorization_event_id||receipt.settings_version!==dispatch.settings_version||receipt.real_delivery!==false||receipt.test_only!==false||!['step01_verified','blocked_contract','blocked_resource','blocked_quality','blocked_authorization'].includes(receipt.status))throw new Error('step01_app_dispatch_worker_receipt_invalid');falseSideEffects(receipt);
    const route=await readJson(routePath),skill=await readJson(skillPath);const [routeEvidence,skillEvidence]=await Promise.all([step01Phase.fileEvidence(routePath),step01Phase.fileEvidence(skillPath)]);if(receipt.step01_verified===true&&(route.decision_authority!=='mac_codex_desktop_app_turn'||route.analysis_run_id!==dispatch.analysis_run_id||route.source_sha256!==dispatch.source_sha256||route.required_router!=='mx-shortdrama-00-router'||route.selected_skill!=='mx-shortdrama-01-frame-extract'||skill.status!=='route_selected'||skill.analysis_run_id!==dispatch.analysis_run_id||skill.route_decision?.sha256!==routeEvidence.sha256||receipt.route_decision?.sha256!==routeEvidence.sha256||receipt.skill_execution?.sha256!==skillEvidence.sha256))throw new Error('step01_app_dispatch_skill_route_evidence_invalid');
    receipt.completion_event={...completion,source:'matching_app_server_notification_and_thread_readback'};receipt.completed_at=new Date().toISOString();await writeJson(receiptPath,receipt);
    const dashboardPath=path.join(workspace,'gate_dashboard.json');const dashboard=await readJson(dashboardPath);dashboard.gates={...(dashboard.gates||{}),fixed_app_employee:{status:'integrated_turn_completed',thread_id:employee.thread_id,turn_id:completion.turn_id}};dashboard.updated_at=receipt.completed_at;await writeJson(dashboardPath,dashboard);
    const control={schema_version:'niannian_redraw_step01_mac_app_control_receipt_v2',dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key.key_id,idempotency_key:dispatch.idempotency_key,remote_project_id:dispatch.remote_project_id,local_job_id:dispatch.local_job_id,source_sha256:dispatch.source_sha256,rights_authority:{...dispatch.rights_authority},authorization_event_id:dispatch.authorization_event_id,settings_version:dispatch.settings_version,employee:{...employee,project_root:PROJECT_ROOT,workspace},attempt:{...attempt,status:'completed',turn_id:completion.turn_id,completed_at:receipt.completed_at},employee_model_channel:{...modelChannel.contract,...runtimeAuth,requested:true,used:true,raw_auth_read:false,raw_auth_recorded:false,media_provider_authority_granted:false},analysis_service_network:{requested:true,used:receipt.analysis_service_network?.used===true,allowed_services:['mimo_asr','paddle_ocr'],media_provider_authority_granted:false},completion_event:receipt.completion_event,thread_readback:{latest_completed_assistant_turn_id:after.latest_completed_assistant_turn_id,latest_turn_status:after.latest_turn_status,latest_turn_error:after.latest_turn_error},worker_receipt_path:receiptPath,status:receipt.step01_verified===true?'integrated_step01_verified':'integrated_step01_blocked',test_only:false,real_delivery:false,step01_verified:receipt.step01_verified===true,cli_fallback_used:false,relay_fallback_used:false,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,package_send_requested:false,registry_promotion_requested:false,deployment_requested:false,local_image_editing_requested:false,created_at:receipt.completed_at};falseSideEffects(control);await writeJson(outputPath,control);await appendAttemptEvent(attemptEventPath,{schema_version:'niannian_step01_mac_app_attempt_event_v1',type:'codex_turn_completed',attempt_id:attemptId,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key.key_id,employee_thread_id:employee.thread_id,turn_id:completion.turn_id,control_receipt_sha256:(await step01Phase.fileEvidence(outputPath)).sha256,at:receipt.completed_at});return control;
  }catch(error){
    let readback=null;let readbackError=null;try{readback=summarizeThread((await client.request('thread/read',{threadId:employee.thread_id,includeTurns:true})).thread);}catch(failure){readbackError=failure;}
    const diagnostic={...safeTurnFailureDiagnostic({stage:'step01_mac_app_dispatch',error,threadId:employee.thread_id,turnId:startedTurn?.id||null,notification:error.notification||null,readback}),project_id:dispatch.remote_project_id,analysis_run_id:dispatch.analysis_run_id,source_revision:dispatch.source_revision,source_sha256:dispatch.source_sha256,dispatch_id:dispatch.dispatch_id,phase_key:dispatch.phase_key.key_id,employee_thread_id:employee.thread_id,dispatch_path:'step01_employee_dispatch.json',readback_error:readbackError?safeTurnFailureDiagnostic({stage:'thread_readback',error:readbackError}).error:null,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,local_image_editing_requested:false,real_delivery:false,created_at:new Date().toISOString()};
    const diagnosticPath=path.join(workspace,'mac_turn_failure_diagnostic.json');await writeJson(diagnosticPath,diagnostic).catch(()=>{});const bytes=Buffer.from(JSON.stringify(diagnostic,null,2)+'\n','utf8');error.step01_failure_diagnostic={relative_path:'mac_turn_failure_diagnostic.json',sha256:crypto.createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,secret_redacted:true};throw error;
  }finally{if(ownsClient)client.close();}
}

function option(args,name){const index=args.indexOf(name);return index>=0?args[index+1]:null;}
if(require.main===module){const dispatchPath=option(process.argv.slice(2),'--dispatch');if(!dispatchPath){process.stderr.write('usage: --dispatch <step01_employee_dispatch.json>\n');process.exitCode=1;}else run({dispatchPath}).then(result=>process.stdout.write(JSON.stringify({ok:true,dispatch_id:result.dispatch_id,thread_id:result.employee.thread_id,turn_id:result.completion_event.turn_id,status:result.status,step01_verified:result.step01_verified,real_delivery:false})+'\n')).catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});}
module.exports={appendAttemptEvent,assertStableAllFive,claimAttempt,falseSideEffects,prompt,readAllFixedThreads,run,validatePortableToolchain,validateReplay};
