'use strict';

const fs=require('fs');
const os=require('os');
const path=require('path');

const PROFILES=Object.freeze({
  asxs:Object.freeze({provider_id:'asxs',display_name:'ASXS Responses',config_provider_id:'codex_local_access',provider_name:'ASXS Responses',base_url:'https://api.asxs.top/v1',wire_api:'responses',app_server_transport:'stdio',requires_openai_auth:false,model:null,review_model:null,model_reasoning_effort:null,disable_response_storage:null,network_access:null,provider_env_key:'KRILL_CODEX_API_KEY',process_env_keys:Object.freeze(['KRILL_CODEX_API_KEY']),keychain_service:'fun.cauai.niannian.employee-model.asxs',keychain_account:'asxs-responses-api-key',enabled:true,selected:false,legacy:true}),
  mcgrox:Object.freeze({provider_id:'mcgrox',display_name:'McGrox Responses (legacy)',config_provider_id:'codex_local_access',provider_name:'OpenAI',base_url:'https://www.mcgrox.top',wire_api:'responses',app_server_transport:'stdio',credential_mode:'cockpit_managed_auth',requires_openai_auth:true,model:'gpt-5.5',review_model:'gpt-5.5',model_reasoning_effort:'xhigh',disable_response_storage:true,network_access:'enabled',provider_env_key:null,process_env_keys:Object.freeze([]),keychain_service:null,keychain_account:null,enabled:true,selected:false,legacy:true}),
  native_account:Object.freeze({provider_id:'native_account',display_name:'Codex native account',config_provider_id:'openai',provider_name:'OpenAI',base_url:null,wire_api:'responses',app_server_transport:'stdio',credential_mode:'native_account',requires_openai_auth:true,model:null,review_model:null,model_reasoning_effort:null,disable_response_storage:null,network_access:null,provider_env_key:null,process_env_keys:Object.freeze([]),keychain_service:null,keychain_account:null,launch_overrides:Object.freeze(['model_provider="openai"']),enabled:true,selected:true,legacy:false})
});
const DEFAULT_PROVIDER_ID='native_account';
const CONFIG_PATH=path.join(os.homedir(),'.config','ai-brain','employee-model-profile.json');
function validateProfile(profile){if(!profile||typeof profile!=='object'||!Object.values(PROFILES).some(item=>item.provider_id===profile.provider_id)||profile.enabled!==true||profile.wire_api!=='responses'||!['stdio','proxy'].includes(profile.app_server_transport)||!['keychain_process_injection','cockpit_managed_auth','native_account'].includes(profile.credential_mode||'keychain_process_injection')||!profile.config_provider_id||!profile.provider_name||typeof profile.requires_openai_auth!=='boolean'||!Array.isArray(profile.process_env_keys)||(profile.credential_mode==='keychain_process_injection'&&!profile.process_env_keys.length)||(['cockpit_managed_auth','native_account'].includes(profile.credential_mode)&&profile.process_env_keys.length))throw new Error('employee_model_profile_rejected');if(profile.credential_mode==='native_account'){if(profile.config_provider_id!=='openai'||profile.base_url!==null||!Array.isArray(profile.launch_overrides)||profile.launch_overrides.length!==1||profile.launch_overrides[0]!=='model_provider="openai"'||profile.legacy!==false)throw new Error('employee_model_native_profile_rejected');}else{let url;try{url=new URL(profile.base_url)}catch{throw new Error('employee_model_profile_url_invalid')}if(url.protocol!=='https:'||url.username||url.password||url.port||/^\d{1,3}(?:\.\d{1,3}){3}$/.test(url.hostname)||url.pathname!=='/'&&url.pathname!=='/v1')throw new Error('employee_model_profile_url_rejected');}for(const key of profile.process_env_keys)if(!/^[A-Z][A-Z0-9_]{2,80}$/.test(key))throw new Error('employee_model_profile_env_key_invalid');return profile;}
function activeProfile(options={}){const configPath=options.configPath||CONFIG_PATH;let id=DEFAULT_PROVIDER_ID;try{const row=JSON.parse(fs.readFileSync(configPath,'utf8'));if(row&&typeof row.selected_provider_id==='string')id=row.selected_provider_id;}catch(error){if(error.code!=='ENOENT')throw new Error('employee_model_profile_config_invalid')}const selected=validateProfile(PROFILES[id]);return selected.legacy===true&&options.allowLegacy!==true?validateProfile(PROFILES[DEFAULT_PROVIDER_ID]):selected;}
function selectProfile(providerId,options={}){const profile=validateProfile(PROFILES[String(providerId||'')]);const configPath=options.configPath||CONFIG_PATH;fs.mkdirSync(path.dirname(configPath),{recursive:true,mode:0o700});const payload=Buffer.from(JSON.stringify({schema_version:'niannian_employee_model_profile_selection_v1',selected_provider_id:profile.provider_id,selected_at:new Date().toISOString(),secret_recorded:false},null,2)+'\n','utf8');const tmp=configPath+'.tmp-'+process.pid;fs.writeFileSync(tmp,payload,{flag:'wx',mode:0o600});fs.renameSync(tmp,configPath);return safeProfile(profile);}
function appServerLaunchArgs(profile=activeProfile(),transport=profile.app_server_transport){const p=validateProfile(profile);const command=transport==='proxy'?['app-server','proxy']:['app-server','--stdio'];const overrides=p.credential_mode==='native_account'?[...p.launch_overrides]:[];return [...overrides.flatMap(value=>['-c',value]),...command];}
function safeProfile(profile){const p=validateProfile(profile);return {provider_id:p.provider_id,display_name:p.display_name,config_provider_id:p.config_provider_id,provider_name:p.provider_name,base_url:p.base_url,wire_api:p.wire_api,app_server_transport:p.app_server_transport,credential_mode:p.credential_mode||'keychain_process_injection',requires_openai_auth:p.requires_openai_auth,model:p.model,review_model:p.review_model,model_reasoning_effort:p.model_reasoning_effort,disable_response_storage:p.disable_response_storage,network_access:p.network_access,provider_env_key:p.provider_env_key,process_env_keys:[...p.process_env_keys],keychain_service:p.keychain_service,keychain_account:p.keychain_account,launch_mode:p.credential_mode==='native_account'?'native_account':'configured_provider',launch_overrides:p.credential_mode==='native_account'?[...p.launch_overrides]:[],enabled:p.enabled,legacy:p.legacy===true,selected:p.provider_id===activeProfile().provider_id};}
module.exports={CONFIG_PATH,DEFAULT_PROVIDER_ID,PROFILES,activeProfile,appServerLaunchArgs,safeProfile,selectProfile,validateProfile};
