'use strict';

const crypto=require('crypto');
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');

const PROJECT_ROOT='/Users/lsb/AI-Brain/niannian-ai-canonical-local';
const OUTPUT_ROOT=path.join(PROJECT_ROOT,'output','mac-employee-training');
const AUTHORITY_FILE='analysis-service-cost-authority-NN-20260715083045-8120F5.json';
const ALLOWED_ERRORS=new Set(['analysis_cost_policy_evidence_invalid','analysis_cost_policy_identity_invalid','analysis_cost_policy_scope_invalid','analysis_cost_authority_identity_invalid','analysis_cost_authority_scope_invalid','hq_composite_cost_authority_invalid','hq_composite_cost_authority_scope_invalid','hq_composite_governance_binding_invalid','hq_composite_keychain_credential_unavailable','hq_composite_mimo_transcript_empty','hq_composite_mimo_auth_rejected','hq_composite_mimo_rate_limited','hq_composite_mimo_network_failed','hq_composite_mimo_upstream_failed','hq_composite_paddle_job_id_missing','hq_composite_paddle_terminal_failed','hq_composite_paddle_timeout','hq_composite_paddle_result_url_missing','hq_composite_paddle_result_empty','hq_composite_paddle_auth_rejected','hq_composite_paddle_rate_limited','hq_composite_paddle_network_failed','hq_composite_paddle_upstream_failed','hq_v2_upstream_invalid','hq_v2_upstream_binding_invalid','hq_v2_entrypoint_invalid','hq_v2_host_invalid','hq_v2_evidence_not_regular','hq_v2_settings_invalid','capability_status_contract_invalid','capability_status_missing','checked_at_invalid','checked_at_stale','credential_expired','evidence_invalid','gate_missing','gate_missing_or_binding_invalid','hq_composite_or_prerequisite_invalid','runtime_capability_audit_failed','runtime_capability_status_invalid','status_invalid','step01_hq_gate_v2_failed','step01_hq_capability_sync_audit_invalid','step01_hq_capability_sync_freshness_invalid','step01_hq_capability_sync_gate_not_ready','step01_hq_capability_sync_status_invalid','step01_hq_promotion_binding_invalid','step01_hq_promotion_bundle_invalid','step01_hq_promotion_bundle_path_invalid','step01_hq_promotion_candidate_invalid','step01_hq_promotion_evidence_invalid','step01_hq_promotion_gate_invalid','step01_hq_promotion_output_invalid','step01_hq_promotion_override_forbidden','step01_hq_promotion_side_effect_invalid','step01_hq_promotion_upstream_invalid','v2_adoption_candidate_binding_invalid','v2_adoption_candidate_invalid','v2_adoption_employee_response_binding_invalid','v2_adoption_employee_response_json_invalid','v2_adoption_entrypoint_mismatch','v2_adoption_install_invalid','v2_adoption_install_parity_mismatch','v2_adoption_manifest_mismatch','v2_adoption_parity_invalid','v2_adoption_replay_invalid','v2_adoption_replay_manifest_invalid','v2_adoption_replay_thread_set_invalid','v2_adoption_side_effect_contract_invalid','v2_adoption_thread_identity_invalid']);
const LOGS=Object.freeze(['step01-hq-composite-probe-run.log','step01-hq-composite-agent.err.log','step01-hq-composite-agent.out.log']);
const SAFE_STAGES=Object.freeze(['evidence','keychain_secret','build_synthetic_media','run_mimo','run_paddle','validate_authority','main']);
const SAFE_EXCEPTION_TYPES=new Set(['CalledProcessError','ConnectionError','ConnectTimeout','Error','HTTPError','JSONDecodeError','ReadTimeout','RequestException','RuntimeError','SSLError','SyntaxError','Timeout','TimeoutError','TypeError','ValueError']);
function sha256(bytes){return crypto.createHash('sha256').update(bytes).digest('hex');}
async function evidence(filePath){const stats=await fsp.lstat(filePath).catch(()=>null);if(!stats)return null;if(!stats.isFile()||stats.isSymbolicLink()||stats.size>1024*1024)throw new Error('hq_diagnose_log_invalid');const bytes=await fsp.readFile(filePath);return {sha256:sha256(bytes),bytes:bytes.length,text:bytes.toString('utf8')};}
function typedError(text){const value=String(text||''),matches=value.match(/[a-z][a-z0-9_]{5,100}/g)||[];for(const item of matches)if(ALLOWED_ERRORS.has(item))return item;const provider=value.includes('run_mimo')?'mimo':value.includes('run_paddle')?'paddle':null;if(provider){if(/\b(401|403)\b/.test(value))return `hq_composite_${provider}_auth_rejected`;if(/\b429\b/.test(value))return `hq_composite_${provider}_rate_limited`;if(/ReadTimeout|ConnectTimeout|ConnectionError|NameResolution|SSLError|timed out|Failed to establish a new connection/i.test(value))return `hq_composite_${provider}_network_failed`;if(/\b5\d\d\b|raise_for_status|HTTPError/i.test(value))return `hq_composite_${provider}_upstream_failed`;}return 'hq_composite_opaque_failure';}
function diagnosticFingerprint(text){const value=String(text||''),stages=SAFE_STAGES.filter(stage=>new RegExp(`\\bin ${stage}\\b`).test(value)),types=[];for(const match of value.matchAll(/(?:requests\.exceptions\.)?([A-Za-z]+(?:Error|Timeout)|Timeout)\b/g)){if(SAFE_EXCEPTION_TYPES.has(match[1])&&!types.includes(match[1]))types.push(match[1]);}const http=[];for(const match of value.matchAll(/(?:HTTPError:\s*|\b)([1-5]\d\d)(?=\s+(?:Client|Server) Error)/g)){const status=Number(match[1]);if(!http.includes(status))http.push(status);}const errno=[];for(const match of value.matchAll(/\[Errno\s+(\d{1,4})\]/g)){const code=Number(match[1]);if(!errno.includes(code))errno.push(code);}const lines=value.split(/\r?\n/).map(line=>line.trim()).filter(Boolean),terminal=lines.length?Buffer.from(lines[lines.length-1],'utf8'):Buffer.alloc(0);return {stages,exception_types:types.sort(),http_statuses:http.sort((a,b)=>a-b),errnos:errno.sort((a,b)=>a-b),terminal_line_sha256:sha256(terminal),terminal_line_bytes:terminal.length,raw_text_returned:false};}
function tokenFingerprints(line){const tokens=String(line||'').match(/[A-Za-z][A-Za-z0-9_:.\/-]{2,120}/g)||[];return tokens.slice(-64).map((token,index)=>{const value=Buffer.from(token,'utf8');return {token_index:index,sha256:sha256(value),bytes:value.length};});}
function lineFingerprints(text){return String(text||'').split(/\r?\n/).map((line,index)=>({line,index})).filter(item=>item.line.trim()).slice(-32).map(item=>{const value=Buffer.from(item.line.trim(),'utf8');return {line_index:item.index,sha256:sha256(value),bytes:value.length,token_fingerprints:tokenFingerprints(item.line)};});}
async function diagnose(options={}){const root=path.resolve(options.outputRoot||OUTPUT_ROOT),exitPath=path.join(root,'step01-hq-composite-probe-exit.json'),exit=await evidence(exitPath),authority=await evidence(path.join(root,AUTHORITY_FILE)),logs=[];let selected='';for(const name of LOGS){const item=await evidence(path.join(root,name));if(item){logs.push({name,sha256:item.sha256,bytes:item.bytes,line_fingerprints:lineFingerprints(item.text)});selected+='\n'+item.text;}}let exitCode=null;if(exit){try{exitCode=JSON.parse(exit.text).exit_code??null;}catch{throw new Error('hq_diagnose_exit_receipt_json_invalid');}}let authoritySummary=null;if(authority){let value;try{value=JSON.parse(authority.text);}catch{throw new Error('hq_diagnose_authority_json_invalid');}authoritySummary={sha256:authority.sha256,bytes:authority.bytes,schema_version:value.schema_version||null,status:value.status||null,event_id:value.event_id||null,project_id:value.project_id||null,source_sha256:value.source_sha256||null,settings_version:value.settings_version??null,expires_at:value.expires_at||null,allowed_services:Array.isArray(value.allowed_services)?[...value.allowed_services].sort():null,allowed_purposes:Array.isArray(value.allowed_purposes)?[...value.allowed_purposes].sort():null,scope_false:['media_generation_provider_authority_granted','video_generation_authority_granted','image_generation_authority_granted','dubbing_authority_granted','delivery_authority_granted'].every(key=>value[key]===false),policy_sha256:value.policy_evidence?.sha256||null};}return {schema_version:'niannian_mac_hq_diagnose_v4',status:'complete',project_root_binding:PROJECT_ROOT,read_only:true,fixed_whitelist:true,shell_command_requested:false,provider_network_requested:false,provider_submit_requested:false,spend_requested:false,project_media_processed:false,exit_receipt:exit?{sha256:exit.sha256,bytes:exit.bytes,exit_code:exitCode}:null,authority:authoritySummary,logs,typed_error:typedError(selected),diagnostic_fingerprint:diagnosticFingerprint(selected),diagnosed_at:new Date().toISOString()};}
async function main(){process.stdout.write(JSON.stringify(await diagnose())+'\n');}
if(require.main===module)main().catch(error=>{process.stderr.write(JSON.stringify({ok:false,error:String(error.message||error)})+'\n');process.exitCode=1;});
module.exports={ALLOWED_ERRORS,LOGS,SAFE_EXCEPTION_TYPES,SAFE_STAGES,diagnose,diagnosticFingerprint,lineFingerprints,tokenFingerprints,typedError};
