const fs = require('fs');
const path = require('path');

function qaError(code,message,httpStatus=502){const error=new Error(message||code);error.code=code;error.httpStatus=httpStatus;return error;}
function extractText(value){if(typeof value?.output_text==='string')return value.output_text;for(const item of value?.output||[])for(const content of item?.content||[])if(typeof content?.text==='string')return content.text;throw qaError('STEP03_QA_TEXT_MISSING','视觉 QA 未返回结构化结果');}
function mimeFor(filePath){const extension=path.extname(filePath).toLowerCase();return extension==='.jpg'||extension==='.jpeg'?'image/jpeg':extension==='.webp'?'image/webp':'image/png';}
function schema(){return{type:'object',additionalProperties:false,required:['quality_passed','market_identity_passed','subject_identity_passed','composition_passed','people_count_passed','action_and_hands_passed','props_and_screen_passed','text_language_passed','source_actor_leakage_detected','poster_layout_detected','findings'],properties:{quality_passed:{type:'boolean'},market_identity_passed:{type:'boolean'},subject_identity_passed:{type:'boolean'},composition_passed:{type:'boolean'},people_count_passed:{type:'boolean'},action_and_hands_passed:{type:'boolean'},props_and_screen_passed:{type:'boolean'},text_language_passed:{type:'boolean'},source_actor_leakage_detected:{type:'boolean'},poster_layout_detected:{type:'boolean'},findings:{type:'array',maxItems:20,items:{type:'object',additionalProperties:false,required:['severity','message'],properties:{severity:{type:'string',enum:['info','warning','error']},message:{type:'string',minLength:1,maxLength:600}}}}}};}
function validate(value){const booleans=['quality_passed','market_identity_passed','subject_identity_passed','composition_passed','people_count_passed','action_and_hands_passed','props_and_screen_passed','text_language_passed','source_actor_leakage_detected','poster_layout_detected'];if(!value||booleans.some(key=>typeof value[key]!=='boolean')||!Array.isArray(value.findings))throw qaError('STEP03_QA_SCHEMA_INVALID','视觉 QA 结果不符合合同');const passed=booleans.slice(1,8).every(key=>value[key]===true)&&value.source_actor_leakage_detected===false&&value.poster_layout_detected===false&&!value.findings.some(row=>row?.severity==='error');return{...value,quality_passed:passed,passed};}
function qaReferenceFiles(task,referenceFiles){const isCurrentCharacterBoard=task?.type==='character'&&/character-authority-sheet-v3\.4-ciwei-character-only-board/.test(String(task.prompt||''));return isCurrentCharacterBoard?[]:referenceFiles.slice(0,8);}

function createVisionQaClient(options={}){
  const fetchImpl=options.fetchImpl||global.fetch;
  const base=String(options.baseUrl||process.env.NIANNIAN_STEP03_GPT_API_BASE_URL||'').replace(/\/+$/,'');
  const endpointPath=String(options.responsesPath||process.env.NIANNIAN_STEP03_GPT_RESPONSES_PATH||'/responses');
  const model=String(options.model||process.env.NIANNIAN_STEP03_GPT_MODEL||'gpt-5.6-sol');
  function profile(){const key=String(options.apiKey||process.env.KRILL_CODEX_API_KEY||'').trim();if(!base||!/^https:\/\//.test(base)||!endpointPath.startsWith('/')||!key)throw qaError('KRILL_STEP03_PROFILE_NOT_CONFIGURED','Krill GPT-5.6 服务器 QA 配置未就绪',503);return{key,url:base+endpointPath};}
  async function review({task,outputPath,referenceFiles=[]}){const isCharacterBoard=task.type==='character'&&/character-authority-sheet-v3\.4-ciwei-character-only-board/.test(String(task.prompt||'')),rules=['目标市场人物与环境可信','不保留中国原演员身份','人物数量、站位、动作和手部正确','不得有字幕、标题、海报化构图'];if(isCharacterBoard)rules.push('这是一张只包含一个角色的专业多视图人物总表：多角度、表情、服装细节和肢体连续性格本身不是多人拼贴或海报化构图；必须审查它们是否为同一身份，并逐项核验左侧肖像安全边距、正侧背全身、五个独立服装细节格、六格肢体与造型连续性区、发型连续性、人物辨识度和锁定服装是否一致。人物板中出现手机、文件、票据、花束、钥匙、屏幕、社交帖、姓名牌或任何剧情道具即为失败；剧情道具必须通过独立资产任务审核。');const {key,url}=profile(),content=[{type:'input_text',text:JSON.stringify({purpose:task.purpose,task_type:task.type,prompt:task.prompt,reference_roles:task.references||[],rules})}];for(const filePath of qaReferenceFiles(task,referenceFiles))content.push({type:'input_image',image_url:'data:'+mimeFor(filePath)+';base64,'+fs.readFileSync(filePath).toString('base64')});content.push({type:'input_text',text:'下面是待审核的 RunningHub 输出。'});content.push({type:'input_image',image_url:'data:'+mimeFor(outputPath)+';base64,'+fs.readFileSync(outputPath).toString('base64')});const body={model,store:false,instructions:'你是念念AI独立视觉质量审核器。严格对照参考职责和生成目标，只返回 JSON。生成成功不等于通过；看不清时必须失败。',input:[{role:'user',content}],text:{format:{type:'json_schema',name:'niannian_step03_visual_qa_v1',strict:true,schema:schema()}}};let response;try{response=await fetchImpl(url,{method:'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(Math.max(30000,Number(process.env.NIANNIAN_STEP03_GPT_TIMEOUT_MS||180000)))});}catch(error){throw qaError('KRILL_STEP03_QA_NETWORK_FAILED','Krill 视觉 QA 网络请求失败');}if(!response.ok)throw qaError('KRILL_STEP03_QA_HTTP_'+response.status,'Krill 视觉 QA 请求失败 ('+response.status+')');let value;try{value=JSON.parse(extractText(await response.json()));}catch(error){if(error.code)throw error;throw qaError('STEP03_QA_JSON_INVALID','视觉 QA 未返回有效 JSON');}return validate(value);}
  return{review,probe(){return{configured:Boolean(base&&/^https:\/\//.test(base)&&(options.apiKey||process.env.KRILL_CODEX_API_KEY)),wire_api:'responses',model,provider:'krill'}}};
}

module.exports={createVisionQaClient,schema,validate,extractText,qaReferenceFiles};
