'use strict';

const crypto=require('crypto');
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');
const {fileEvidence,phaseKey,safeRelative,verifyManifest,RETURN_MANIFEST_SCHEMA}=require('./niannian_redraw_step01_mac_app_phase_transport');
const {buildStep01EvidencePackage,validateStep01EvidencePackage}=require('./niannian_step01_evidence_package');
const {appendEvidenceEvent,readEvidenceEvents,reduceEvidenceEvents}=require('./niannian_step01_evidence_events');
const FIXED_EMPLOYEE_THREADS=new Set(['019f6201-c013-7cf3-b155-61d2789085f4','019f6201-cb91-7cf0-819e-696eeabd9e78','019f6201-d5e8-7083-884d-c714eb1a78b0','019f6201-dff9-7f63-94d8-7f9020b3c223','019f6201-ea1b-7e22-9dd0-a3b851b15b69']);
const EXPECTED_SKILL_BUNDLE={bundle_id:'niannian-mac-production-skills-v2',artifact_set_id:'macskillset-ceb5015e5d4b129e5e2eb5a7a89af468eed547d43df2c50780dde5f26aba3549',manifest_sha256:'59035cd1b97540ec85c926d4e957c3766b8c106012af725b0abad2f8d1548b09'};
const EXPECTED_ROUTER_SKILL={skill_id:'mx-shortdrama-00-router',exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-00-router/SKILL.md',sha256:'c63ebadfae8d37002c441d1508380f359a3782aead52ce1150f6404c0c553486',bytes:47517};
const EXPECTED_STEP_SKILL={skill_id:'mx-shortdrama-01-frame-extract',exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/SKILL.md',sha256:'c4566dcf0c753a009d5025b470f34ba31ae52b71f9e4e471cf7794da5e87010f',bytes:27494};
const EXPECTED_SCRIPT_ENTRYPOINTS={
  build_audio_evidence:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/scripts/build_audio_evidence.py',sha256:'d394dbac331acc6557820d6de2ba99fc5054eb4e0a41f04aa52aaf778d563b3a',bytes:95096},
  qwen3_forced_aligner_worker:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/scripts/qwen3_forced_aligner_worker.py',sha256:'70315afbb36b3103e4ddc32386a59c976d0ceeea1211c6596b4bb4ee616ab30d',bytes:15963},
  extract_episode_frames:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/scripts/extract_episode_frames.py',sha256:'934e66e71ff1e2e0511c94ebf50e6eaf1efc61528b976330f1d136e56026c76d',bytes:28906},
  enhance_episode_evidence:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/scripts/enhance_episode_evidence.py',sha256:'cedd9424b1e265744e63251c933c3d9e2ac0a02ac16b9de0383957fba57c2904',bytes:19244},
  smart_selective_ocr:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-02-source-timeline/scripts/smart_selective_ocr.py',sha256:'210a2508938aa17880b2280d2863ac709988ce421637d417daac21923808e8bc',bytes:47080},
  validate_episode_evidence:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/scripts/validate_episode_evidence.py',sha256:'089200e8e16db91b0b69c7cc4f9fb4f431db75daefff7935ae0571899c5a3deb',bytes:13906},
  finalize_step01_evidence:{exact_path:'/Users/lsb/.codex/skills/mx-shortdrama-01-frame-extract/scripts/finalize_step01_evidence.py',sha256:'18d0e3ea98774fc70232fabf9eb8a57faee3dbe9970e388a0009124281212feb',bytes:29369}
};

function isInside(parent,candidate,allowRoot=false){const relative=path.relative(path.resolve(parent),path.resolve(candidate));if(!relative)return allowRoot;return relative!=='..'&&!relative.startsWith('..'+path.sep)&&!path.isAbsolute(relative);}
async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}
async function atomicJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});const temp=filePath+'.tmp-'+process.pid+'-'+crypto.randomBytes(3).toString('hex');await fsp.writeFile(temp,JSON.stringify(value,null,2)+'\n',{encoding:'utf8',flag:'wx'});await fsp.rename(temp,filePath);}
async function copyExact(source,destination){const stats=await fsp.lstat(source);if(!stats.isFile()||stats.isSymbolicLink())throw new Error('step01_reducer_source_file_invalid');await fsp.mkdir(path.dirname(destination),{recursive:true});await fsp.copyFile(source,destination,fs.constants.COPYFILE_EXCL);}
function falseSideEffects(value){for(const key of ['media_provider_network_requested','media_provider_submit_requested','media_provider_upload_requested','spend_requested','package_send_requested','registry_promotion_requested','deployment_requested','local_image_editing_requested'])if(value?.[key]!==false)throw new Error('step01_reducer_side_effect_invalid:'+key);}
function artifactRoles(ledger){return new Set((ledger?.artifacts||[]).filter(item=>item.status==='verified').map(item=>String(item.artifact_id||item.relative_path||'').toLowerCase()));}
function requireVerifiedRoles(ledger){const roles=[...artifactRoles(ledger)];for(const pattern of [/step01_evidence_manifest/,/(?:validation|validate)/,/(?:reconciliation|idempotency)/,/(?:mimo|asr)/,/(?:aligner|alignment)/,/(?:transnet|shot)/,/(?:ocr|paddle)/,/(?:native|frame)/])if(!roles.some(role=>pattern.test(role)))throw new Error('step01_reducer_verified_artifact_role_missing:'+pattern.source);}
function exactRecord(actual,expected){return actual&&Object.keys(expected).every(key=>actual[key]===expected[key]);}
function validateSkillAuthority(route,skillReceipt){if(!exactRecord(route.router_skill,EXPECTED_ROUTER_SKILL)||!exactRecord(route.step_skill,EXPECTED_STEP_SKILL)||!exactRecord(skillReceipt.router_skill,EXPECTED_ROUTER_SKILL)||!exactRecord(skillReceipt.step_skill,EXPECTED_STEP_SKILL))throw new Error('step01_reducer_skill_file_authority_invalid');const actual=skillReceipt.script_entrypoints;if(!actual||Object.keys(actual).length!==Object.keys(EXPECTED_SCRIPT_ENTRYPOINTS).length||Object.entries(EXPECTED_SCRIPT_ENTRYPOINTS).some(([key,value])=>!exactRecord(actual[key],value)))throw new Error('step01_reducer_script_entrypoint_authority_invalid');}
async function appendEvent(filePath,event){await fsp.mkdir(path.dirname(filePath),{recursive:true});await fsp.appendFile(filePath,JSON.stringify(event)+'\n','utf8');}
async function reconcileStep01Return(options={}){
  const jobRoot=path.resolve(String(options.jobRoot||''));const stateRoot=path.resolve(String(options.canonicalJobRoot||jobRoot));const returnRoot=path.resolve(String(options.returnRoot||''));if(!isInside(path.dirname(jobRoot),jobRoot,true)||!isInside(path.dirname(stateRoot),stateRoot,true))throw new Error('step01_reducer_job_root_invalid');const returnManifestEvidence=await fileEvidence(path.join(returnRoot,'step01_return_transport_manifest.json'));const verified=await verifyManifest(returnRoot,'step01_return_transport_manifest.json',RETURN_MANIFEST_SCHEMA,options.expectedManifestSha256||returnManifestEvidence.sha256,options.expectedPhase);
  const [dispatch,route,skillReceipt,reconciliation,receipt,control,evidenceManifest,checkpoint,dashboard,ledger,result,task,authorization,rights]=await Promise.all(['step01_employee_dispatch.json','route_decision.json','skill_execution_receipt.json','evidence/analysis_service_reconciliation.json','step01_employee_worker_receipt.json','step01_employee_control_receipt.json','step01_evidence_manifest.json','checkpoint.json','gate_dashboard.json','artifact_ledger.json','result_manifest.json'].map(name=>readJson(path.join(returnRoot,name))).concat([readJson(path.join(jobRoot,'task.json')),readJson(path.join(jobRoot,'step01_authorization.json')),readJson(path.join(jobRoot,'rights_authority.json'))]));
  const rightsEvidence=await fileEvidence(path.join(jobRoot,'rights_authority.json'));const phase=phaseKey(dispatch.phase_key||dispatch);if(phase.canonical!==verified.phase.canonical||task.remote_job_id!==phase.remote_project_id||task.job_id!==phase.local_job_id||task.analysis_run?.id!==dispatch.analysis_run_id||Number(task.analysis_run?.source_revision)!==Number(dispatch.source_revision)||task.source_video?.sha256!==phase.source_sha256||rights.status!=='confirmed'||rights.revoked!==false||rights.event_id!==phase.rights_authority_event_id||rightsEvidence.sha256!==phase.rights_authority_sha256||task.rights_authority?.event_id!==rights.event_id||task.rights_authority?.sha256!==rightsEvidence.sha256||authorization.rights_authority?.event_id!==rights.event_id||authorization.rights_authority?.sha256!==rightsEvidence.sha256||authorization.event_id!==phase.authorization_event_id||authorization.settings_version!==phase.settings_version)throw new Error('step01_reducer_current_authority_binding_invalid');
  if(receipt.dispatch_id!==phase.dispatch_id||receipt.phase_key!==phase.key_id||receipt.source_sha256!==phase.source_sha256||receipt.rights_authority?.event_id!==rights.event_id||receipt.rights_authority?.sha256!==rightsEvidence.sha256||control.dispatch_id!==phase.dispatch_id||control.phase_key!==phase.key_id||control.rights_authority?.event_id!==rights.event_id||control.rights_authority?.sha256!==rightsEvidence.sha256||control.attempt?.status!=='completed'||control.attempt?.dispatch_id!==phase.dispatch_id||control.attempt?.phase_key!==phase.key_id||!/^step01attempt-[a-f0-9]{64}$/.test(String(control.attempt?.attempt_id||''))||!/^[a-f0-9]{64}$/.test(String(control.attempt?.phase_manifest_sha256||''))||!FIXED_EMPLOYEE_THREADS.has(dispatch.employee?.thread_id)||control.employee?.thread_id!==dispatch.employee.thread_id||control.completion_event?.method!=='turn/completed'||control.completion_event?.status!=='completed'||control.completion_event?.error!==null||receipt.completion_event?.method!=='turn/completed'||receipt.completion_event?.status!=='completed'||receipt.completion_event?.error!==null||receipt.completion_event?.turn_id!==control.completion_event.turn_id)throw new Error('step01_reducer_receipt_binding_invalid');falseSideEffects(dispatch);falseSideEffects(receipt);falseSideEffects(control);
  const [routeEvidence,skillEvidence,reconciliationEvidence]=await Promise.all([fileEvidence(path.join(returnRoot,'route_decision.json')),fileEvidence(path.join(returnRoot,'skill_execution_receipt.json')),fileEvidence(path.join(returnRoot,'evidence','analysis_service_reconciliation.json'))]);
  if(receipt.step01_verified===true&&(route.schema_version!=='niannian_step01_mac_skill_route_decision_v1'||route.decision_authority!=='mac_codex_desktop_app_turn'||route.project_id!==phase.remote_project_id||route.analysis_run_id!==task.analysis_run?.id||Number(route.source_revision)!==Number(task.analysis_run?.source_revision)||route.source_sha256!==phase.source_sha256||route.required_router!=='mx-shortdrama-00-router'||route.selected_skill!=='mx-shortdrama-01-frame-extract'||route.test_only!==false||JSON.stringify(route.skill_bundle)!==JSON.stringify(EXPECTED_SKILL_BUNDLE)||skillReceipt.schema_version!=='niannian_step01_skill_execution_receipt_v1'||skillReceipt.status!=='route_selected'||skillReceipt.analysis_run_id!==task.analysis_run?.id||skillReceipt.source_sha256!==phase.source_sha256||skillReceipt.dispatch_id!==phase.dispatch_id||skillReceipt.phase_key!==phase.key_id||skillReceipt.route_decision?.sha256!==routeEvidence.sha256||JSON.stringify(skillReceipt.skill_bundle)!==JSON.stringify(route.skill_bundle)||JSON.stringify(skillReceipt.router_skill)!==JSON.stringify(route.router_skill)||JSON.stringify(skillReceipt.step_skill)!==JSON.stringify(route.step_skill)||receipt.route_decision?.sha256!==routeEvidence.sha256||receipt.route_decision?.bytes!==routeEvidence.bytes||receipt.skill_execution?.sha256!==skillEvidence.sha256||receipt.skill_execution?.bytes!==skillEvidence.bytes))throw new Error('step01_reducer_skill_route_evidence_invalid');
  if(receipt.step01_verified===true)validateSkillAuthority(route,skillReceipt);
  if(receipt.step01_verified===true){const declared=dispatch.analysis_service_idempotency||[],services=reconciliation.services||[];if(reconciliation.schema_version!=='niannian_step01_analysis_service_reconciliation_v1'||reconciliation.status!=='completed_reconciled'||reconciliation.analysis_run_id!==task.analysis_run?.id||reconciliation.source_sha256!==phase.source_sha256||reconciliation.claim?.dispatch_id!==phase.dispatch_id||reconciliation.claim?.phase_key!==phase.key_id||reconciliation.media_provider_authority_granted!==false||reconciliation.test_only!==false||receipt.analysis_service_reconciliation?.relative_path!=='evidence/analysis_service_reconciliation.json'||receipt.analysis_service_reconciliation?.sha256!==reconciliationEvidence.sha256||receipt.analysis_service_reconciliation?.bytes!==reconciliationEvidence.bytes||declared.length!==2||services.length!==2)throw new Error('step01_reducer_analysis_service_reconciliation_invalid');for(const expected of [['mimo_asr','chinese_transcript'],['paddle_ocr','subtitle_text_qa']]){const [serviceId,purpose]=expected,key=crypto.createHash('sha256').update([task.analysis_run.id,phase.source_sha256,serviceId,purpose].join('|')).digest('hex'),declaredItem=declared.find(item=>item.service_id===serviceId&&item.purpose===purpose),service=services.find(item=>item.service_id===serviceId&&item.purpose===purpose);if(declaredItem?.key!==key||service?.key!==key||service.status!=='completed'||!['submitted_once','recovered_prior_receipt'].includes(service.action)||!Array.isArray(service.provider_task_ids)||(serviceId==='paddle_ocr'&&!service.provider_task_ids.length))throw new Error('step01_reducer_analysis_service_reconciliation_invalid:'+serviceId);}}
  if(receipt.analysis_service_network?.media_provider_authority_granted!==false||control.analysis_service_network?.media_provider_authority_granted!==false)throw new Error('step01_reducer_provider_identity_mixed');
  const step01Verified=receipt.status==='step01_verified'&&receipt.step01_verified===true&&control.step01_verified===true&&evidenceManifest.status==='verified'&&evidenceManifest.downstream_consumable===true&&result.step01_verified===true;
  const blocked=String(receipt.status||'').startsWith('blocked_')&&receipt.step01_verified===false&&control.step01_verified===false&&evidenceManifest.downstream_consumable===false;if(!step01Verified&&!blocked)throw new Error('step01_reducer_return_state_invalid');if(step01Verified)requireVerifiedRoles(ledger);
  const eventPath=path.join(stateRoot,'evidence_events.jsonl');const eventBase={project_id:phase.remote_project_id,analysis_run_id:task.analysis_run.id,source_revision:Number(task.analysis_run.source_revision),source_sha256:phase.source_sha256,dispatch_id:phase.dispatch_id,phase_key:phase.key_id};const existingEvents=await readEvidenceEvents(eventPath);if(!existingEvents.some(event=>event.type==='analysis_run_created'&&event.analysis_run_id===task.analysis_run.id&&event.source_sha256===phase.source_sha256))throw new Error('step01_reducer_analysis_run_created_event_missing');const claimed=existingEvents.find(event=>event.type==='dispatch_claimed'&&event.dispatch_id===phase.dispatch_id&&event.phase_key===phase.key_id);if(!claimed||claimed.phase_manifest_sha256!==control.attempt.phase_manifest_sha256||claimed.employee_thread_id!==dispatch.employee.thread_id)throw new Error('step01_reducer_event_first_dispatch_claim_missing_or_mismatched');const started=existingEvents.find(event=>event.type==='codex_turn_started'&&event.dispatch_id===phase.dispatch_id&&event.phase_key===phase.key_id);if(!started||started.phase_manifest_sha256!==control.attempt.phase_manifest_sha256||started.employee_thread_id!==dispatch.employee.thread_id)throw new Error('step01_reducer_event_first_turn_start_missing_or_mismatched');
  const archiveBase=path.join(stateRoot,'step01_fixed_app_returns');const archiveRoot=path.join(archiveBase,phase.key_id+'-'+verified.manifestSha256.slice(0,16));const staging=archiveRoot+'.incoming-'+process.pid+'-'+crypto.randomBytes(3).toString('hex');const existing=await fsp.stat(archiveRoot).then(stats=>stats.isDirectory(),()=>false);
  if(!existing){await fsp.mkdir(staging,{recursive:true});try{for(const item of verified.manifest.files){const relative=safeRelative(item.relative_path);await copyExact(path.join(returnRoot,relative),path.join(staging,relative));}await copyExact(path.join(returnRoot,'step01_return_transport_manifest.json'),path.join(staging,'step01_return_transport_manifest.json'));await fsp.mkdir(archiveBase,{recursive:true});await fsp.rename(staging,archiveRoot);}catch(error){await fsp.rm(staging,{recursive:true,force:true});throw error;}}
  else{const archived=await fileEvidence(path.join(archiveRoot,'step01_return_transport_manifest.json'));if(archived.sha256!==verified.manifestSha256)throw new Error('step01_reducer_archive_conflict');}
  let evidencePackage=null;
  if(step01Verified){
    const analysisRun=task.analysis_run;
    if(!analysisRun?.id||analysisRun.source_sha256!==phase.source_sha256||Number(analysisRun.source_revision)<1)throw new Error('step01_reducer_analysis_run_binding_missing');
    const evidenceRoot=path.join(stateRoot,'analysis_runs',analysisRun.id,'evidence');
    evidencePackage=await buildStep01EvidencePackage({sourceRoot:archiveRoot,outputRoot:evidenceRoot,project:{id:phase.remote_project_id,source:{sha256:phase.source_sha256,bytes:Number(task.source_video?.bytes)},sourceRevision:Number(analysisRun.source_revision)},analysisRun:{id:analysisRun.id}});
    await validateStep01EvidencePackage({outputRoot:evidenceRoot,expected:{projectId:phase.remote_project_id,analysisRunId:analysisRun.id,sourceSha256:phase.source_sha256,sourceRevision:Number(analysisRun.source_revision)}});
    const customerArtifacts=[
      {artifact_id:'step01_customer_evidence_index',...evidencePackage.index},
      {artifact_id:'step01_customer_delivery_manifest',...evidencePackage.delivery},
      {artifact_id:'step01_customer_delivery_receipt',...evidencePackage.receipt},
      {artifact_id:'step01_customer_evidence_bundle',...evidencePackage.bundle}
    ].map(item=>({artifact_id:item.artifact_id,node_id:'step01_evidence',exact_path:item.exact_path,sha256:item.sha256,bytes:item.bytes,status:'verified',downstream_consumable_by:item.artifact_id==='step01_customer_evidence_bundle'?['website_download']:['website_preview','Step02']}));
    ledger.artifacts=(Array.isArray(ledger.artifacts)?ledger.artifacts:[]).filter(item=>!customerArtifacts.some(candidate=>candidate.artifact_id===item.artifact_id)).concat(customerArtifacts);
  }
  const now=new Date().toISOString();const status={schema_version:'niannian_step01_status_v4',job_id:phase.local_job_id,status:step01Verified?'evidence_ready':receipt.production_status||receipt.status,current_node:step01Verified?'Step02':'Step01',earliest_incomplete_node:step01Verified?'Step02':'Step01',next_skill:step01Verified?'mx-shortdrama-02-source-timeline':'mx-shortdrama-01-frame-extract',blocker:step01Verified?null:receipt.blocker||{code:receipt.status},next_action:step01Verified?'原片事实证据包已生成；Step02 只消费 exact Step01 evidence manifest SHA。':'按 typed blocker 修复后恢复同一 phase；不得降级或重复 analysis-service job。',rights_authority:{event_id:rights.event_id,sha256:rightsEvidence.sha256,status:'confirmed',revoked:false},analysis_run:step01Verified?{id:task.analysis_run.id,source_revision:task.analysis_run.source_revision,source_sha256:phase.source_sha256}:null,evidence_package:step01Verified?{index:{exact_path:evidencePackage.index.exact_path,sha256:evidencePackage.index.sha256,bytes:evidencePackage.index.bytes},delivery:{exact_path:evidencePackage.delivery.exact_path,sha256:evidencePackage.delivery.sha256,bytes:evidencePackage.delivery.bytes},bundle:{exact_path:evidencePackage.bundle.exact_path,sha256:evidencePackage.bundle.sha256,bytes:evidencePackage.bundle.bytes,file_name:evidencePackage.bundle.file_name},status:'evidence_ready'}:null,fixed_app_return:{phase_key:phase.key_id,manifest_sha256:verified.manifestSha256,employee_thread_id:dispatch.employee.thread_id,turn_id:control.completion_event.turn_id,archive_root:archiveRoot},updated_at:now};
  checkpoint.fixed_app_return=status.fixed_app_return;checkpoint.updated_at=now;dashboard.fixed_app_return=status.fixed_app_return;dashboard.updated_at=now;ledger.fixed_app_return=status.fixed_app_return;ledger.updated_at=now;result.fixed_app_return=status.fixed_app_return;result.transport_success=true;result.user_visible_acceptance=false;result.real_delivery=false;result.updated_at=now;
  if(step01Verified){
    const evidencePointer=status.evidence_package;
    checkpoint.status='evidence_ready';checkpoint.current_step='Step02';checkpoint.completed=[...new Set([...(checkpoint.completed||[]),'Step01 customer evidence package verified'])];checkpoint.step01_evidence_package=evidencePointer;checkpoint.next_action='原片事实证据包已生成；下一阶段只能消费 exact evidence manifest SHA。';
    dashboard.current_node='Step02';dashboard.overall_status='evidence_ready_step02_ready';dashboard.gates={...(dashboard.gates||{}),Step01:{status:'evidence_ready',evidence_index_sha256:evidencePointer.index.sha256,bundle_sha256:evidencePointer.bundle.sha256},Step02:{status:'ready'}};dashboard.step01_evidence_package=evidencePointer;
    result.status='evidence_ready';result.success=true;result.step01_verified=true;result.step01_evidence_package=evidencePointer;result.artifacts=ledger.artifacts;
  }
  await appendEvidenceEvent(eventPath,{...eventBase,type:'skill_route_selected',status:route.selected_skill||'blocked_contract',evidence_sha256:routeEvidence.sha256});
  await appendEvidenceEvent(eventPath,{...eventBase,type:'analysis_service_task_reconciled',status:receipt.analysis_service_network?.used===true?'used':'not_used',evidence_sha256:reconciliationEvidence.sha256});
  await appendEvidenceEvent(eventPath,{...eventBase,type:'codex_turn_completed',status:control.completion_event.status,evidence_sha256:String(control.completion_event.turn_id)});
  await appendEvidenceEvent(eventPath,{...eventBase,type:'return_manifest_received',status:'return_received',evidence_sha256:verified.manifestSha256});
  await appendEvidenceEvent(eventPath,{...eventBase,type:'artifact_paths_verified',status:step01Verified?'verified':'blocked',evidence_sha256:evidenceManifest.status==='verified'?(await fileEvidence(path.join(returnRoot,'step01_evidence_manifest.json'))).sha256:verified.manifestSha256});
  if(step01Verified){await appendEvidenceEvent(eventPath,{...eventBase,type:'step01_validation_passed',status:'passed',evidence_sha256:evidencePackage.index.validation.receipt_sha256});await appendEvidenceEvent(eventPath,{...eventBase,type:'step01_evidence_accepted',status:'evidence_ready',evidence_sha256:evidencePackage.bundle.sha256});}
  else await appendEvidenceEvent(eventPath,{...eventBase,type:'blocker_observed',status:String(receipt.status||'blocked_contract'),evidence_sha256:verified.manifestSha256,blocker:receipt.blocker||null});
  const reduced=reduceEvidenceEvents(await readEvidenceEvents(eventPath),{projectId:phase.remote_project_id,analysisRunId:task.analysis_run.id,sourceSha256:phase.source_sha256,sourceRevision:Number(task.analysis_run.source_revision)});if(step01Verified&&(!reduced.accepted||reduced.status!=='evidence_ready'))throw new Error('step01_reducer_event_replay_not_accepted');status.reducer={status:reduced.status,event_count:reduced.eventCount,last_event_id:reduced.lastEvent?.event_id||null};dashboard.reducer=status.reducer;result.reducer=status.reducer;
  await Promise.all([atomicJson(path.join(stateRoot,'status.json'),status),atomicJson(path.join(stateRoot,'checkpoint.json'),checkpoint),atomicJson(path.join(stateRoot,'gate_dashboard.json'),dashboard),atomicJson(path.join(stateRoot,'artifact_ledger.json'),ledger),atomicJson(path.join(stateRoot,'result_manifest.json'),result),atomicJson(path.join(stateRoot,'step01_employee_dispatch.json'),dispatch),atomicJson(path.join(stateRoot,'route_decision.json'),route),atomicJson(path.join(stateRoot,'skill_execution_receipt.json'),skillReceipt),atomicJson(path.join(stateRoot,'step01_evidence_manifest.json'),evidenceManifest),atomicJson(path.join(stateRoot,'step01_employee_worker_receipt.json'),receipt),atomicJson(path.join(stateRoot,'step01_employee_control_receipt.json'),control),fsp.copyFile(path.join(returnRoot,'worker_report.md'),path.join(stateRoot,'worker_report.md'))]);
  return {status:step01Verified?'step01_evidence_ready_reconciled':'step01_blocked_reconciled',step01_verified:step01Verified,evidence_ready:step01Verified,evidence_package:status.evidence_package,phase_key:phase.key_id,return_manifest_sha256:verified.manifestSha256,employee_thread_id:dispatch.employee.thread_id,turn_id:control.completion_event.turn_id,archive_root:archiveRoot,analysis_service_network_used:receipt.analysis_service_network?.used===true,media_provider_network_requested:false,media_provider_submit_requested:false,spend_requested:false,real_delivery:false};
}

module.exports={EXPECTED_ROUTER_SKILL,EXPECTED_SCRIPT_ENTRYPOINTS,EXPECTED_SKILL_BUNDLE,EXPECTED_STEP_SKILL,artifactRoles,falseSideEffects,reconcileStep01Return,requireVerifiedRoles,validateSkillAuthority};
