'use strict';

const crypto=require('crypto');
const childProcess=require('child_process');
const fs=require('fs');
const fsp=fs.promises;
const os=require('os');
const path=require('path');

const PROJECT_ROOT='/Users/lsb/AI-Brain/niannian-ai-canonical-local';
const SCRIPT_PATH=PROJECT_ROOT+'/bridge/pull_mac_bridge_bootstrap.sh';
const STATE_PATH=PROJECT_ROOT+'/output/mac-employee-training/mac-bridge-release-state.json';
const INSTALL_RECEIPT_PATH=PROJECT_ROOT+'/output/mac-employee-training/mac-bridge-release-install-receipt.json';
const RECEIPT_ROOT=path.join(os.homedir(),'.local','share','niannian-ai','mac-bridge-install-receipts');
const RECEIPT_SCHEMA='niannian_mac_bridge_install_relay_receipt_v1';

function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
function assertToken(value,pattern,code){const result=String(value||'');if(!pattern.test(result))throw new Error(code);return result;}
async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}
async function fileEvidence(filePath){const stats=await fsp.lstat(filePath);if(!stats.isFile()||stats.isSymbolicLink())throw new Error('mac_bridge_install_relay_file_invalid');const bytes=await fsp.readFile(filePath);return {sha256:sha256(bytes),bytes:bytes.length};}
async function atomicReceipt(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true,mode:0o700});const bytes=Buffer.from(JSON.stringify(value,null,2)+'\n'),temporary=filePath+'.tmp-'+process.pid+'-'+crypto.randomBytes(3).toString('hex');await fsp.writeFile(temporary,bytes,{flag:'wx',mode:0o600});await fsp.rename(temporary,filePath);await fsp.chmod(filePath,0o600);return {sha256:sha256(bytes),bytes:bytes.length};}
function identity(options){return {request_id:assertToken(options.requestId,/^[A-Za-z0-9._-]{8,96}$/,'mac_bridge_install_relay_request_id_invalid'),release_version:assertToken(options.releaseVersion,/^20\d{2}\.\d{2}\.\d{2}\.\d+$/,'mac_bridge_install_relay_version_invalid'),manifest_sha256:assertToken(options.manifestSha256,/^[a-f0-9]{64}$/,'mac_bridge_install_relay_manifest_sha_invalid'),archive_sha256:assertToken(options.archiveSha256,/^[a-f0-9]{64}$/,'mac_bridge_install_relay_archive_sha_invalid')};}
function sameIdentity(receipt,expected){return receipt?.schema_version===RECEIPT_SCHEMA&&receipt.request_id===expected.request_id&&receipt.release_version===expected.release_version&&receipt.manifest_sha256===expected.manifest_sha256&&receipt.archive_sha256===expected.archive_sha256;}
function runFixedScript(options={}){return new Promise((resolve,reject)=>{const child=(options.spawn||childProcess.spawn)('/bin/bash',[options.scriptPath||SCRIPT_PATH],{cwd:options.projectRoot||PROJECT_ROOT,env:{...(options.env||process.env),NIANNIAN_EXPECTED_RELEASE_VERSION:options.releaseVersion,NIANNIAN_EXPECTED_MANIFEST_SHA256:options.manifestSha256,NIANNIAN_EXPECTED_ARCHIVE_SHA256:options.archiveSha256},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout?.on('data',chunk=>{stdout=(stdout+chunk).slice(-8192);});child.stderr?.on('data',chunk=>{stderr=(stderr+chunk).slice(-8192);});const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('mac_bridge_install_relay_timeout'));},Number(options.timeoutMs||300000));child.on('error',error=>{clearTimeout(timer);reject(error);});child.on('exit',code=>{clearTimeout(timer);if(code===0)return resolve({exit_code:0,stdout_sha256:sha256(stdout),stderr_sha256:sha256(stderr)});reject(new Error('mac_bridge_install_relay_script_failed:'+String(code)));});});}
async function runInstall(options={}){
  const overrides=['receiptPath','scriptPath','projectRoot','statePath','installReceiptPath','spawn','env'].some(key=>options[key]!==undefined);if(overrides&&(options.testMode!==true||process.env.NIANNIAN_MAC_BRIDGE_INSTALL_RELAY_TEST_MODE!=='1'))throw new Error('mac_bridge_install_relay_override_forbidden');
  const expected=identity(options),receiptPath=path.resolve(options.receiptPath||path.join(RECEIPT_ROOT,expected.request_id+'.json')),existing=await readJson(receiptPath).catch(error=>error.code==='ENOENT'?null:Promise.reject(error));
  if(existing){if(!sameIdentity(existing,expected))throw new Error('mac_bridge_install_relay_replay_conflict');return {status:existing.status==='installed_verified'?'replayed':'replayed_failed',receipt:existing,receipt_path:receiptPath};}
  const scriptPath=path.resolve(options.scriptPath||SCRIPT_PATH),projectRoot=path.resolve(options.projectRoot||PROJECT_ROOT);if(scriptPath!==path.join(projectRoot,'bridge','pull_mac_bridge_bootstrap.sh'))throw new Error('mac_bridge_install_relay_script_path_invalid');const scriptStats=await fsp.lstat(scriptPath);if(!scriptStats.isFile()||scriptStats.isSymbolicLink())throw new Error('mac_bridge_install_relay_script_invalid');
  try{
    const execution=await runFixedScript({...options,...expected,scriptPath,projectRoot}),statePath=path.resolve(options.statePath||path.join(projectRoot,'output','mac-employee-training','mac-bridge-release-state.json')),installReceiptPath=path.resolve(options.installReceiptPath||path.join(projectRoot,'output','mac-employee-training','mac-bridge-release-install-receipt.json'));
    const [state,installReceipt,stateEvidence,installEvidence]=await Promise.all([readJson(statePath),readJson(installReceiptPath),fileEvidence(statePath),fileEvidence(installReceiptPath)]);
    if(state.schema_version!=='niannian_mac_bridge_install_state_v1'||state.status!=='installed_verified'||state.release_version!==expected.release_version||state.manifest_sha256!==expected.manifest_sha256||installReceipt.schema_version!=='niannian_mac_bridge_install_receipt_v1'||installReceipt.status!=='installed_verified'||installReceipt.release_version!==expected.release_version||installReceipt.manifest_sha256!==expected.manifest_sha256||installReceipt.secret_output!==false||installReceipt.provider_network_requested!==false||installReceipt.provider_submit_requested!==false||installReceipt.project_media_processed!==false||installReceipt.real_delivery!==false)throw new Error('mac_bridge_install_relay_readback_invalid');
    const receipt={schema_version:RECEIPT_SCHEMA,status:'installed_verified',...expected,operation:'fixed_pull_and_sealed_bootstrap',script_path:scriptPath,execution,installed_state:{exact_path:statePath,...stateEvidence},install_receipt:{exact_path:installReceiptPath,...installEvidence},shell_surface:'fixed_script_only',arbitrary_command_allowed:false,provider_network_requested:false,provider_submit_requested:false,project_media_processed:false,spend_requested:false,real_delivery:false,installed_at:state.installed_at,created_at:new Date().toISOString()},evidence=await atomicReceipt(receiptPath,receipt);return {status:'installed_verified',receipt:{...receipt,receipt_sha256:evidence.sha256,receipt_bytes:evidence.bytes},receipt_path:receiptPath};
  }catch(error){const failed={schema_version:RECEIPT_SCHEMA,status:'failed',...expected,error:{message:String(error.message||error).slice(0,500)},shell_surface:'fixed_script_only',arbitrary_command_allowed:false,provider_network_requested:false,provider_submit_requested:false,project_media_processed:false,spend_requested:false,real_delivery:false,created_at:new Date().toISOString()};await atomicReceipt(receiptPath,failed).catch(()=>{});throw error;}
}
async function main(){const [requestId,releaseVersion,manifestSha256,archiveSha256]=process.argv.slice(2);const result=await runInstall({requestId,releaseVersion,manifestSha256,archiveSha256}),receipt=result.receipt;process.stdout.write(JSON.stringify({ok:result.status!=='replayed_failed',status:result.status,request_id:requestId,receipt_path:result.receipt_path,receipt_sha256:receipt.receipt_sha256||sha256(Buffer.from(JSON.stringify(receipt,null,2)+'\n')),receipt_bytes:receipt.receipt_bytes||Buffer.byteLength(JSON.stringify(receipt,null,2)+'\n'),installed_state:receipt.installed_state||null,install_receipt:receipt.install_receipt||null,error:result.status==='replayed_failed'?receipt.error||null:null})+'\n');if(result.status==='replayed_failed')process.exitCode=2;}
if(require.main===module)main().catch(error=>{process.stderr.write(JSON.stringify({ok:false,error:String(error.message||error)})+'\n');process.exitCode=1;});
module.exports={INSTALL_RECEIPT_PATH,PROJECT_ROOT,RECEIPT_ROOT,RECEIPT_SCHEMA,SCRIPT_PATH,STATE_PATH,atomicReceipt,fileEvidence,identity,runFixedScript,runInstall,sameIdentity,sha256};
