'use strict';

const crypto=require('crypto');
const fsp=require('fs').promises;
const os=require('os');
const path=require('path');
const {spawn}=require('child_process');
const {fileEvidence,importMacReturnToWindows,phaseKey,safeRelative}=require('./niannian_redraw_step01_mac_app_phase_transport');
const {THREADS}=require('./mac_codex_app_employee_bootstrap');
const {appendEvidenceEvent}=require('./niannian_step01_evidence_events');

const MAC_ALIAS='niannian-mac';
const MAC_PROJECT='/Users/lsb/AI-Brain/niannian-ai-canonical-local';
const MAC_INBOX='/Users/lsb/.local/share/niannian-ai/step01-phase-inbox';

async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}
function option(args,name){const index=args.indexOf(name);return index>=0?args[index+1]:null;}
function safeRemotePath(value){const normalized=String(value||'');if(!/^\/Users\/lsb\/[A-Za-z0-9._\/-]+$/.test(normalized)||normalized.includes('..'))throw new Error('step01_carrier_remote_path_invalid');return normalized;}
function terminateProcessTree(child){if(!child?.pid)return;if(process.platform==='win32'){try{const killer=spawn('taskkill',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});killer.unref();}catch{try{child.kill();}catch{}}}else{try{process.kill(-child.pid,'SIGTERM');}catch{}try{child.kill('SIGTERM');}catch{}}}
function runProcess(command,args,timeoutMs=6*60*60*1000){return new Promise((resolve,reject)=>{const child=spawn(command,args,{windowsHide:true,stdio:['ignore','pipe','pipe'],detached:process.platform!=='win32'});let stdout='';let stderr='';let settled=false;const finish=(error,result)=>{if(settled)return;settled=true;clearTimeout(timer);error?reject(error):resolve(result);};const timer=setTimeout(()=>{terminateProcessTree(child);finish(new Error('step01_carrier_timeout:'+command));},timeoutMs);child.stdout.on('data',chunk=>{stdout=(stdout+chunk.toString('utf8')).slice(-1024*1024);});child.stderr.on('data',chunk=>{stderr=(stderr+chunk.toString('utf8')).slice(-1024*1024);});child.on('error',()=>finish(new Error('step01_carrier_process_start_failed:'+command)));child.on('close',code=>code===0?finish(null,{stdout,stderr}):finish(new Error('step01_carrier_process_failed:'+command+':'+code+':'+stderr.slice(-1200))));});}
function parseJsonLine(value){for(const line of String(value||'').split(/\r?\n/).reverse()){try{const parsed=JSON.parse(line);if(parsed?.ok===true)return parsed;}catch{}}throw new Error('step01_carrier_result_missing');}
function validateDispatchEnvelope(dispatch,phase){if(dispatch?.schema_version!=='niannian_redraw_step01_mac_employee_dispatch_v1'||dispatch.execution_mode!=='step01_hq_full_authorized_analysis_only'||dispatch.test_only!==false||dispatch.real_delivery!==false||dispatch.phase_key?.key_id!==phase.key_id)throw new Error('step01_carrier_dispatch_contract_invalid');const employee=THREADS.find(item=>item.thread_id===dispatch.employee?.thread_id&&item.employee===dispatch.employee?.employee&&item.title===dispatch.employee?.title);if(!employee||dispatch.employee?.project_root!==MAC_PROJECT)throw new Error('step01_carrier_employee_identity_invalid');for(const key of ['media_provider_network_requested','media_provider_submit_requested','media_provider_upload_requested','spend_requested','deployment_requested','local_image_editing_requested'])if(dispatch[key]!==false)throw new Error('step01_carrier_side_effect_invalid:'+key);if(dispatch.analysis_service_network_authority?.status!=='authorized'||dispatch.analysis_service_network_authority?.media_provider_authority_granted!==false)throw new Error('step01_carrier_analysis_authority_invalid');return employee;}
function validateRemoteResult(result,phase,dispatch){if(!result||result.phase_key!==phase.key_id||result.dispatch_id!==phase.dispatch_id||result.employee_thread_id!==dispatch.employee.thread_id||String(result.workspace||'')!==String(dispatch.employee.workspace||''))throw new Error('step01_carrier_remote_result_invalid');for(const key of ['media_provider_network_requested','media_provider_submit_requested','media_provider_upload_requested','spend_requested','deployment_requested','real_delivery'])if(result[key]!==false)throw new Error('step01_carrier_remote_side_effect_invalid:'+key);if(result.analysis_service_network_requested!==true)return (()=>{throw new Error('step01_carrier_analysis_network_result_invalid');})();return result;}
function terminalWorkerScript(remotePackage,manifestSha){safeRemotePath(remotePackage);if(!/^[a-f0-9]{64}$/.test(manifestSha))throw new Error('step01_carrier_terminal_manifest_invalid');const project=MAC_PROJECT,launcher=project+'/bridge/niannian_redraw_step01_mac_app_phase_worker_launcher.js',node='/Users/lsb/.local/bin/node',stdout=remotePackage+'/.worker-terminal.stdout',stderr=remotePackage+'/.worker-terminal.stderr',exit=remotePackage+'/.worker-terminal-exit.json';return `#!/bin/bash\nset -Eeuo pipefail\nIFS=$'\\n\\t'\numask 077\ncd "${project}"\nrm -f "${exit}" "${stdout}" "${stderr}"\nset +e\n"${node}" "${launcher}" --package "${remotePackage}" --manifest-sha ${manifestSha} >"${stdout}.tmp" 2>"${stderr}.tmp"\nrc=$?\nset -e\n/bin/mv "${stdout}.tmp" "${stdout}"\n/bin/mv "${stderr}.tmp" "${stderr}"\n/usr/bin/printf '{"schema_version":"niannian_step01_terminal_worker_exit_v1","exit_code":%d}\\n' "$rc" >"${exit}.tmp"\n/bin/chmod 600 "${exit}.tmp" "${stdout}" "${stderr}"\n/bin/mv "${exit}.tmp" "${exit}"\nexit "$rc"\n`;}
async function runTerminalWorker(remotePackage,manifestSha,run=runProcess,timeoutMs=6*60*60*1000){const remoteCommand=remotePackage+'/.worker-terminal.command',remoteExit=remotePackage+'/.worker-terminal-exit.json',remoteStdout=remotePackage+'/.worker-terminal.stdout',remoteStderr=remotePackage+'/.worker-terminal.stderr';const localCommand=path.join(os.tmpdir(),'niannian-step01-terminal-'+manifestSha+'.command');await fsp.writeFile(localCommand,terminalWorkerScript(remotePackage,manifestSha),{encoding:'utf8',mode:0o700});try{await copyFileToMac(localCommand,remoteCommand,run);await run('ssh',[MAC_ALIAS,'chmod','700',remoteCommand]);let exit=null;try{exit=JSON.parse((await run('ssh',[MAC_ALIAS,'cat',remoteExit],30000)).stdout);}catch{}if(!exit){await run('ssh',[MAC_ALIAS,'/usr/bin/open','-a','Terminal',remoteCommand],30000);const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,2000));try{exit=JSON.parse((await run('ssh',[MAC_ALIAS,'cat',remoteExit],30000)).stdout);break;}catch{}}}if(!exit)throw new Error('step01_carrier_terminal_worker_timeout');if(exit.schema_version!=='niannian_step01_terminal_worker_exit_v1'||!Number.isInteger(exit.exit_code))throw new Error('step01_carrier_terminal_exit_invalid');const [stdout,stderr]=await Promise.all([run('ssh',[MAC_ALIAS,'cat',remoteStdout],30000).then(value=>value.stdout),run('ssh',[MAC_ALIAS,'cat',remoteStderr],30000).then(value=>value.stdout)]);if(exit.exit_code!==0)throw new Error('step01_carrier_terminal_worker_failed:'+exit.exit_code+':'+String(stderr).slice(-1200));return{stdout,stderr};}finally{await fsp.rm(localCommand,{force:true});}}
async function copyFileToMac(localPath,remotePath,run=runProcess){safeRemotePath(remotePath);await run('ssh',[MAC_ALIAS,'mkdir','-p',path.posix.dirname(remotePath)]);await run('scp',[localPath,MAC_ALIAS+':'+remotePath]);}
async function copyFileFromMac(remotePath,localPath,run=runProcess){safeRemotePath(remotePath);await fsp.mkdir(path.dirname(localPath),{recursive:true});await run('scp',[MAC_ALIAS+':'+remotePath,localPath]);}
async function runCarrier(options={}){
  const packageRoot=path.resolve(String(options.packageRoot||''));const expectedManifestSha256=String(options.expectedManifestSha256||'').toLowerCase();const windowsReturnRoot=path.resolve(String(options.windowsReturnRoot||''));if(!/^[a-f0-9]{64}$/.test(expectedManifestSha256))throw new Error('step01_carrier_manifest_sha_invalid');const actual=await fileEvidence(path.join(packageRoot,'step01_phase_manifest.json'));if(actual.sha256!==expectedManifestSha256)throw new Error('step01_carrier_manifest_sha_mismatch');
  const manifest=await readJson(path.join(packageRoot,'step01_phase_manifest.json'));const phase=phaseKey(manifest.phase_key||{});const dispatch=await readJson(path.join(packageRoot,'step01_employee_dispatch.json'));validateDispatchEnvelope(dispatch,phase);const eventLogPath=path.resolve(String(options.eventLogPath||''));if(!eventLogPath)throw new Error('step01_carrier_dispatch_event_log_required');const claim=await appendEvidenceEvent(eventLogPath,{type:'dispatch_claimed',project_id:dispatch.remote_project_id,analysis_run_id:dispatch.analysis_run_id,source_sha256:dispatch.source_sha256,source_revision:dispatch.source_revision,dispatch_id:dispatch.dispatch_id,phase_key:phase.key_id,phase_manifest_sha256:expectedManifestSha256,employee_thread_id:dispatch.employee.thread_id,status:'claimed'});if(claim.dispatch_id!==dispatch.dispatch_id||claim.phase_key!==phase.key_id)throw new Error('step01_carrier_dispatch_event_binding_invalid');const remotePackage=safeRemotePath(MAC_INBOX+'/'+phase.key_id);const run=options.runProcess||runProcess;
  for(const item of [...manifest.files,{relative_path:'step01_phase_manifest.json'}]){const relative=safeRelative(item.relative_path);await copyFileToMac(path.join(packageRoot,...relative.split('/')),remotePackage+'/'+relative,run);}
  const start=await appendEvidenceEvent(eventLogPath,{type:'codex_turn_started',project_id:dispatch.remote_project_id,analysis_run_id:dispatch.analysis_run_id,source_sha256:dispatch.source_sha256,source_revision:dispatch.source_revision,dispatch_id:dispatch.dispatch_id,phase_key:phase.key_id,phase_manifest_sha256:expectedManifestSha256,employee_thread_id:dispatch.employee.thread_id,status:'authorized_before_turn_start'});if(start.dispatch_id!==dispatch.dispatch_id||start.phase_key!==phase.key_id)throw new Error('step01_carrier_turn_start_event_binding_invalid');
  const remoteResult=validateRemoteResult(parseJsonLine((await runTerminalWorker(remotePackage,expectedManifestSha256,run,Number(options.timeoutMs||6*60*60*1000))).stdout),phase,dispatch);const remoteWorkspace=safeRemotePath(remoteResult.workspace);const staging=path.join(os.tmpdir(),'niannian-step01-return-'+phase.key_id+'-'+process.pid+'-'+crypto.randomBytes(3).toString('hex'));await fsp.mkdir(staging,{recursive:true});
  try{
    await copyFileFromMac(remoteWorkspace+'/step01_return_transport_manifest.json',path.join(staging,'step01_return_transport_manifest.json'),run);const returnEvidence=await fileEvidence(path.join(staging,'step01_return_transport_manifest.json'));if(returnEvidence.sha256!==remoteResult.return_manifest_sha256)throw new Error('step01_carrier_return_manifest_sha_mismatch');const returnManifest=await readJson(path.join(staging,'step01_return_transport_manifest.json'));for(const item of returnManifest.files||[]){const relative=safeRelative(item.relative_path);await copyFileFromMac(remoteWorkspace+'/'+relative,path.join(staging,...relative.split('/')),run);}
    const imported=await importMacReturnToWindows({packageRoot:staging,expectedManifestSha256:remoteResult.return_manifest_sha256,expectedPhase:phase,windowsReturnRoot});const cleanupPath=MAC_PROJECT+'/bridge/niannian_redraw_step01_mac_app_phase_cleanup.js';const cleanup=parseJsonLine((await run('ssh',[MAC_ALIAS,'/Users/lsb/.local/bin/node',cleanupPath,'--package',remotePackage,'--manifest-sha',expectedManifestSha256,'--phase-key',phase.key_id],2*60*1000)).stdout);if(cleanup.phase_key!==phase.key_id||cleanup.manifest_sha256!==expectedManifestSha256||!['archived_for_recovery','replayed_inbox_removed'].includes(cleanup.status))throw new Error('step01_carrier_cleanup_result_invalid');
    const reconciled=typeof options.reconcile==='function'?await options.reconcile({phase,dispatch,windowsReturnRoot,remoteResult}):null;return {ok:true,status:'cross_device_step01_return_imported',phase_key:phase.key_id,dispatch_id:phase.dispatch_id,employee_thread_id:dispatch.employee.thread_id,completion_event:remoteResult.completion_event,windows_return_root:windowsReturnRoot,return_manifest_sha256:remoteResult.return_manifest_sha256,import_status:imported.status,reconcile_status:reconciled?.status||null,remote_inbox_cleanup_status:cleanup.status,remote_recovery_archive:cleanup.archive_root,analysis_service_network_requested:true,analysis_service_network_used:remoteResult.analysis_service_network_used===true,media_provider_network_requested:false,media_provider_submit_requested:false,media_provider_upload_requested:false,spend_requested:false,deployment_requested:false,real_delivery:false,step01_verified:remoteResult.step01_verified===true};
  }finally{await fsp.rm(staging,{recursive:true,force:true});}
}

async function main(){const args=process.argv.slice(2);const packageRoot=option(args,'--package');const manifestSha=option(args,'--manifest-sha');const returnRoot=option(args,'--windows-return');const eventLogPath=option(args,'--event-log');if(!packageRoot||!manifestSha||!returnRoot||!eventLogPath)throw new Error('usage: --package <path> --manifest-sha <sha256> --windows-return <path> --event-log <evidence_events.jsonl>');process.stdout.write(JSON.stringify(await runCarrier({packageRoot,expectedManifestSha256:manifestSha,windowsReturnRoot:returnRoot,eventLogPath}))+'\n');}
if(require.main===module)main().catch(error=>{process.stderr.write(String(error.message||error)+'\n');process.exitCode=1;});
module.exports={MAC_ALIAS,MAC_INBOX,MAC_PROJECT,copyFileFromMac,copyFileToMac,parseJsonLine,runCarrier,runProcess,runTerminalWorker,safeRemotePath,terminalWorkerScript,terminateProcessTree,validateDispatchEnvelope,validateRemoteResult};
