'use strict';

const crypto=require('crypto');
const fs=require('fs');
const fsp=fs.promises;
const path=require('path');

const EXACT_PROJECT_ID='NN-20260715083045-8120F5';
const EXACT_SOURCE_SHA256='a46f74392e2b3f7ec813b4eba5a0cd9756a7c30225e0033fd671d2cab21cd30c';
const EXACT_SOURCE_BYTES=145897161;
const CURRENT_RECOVERY_SCHEMA='niannian_step01_incomplete_projection_recovery_current_v1';

function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
async function readJson(filePath){return JSON.parse(await fsp.readFile(filePath,'utf8'));}
async function atomicJson(filePath,value){await fsp.mkdir(path.dirname(filePath),{recursive:true});const temporary=filePath+'.tmp-'+process.pid+'-'+crypto.randomBytes(4).toString('hex');await fsp.writeFile(temporary,JSON.stringify(value,null,2)+'\n',{encoding:'utf8',flag:'wx'});await fsp.rename(temporary,filePath);}
async function fileEvidence(filePath){const stats=await fsp.lstat(filePath);if(!stats.isFile()||stats.isSymbolicLink())throw new Error('step01_projection_file_invalid:'+filePath);const bytes=await fsp.readFile(filePath);return {sha256:sha256(bytes),bytes:bytes.length};}
async function sourceEvidence(filePath){const stats=await fsp.lstat(filePath);if(!stats.isFile()||stats.isSymbolicLink())throw new Error('step01_projection_source_invalid');const hash=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(filePath))hash.update(chunk);return {sha256:hash.digest('hex'),bytes:stats.size};}
function isInside(parent,candidate){const relative=path.relative(path.resolve(parent),path.resolve(candidate));return Boolean(relative)&&relative!=='..'&&!relative.startsWith('..'+path.sep)&&!path.isAbsolute(relative);}
function blockedPipeline(){return [{id:'Step01',label:'证据与关键帧',status:'blocked'},{id:'Step02',label:'源片事实账本',status:'blocked'},{id:'Step04',label:'资产与视频提示词',status:'blocked'},{id:'Step05',label:'资产与视频执行',status:'blocked'}];}
function projectionIsReconciled(project,current){return project.status==='blocked'&&project.productionStatus==='blocked_contract'&&project.analysis?.status==='blocked_contract'&&project.analysis?.runId===null&&project.runtime?.step01?.eventLogPresent===false&&project.runtime?.gates?.Step01?.status==='blocked_contract'&&project.runtime?.step02Unlocked===false&&project.runtime?.finalVideoDelivered===false&&current['status.json']?.status==='blocked_contract'&&current['gate_dashboard.json']?.gates?.Step01?.status==='blocked_contract'&&current['result_manifest.json']?.step01_verified===false&&current['result_manifest.json']?.final_video_delivered===false;}
async function verifiedRecoveryPointer(jobRoot,projectId,expectedSha,expectedBytes,current){const markerPath=path.join(jobRoot,'projection_recovery_current.json');let marker=await readJson(markerPath).catch(error=>error.code==='ENOENT'?null:Promise.reject(error));let pointer=marker?.recovery_receipt||null;if(marker&&(marker.schema_version!==CURRENT_RECOVERY_SCHEMA||marker.status!=='current'||marker.project_id!==projectId||marker.source_sha256!==expectedSha||Number(marker.source_bytes)!==expectedBytes))throw new Error('step01_projection_current_marker_invalid');if(!pointer){const artifact=(current['artifact_ledger.json']?.artifacts||[]).find(item=>item.artifact_id==='step01_incomplete_projection_recovery'&&item.status==='verified_structural_only');if(artifact)pointer={exact_path:artifact.exact_path,sha256:artifact.sha256,bytes:artifact.bytes};}if(!pointer)return null;const exact=path.resolve(String(pointer.exact_path||''));if(!isInside(jobRoot,exact))throw new Error('step01_projection_recovery_receipt_path_invalid');const evidence=await fileEvidence(exact);if(evidence.sha256!==pointer.sha256||evidence.bytes!==Number(pointer.bytes))throw new Error('step01_projection_recovery_receipt_hash_invalid');const receipt=await readJson(exact);if(receipt.schema_version!=='niannian_step01_incomplete_projection_recovery_v1'||receipt.status!=='reconciled_incomplete'||receipt.project_id!==projectId||receipt.source_sha256!==expectedSha||Number(receipt.source_bytes)!==expectedBytes||receipt.authoritative_analysis_run_present!==false||receipt.step01_evidence_manifest_present!==false||receipt.real_delivery!==false)throw new Error('step01_projection_recovery_receipt_contract_invalid');if(!marker){marker={schema_version:CURRENT_RECOVERY_SCHEMA,status:'current',project_id:projectId,source_sha256:expectedSha,source_bytes:expectedBytes,recovery_receipt:{exact_path:exact,...evidence},updated_at:new Date().toISOString()};await atomicJson(markerPath,marker);}return {exact_path:exact,...evidence};}

async function reconcile(options={}){
  const root=path.resolve(options.root||path.join(__dirname,'..')),dataRoot=path.resolve(options.dataRoot||path.join(root,'data')),projectId=String(options.projectId||EXACT_PROJECT_ID),expectedSha=String(options.sourceSha256||EXACT_SOURCE_SHA256),expectedBytes=Number(options.sourceBytes||EXACT_SOURCE_BYTES);
  if(options.testMode!==true&&(projectId!==EXACT_PROJECT_ID||expectedSha!==EXACT_SOURCE_SHA256||expectedBytes!==EXACT_SOURCE_BYTES))throw new Error('step01_projection_exact_authority_override_forbidden');
  const projectsPath=path.join(dataRoot,'projects.json'),jobRoot=path.join(dataRoot,'jobs',projectId),projects=await readJson(projectsPath),project=projects.find(item=>item.id===projectId);if(!project)throw new Error('step01_projection_project_missing');
  const source=await sourceEvidence(path.resolve(String(project.source?.storedPath||'')));if(source.sha256!==expectedSha||source.bytes!==expectedBytes||project.source?.sha256!==expectedSha||Number(project.source?.bytes)!==expectedBytes)throw new Error('step01_projection_source_binding_invalid');
  const forbiddenEvidence=['step01_evidence_manifest.json','evidence_events.jsonl'];for(const name of forbiddenEvidence)if(await fsp.lstat(path.join(jobRoot,name)).then(()=>true,error=>error.code==='ENOENT'?false:Promise.reject(error)))throw new Error('step01_projection_authoritative_evidence_present:'+name);
  const analysisRuns=path.join(jobRoot,'analysis_runs');if(await fsp.lstat(analysisRuns).then(()=>true,error=>error.code==='ENOENT'?false:Promise.reject(error)))throw new Error('step01_projection_analysis_run_present');
  const files=['status.json','checkpoint.json','gate_dashboard.json','artifact_ledger.json','result_manifest.json'];const current=Object.fromEntries(await Promise.all(files.map(async name=>[name,await readJson(path.join(jobRoot,name))])));const currentEvidence=Object.fromEntries(await Promise.all(files.map(async name=>[name,await fileEvidence(path.join(jobRoot,name))])));
  if(projectionIsReconciled(project,current)){const replay=await verifiedRecoveryPointer(jobRoot,projectId,expectedSha,expectedBytes,current);if(!replay)throw new Error('step01_projection_reconciled_without_durable_receipt');return {status:'replayed_incomplete_projection',project_id:projectId,source_sha256:expectedSha,recovery_receipt:replay,step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,real_delivery:false};}
  const now=new Date().toISOString(),stamp=now.replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),historyRoot=path.join(jobRoot,'projection_recovery_history',stamp);await fsp.mkdir(path.dirname(historyRoot),{recursive:true});await fsp.mkdir(historyRoot,{recursive:false});for(const name of files)await fsp.copyFile(path.join(jobRoot,name),path.join(historyRoot,name),fs.constants.COPYFILE_EXCL);await atomicJson(path.join(historyRoot,'project_projection.json'),project);
  const blocker={code:'STEP01_SOURCE_ONLY_ANALYSIS_RUN_REQUIRED',blocker_class:'contract',message:'当前没有 source-only analysis run 或真实 Step01 evidence；旧创作参数 task 不得执行。',resume_event:'用户在网站点击开始分析，并在 Mac release/hq_full 能力可用后创建新 run。'};
  const status={schema_version:'niannian_step01_status_v4',job_id:projectId,status:'blocked_contract',current_node:'Step01',earliest_incomplete_node:'Step01',next_skill:'mx-shortdrama-00-router',blocker,next_action:'等待网站创建 source_evidence_only analysis run；随后由固定 Mac Codex App 员工先运行 Router。',step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,updated_at:now};
  const checkpoint={...current['checkpoint.json'],status:'blocked_contract',current_node:'Step01',earliest_incomplete_node:'Step01',blockers:[blocker],historical_blockers:current['checkpoint.json'].blockers||[],next_skill:'mx-shortdrama-00-router',next_action:status.next_action,step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,updated_at:now};
  const dashboard={...current['gate_dashboard.json'],current_node:'Step01',earliest_incomplete_node:'Step01',next_skill:'mx-shortdrama-00-router',overall_status:'blocked_contract',blocker,next_action:status.next_action,gates:{...(current['gate_dashboard.json'].gates||{}),Step01:{status:'blocked_contract',evidence_ready:false},Step02:{status:'blocked_upstream'},Step04:{status:'blocked_upstream'},Step05:{status:'blocked_upstream'},provider_submit:{status:'blocked_no_authority'},package_send:{status:'blocked'}},step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,updated_at:now};
  const recoveryReceipt={schema_version:'niannian_step01_incomplete_projection_recovery_v1',status:'reconciled_incomplete',project_id:projectId,source_sha256:source.sha256,source_bytes:source.bytes,prior_projections:currentEvidence,history_root:historyRoot,authoritative_analysis_run_present:false,step01_evidence_manifest_present:false,step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,real_delivery:false,reconciled_at:now};const receiptPath=path.join(historyRoot,'recovery_receipt.json');await atomicJson(receiptPath,recoveryReceipt);const receiptEvidence=await fileEvidence(receiptPath);
  const recoveryArtifact={artifact_id:'step01_incomplete_projection_recovery',node_id:'Step01',exact_path:receiptPath,sha256:receiptEvidence.sha256,bytes:receiptEvidence.bytes,status:'verified_structural_only',downstream_consumable_by:[],real_delivery:false};const ledger={...current['artifact_ledger.json'],artifacts:(current['artifact_ledger.json'].artifacts||[]).filter(item=>item.artifact_id!==recoveryArtifact.artifact_id).concat([recoveryArtifact]),status:'blocked_contract',step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,updated_at:now};const result={...current['result_manifest.json'],status:'blocked_contract',success:false,packaged:false,transport_success:false,user_visible_acceptance:false,step01_verified:false,evidence_ready:false,step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,real_delivery:false,artifacts:ledger.artifacts,blocker,updated_at:now};
  project.status='blocked';project.productionStatus='blocked_contract';project.analysis={...(project.analysis||{}),status:'blocked_contract',runId:null,sourceRevision:Number(project.sourceRevision||1),sourceSha256:expectedSha,blocker,step01EvidenceDelivered:false,updatedAt:now};project.pipeline=blockedPipeline();project.runtime={...(project.runtime||{}),productionStatus:'blocked_contract',currentNode:'Step01',earliestIncompleteNode:'Step01',nextSkill:'mx-shortdrama-00-router',blocker,nextAction:status.next_action,gateState:'step01_source_only_contract_required',worker:{status:'not_dispatched',mode:'fixed_mac_app_phase',threadId:null,turnId:null,cliFallbackAllowed:false,relayFallbackAllowed:false,updatedAt:now},step01:{schemaVersion:'niannian_step01_projection_v1',eventLogPresent:false,strictPassReproducible:false,step02Unlocked:false,tiers:{basic:{status:'blocked',label:'基础证据'},enhanced:{status:'pending',label:'增强分析'},strict:{status:'blocked',label:'严格验证'}}},gates:{...dashboard.gates},step01EvidenceDelivered:false,step02Unlocked:false,finalVideoDelivered:false,checkpointUpdatedAt:now};project.dispatch={...(project.dispatch||{}),status:'blocked',controllerId:null,leaseId:null,claimedAt:null,leaseUntil:null,heartbeatAt:null,blocker};
  await Promise.all([atomicJson(path.join(jobRoot,'status.json'),status),atomicJson(path.join(jobRoot,'checkpoint.json'),checkpoint),atomicJson(path.join(jobRoot,'gate_dashboard.json'),dashboard),atomicJson(path.join(jobRoot,'artifact_ledger.json'),ledger),atomicJson(path.join(jobRoot,'result_manifest.json'),result),atomicJson(projectsPath,projects)]);await atomicJson(path.join(jobRoot,'projection_recovery_current.json'),{schema_version:CURRENT_RECOVERY_SCHEMA,status:'current',project_id:projectId,source_sha256:expectedSha,source_bytes:expectedBytes,recovery_receipt:{exact_path:receiptPath,...receiptEvidence},updated_at:now});await fsp.appendFile(path.join(jobRoot,'job_events.jsonl'),JSON.stringify({at:now,type:'step01_incomplete_projection_reconciled',project_id:projectId,source_sha256:expectedSha,recovery_receipt_sha256:receiptEvidence.sha256,status:'blocked_contract',real_delivery:false})+'\n','utf8');return {status:'reconciled_incomplete',project_id:projectId,source_sha256:expectedSha,recovery_receipt:{exact_path:receiptPath,...receiptEvidence},step01_evidence_delivered:false,step02_unlocked:false,final_video_delivered:false,real_delivery:false};
}

if(require.main===module)reconcile().then(value=>process.stdout.write(JSON.stringify(value)+'\n')).catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1;});
module.exports={CURRENT_RECOVERY_SCHEMA,EXACT_PROJECT_ID,EXACT_SOURCE_BYTES,EXACT_SOURCE_SHA256,projectionIsReconciled,reconcile,verifiedRecoveryPointer};
